### ISSUE TITLE
Just after clone and try buid I got date_impl.cpp:78:66: error: ‘put_time’ was not declared

### ISSUE THREAD

**Issue by mingodad** [Corvusoft/restbed#1]
restbed/dependency/framework/source/corvusoft/framework/detail/date_impl.cpp:78:66: error: ‘put_time’ was not declared in this scope

**Comment by ben-crowhurst** [comment]
Please provide compiler information.  I think you'll be seeing the following issue.

http://stackoverflow.com/questions/14136833/stdput-time-implementation-status-in-gcc

**Comment by ben-crowhurst** [comment]
@mingodad Was this the cause of your dilemma?

**Comment by ben-crowhurst** [comment]
Closing as OP unresponsive.

**Comment by ben-crowhurst** [comment]
Framework as been collapsed into the core product. This should help resolve many build issues.
