### ISSUE TITLE
Get data from a post request

### ISSUE THREAD

**Issue by Bl4ckb0ne** [Corvusoft/restbed#100]
Hi,

I'm trying to use a post request to my server with ```curl --data "param1=value1&param2=value2" http://localhost:8080/dummy```, but I have no idea how to retrieve the data. I've searched all the examples, and the closest one is this [one](https://github.com/Corvusoft/restbed/blob/d190b29c72e1cd31ab6e638306631ed573cc7cb8/example/http_service/source/example.cpp), but there's no explanaition on how to get the data.

Thanks.

**Comment by ben-crowhurst** [comment]
See the post method handler in the example you mentioned above.

``` c++
size_t content_length = 0;
request->get_header( "Content-Length", content_length );
    
session->fetch( content_length, [ request ]( const shared_ptr< Session > session, const Bytes & body )
 {
    fprintf( stdout, "%.*s\n", ( int ) body.size( ), body.data( ) );
    session->close( OK, "Hello, World!", { { "Content-Length", "13" }, { "Connection", "close" } } );
} );
```

**Comment by Bl4ckb0ne** [comment]
Oops sorry, I was not reading that part.
So all of the stuff that was in the --data argument from curl is in the body.data var, got it, thanks.

**Comment by ben-crowhurst** [comment]
Not a problem.

**Comment by clrusby** [comment]
I think the code should read:

size_t content_length = request->get_header( "Content-Length", 0 );

the parameter is the default, the return from get_header is the actual value in the headers.
