### ISSUE TITLE
Windows: ordinal 341 could not be located 

### ISSUE THREAD

**Issue by callum-kirby** [Corvusoft/restbed#101]
When building 4.0 on Windows 10, Visual Studio 2015 Update 2. The following error is presented when running the test suites.

```
The ordinal 341 could not be located in the dynamic link library C:\Users\Development\Desktop\restbed\build\acceptance-tests\Release\publishing_single_path_resources_http_get_acceptance_test_suite.exe.
```

At first glance it appears to be an OpenSSL dependency issue.

**Comment by ben-crowhurst** [comment]
This will most likely be caused by the wrong version of OpenSSL loading.

Open `restbed.lib` with [dependency walker]() and confirm the location of `libeay32.dll` and `slleay32.dll`.

Resolve the issue by setting the correct search path:
```
set PATH=C:\<RESTBED LOCATION>\restbed\dependency\openssl\out32dll;%PATH%
echo %PATH%
```
