### ISSUE TITLE
Beta version of the websocket

### ISSUE THREAD

**Issue by Bl4ckb0ne** [Corvusoft/restbed#105]
Hi.

For my work I need the websocket feature of restbed. I see that it is planned for the 4.5 version, and the [issue](https://github.com/Corvusoft/restbed/issues/16) is almost 1 year old. 

Is there any beta available, any draft of the websocket? Or should I code something then do a PR?

Thanks.

**Comment by ben-crowhurst** [comment]
We're planning a refactor in 4.5 which will make it easier to implement WebSockets, HTTP2, SPDY and friends.  Please feel free to take a crack at the implementation.

```
auto request = session->get_request( );

if ( request.get_header( "connection", String::lowercase ) == "upgrade" )
{
    if ( request.get_header( "upgrade", String::lowercase ) == "websocket" )
    {
        //validate client headers.

        session->yield( SwitchingProtocols,  { response headers... }, [ ]( shared_ptr< WebSocket >& socket )
        {
            socket.on( "close", callback );
            socket.on( "error", callback );
            socket.on( "message", callback );
            socket.close( callback );
            socket.send( "", callback );
        }
    } //else...
}
```

**Comment by ben-crowhurst** [comment]
Please put any further comments on the WebSocket [ticket](https://github.com/Corvusoft/restbed/issues/16).

**Comment by ben-crowhurst** [comment]
If your organisation has paid for a commercial license, which they must before releasing any products that interact with restbed, have them contact support@corvusoft.co.uk to help prioritise the WebSocket ticket.

**Comment by Bl4ckb0ne** [comment]
We are doing softwares under the GPL license. Here's a an [example](https://github.com/sevaivanov/ring-daemon). 

I'll talk with my superiors about the license

**Comment by ben-crowhurst** [comment]
Restbed is under AGPL.

**Comment by Bl4ckb0ne** [comment]
Ok, so the legal responsible is not here today, I'll talk to her about that tomorrow.
Anyway, I'll do the implementation as a PR for the project. 

For the work I already did using restbed, the files are only on my computer, not on our [gerrit](url). And my boss assured me that the company does not relicense the dependencies, so it should be ok.

**Comment by ben-crowhurst** [comment]
Its not a problem if don't sell anything dependent on Restbed.  I was just informing you its a AGPL'd project.  Look forward to reviewing your PR.

**Comment by Bl4ckb0ne** [comment]
Bad news, the websockets are not a priority on our development. So do not count on me for the websocket PR.

But I'll try to do my best on my free time to do something.

**Comment by ben-crowhurst** [comment]
Not a problem at all.  Hopefully look forward to working with you in future, have a great day 👍

**Comment by Bl4ckb0ne** [comment]
Thanks, I'll keep an eye on the repo.

Good day to you too!
