### ISSUE TITLE
linking issue with /clr flag in Visual Studio 2015

### ISSUE THREAD

**Issue by itadakimas** [Corvusoft/restbed#107]
Hi!

When I try to compile my Visual Studio project with Restbed using the Common Language Runtime (/clr flag), I get this error:

`C1189	#error:  <future> is not supported when compiling with /clr or /clr:pure.	myconfigserver	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\future	8	
` 

How can I fix this?

You will find the source code [here](https://github.com/itadakimas/my_config/tree/feature/server/rest-api/server).

**Comment by ben-crowhurst** [comment]
What version of Visual Studio are you carrying?

**Comment by itadakimas** [comment]
VS 2015 Community Edition

**Comment by ben-crowhurst** [comment]
Update 1? 2?

**Comment by itadakimas** [comment]
I tried with update 1, then update 2. Same problem.

**Comment by ben-crowhurst** [comment]
After much debate. We've drawn the conclusion that this will not be a feature of the project without the express interest, read paid contract, from a commercial entity.

You're welcome to undertake the work yourself and submit a PR for review.
