### ISSUE TITLE
How to get request URI in handler function?

### ISSUE THREAD

**Issue by MasihAkbari** [Corvusoft/restbed#108]
Hi
I have a question about getting URI in my handler function, as my handler handle more than one resource URI i want to know what request calling the handler function.
is there any thing in session that i can use for this purpose?
thanks.

**Comment by MasihAkbari** [comment]
OK, i see that get_path() function do exactly this job. it would be great if this function added to an example like "publishing_multipath_resources" example.

**Comment by MasihAkbari** [comment]
OK i see @ben-crowhurst added label to this issue so i reopen this for feather attention. if i got any time I'll do it myself.

**Comment by ben-crowhurst** [comment]
@MasihAkbari I'm going to close this issue as documentation is on its way which will describe the available API.
