### ISSUE TITLE
Test 64 - resource_rules_engine_acceptance_test_suite (Failed) in Ubuntu Server 16.04

### ISSUE THREAD

**Issue by MasihAkbari** [Corvusoft/restbed#109]
Hi
At this time i cloned git repository completly in my fresh Ubuntu Server 16.04 and after compiling and run `make test` i got this error.
I'm compiling openssl with these command :  `./config shared` , `make all`
and then i build restbed with `cmake -DBUILD_TESTS=YES -DBUILD_EXAMPLES=YES -DBUILD_SSL=YES -DBUILD_SHARED=YES ..` and `make` , `make test`

result is : 
99% tests passed, 1 tests failed out of 104
Total Test time (real) =  15.32 sec
The following tests FAILED:
         64 - resource_rules_engine_acceptance_test_suite (Failed)
Errors while running CTest
Makefile:127: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by ben-crowhurst** [comment]
Please run the test on its own and show the results, thanks.

```
./build/acceptance-tests/resource_rules_engine_acceptance_test_suite
```

**Comment by MasihAkbari** [comment]
This is the result:
![capture](https://cloud.githubusercontent.com/assets/8469800/16062829/0da8a408-32ab-11e6-8a97-79cf9420c2ac.PNG)

**Comment by ben-crowhurst** [comment]
yikes! I've downloaded Ubuntu 16.04 and shall attempt to replicate this issue.

**Comment by ben-crowhurst** [comment]
Appears the shared_ptr< Request > is being deleted multiple times.  This may be an issue with the Catch test framework or over optimisation from the compiler.

**Comment by ben-crowhurst** [comment]
This issue resulted from the ordering of the Request class properties in which the asio::io_service was reclaimed twice during client destruction.

First the Request was destroyed, which in turn caused the SocketImpl to be reclamied. The problem being that the SocketImpl cleaned up the asio::io_service, via asio::buffer, and asio::steady_timer properties, and then the RequestImpl attempted to do the same.

An upcoming refactor will untangle all of this code.
