### ISSUE TITLE
Can't build on MSYS2

### ISSUE THREAD

**Issue by silart-teplomonitor** [Corvusoft/restbed#112]
Hello!
I try to build restbed:
cmake \
-G"MSYS Makefiles" \
-DBUILD_TESTS=no \
-DBUILD_EXAMPLES=YES \
-DBUILD_SSL=NO \
-DBUILD_SHARED=YES \
-DCMAKE_INSTALL_PREFIX=/c/Tools/restbed ..

make -j4 install

And I have a lot of errors:

> error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
>  #error This file requires compiler and library support for the \
>   ^
> [  4%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/http.cpp.obj
> [  5%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/string.cpp.obj
> In file included from C:/build/restbed/source/corvusoft/restbed/rule.cpp:8:0:
> C:/build/restbed/source/corvusoft/restbed/rule.hpp:42:48: error: 'shared_ptr' in namespace 'std' does not name a template type
>              virtual bool condition( const std::shared_ptr< Session > session );
>                                                 ^
> C:/build/restbed/source/corvusoft/restbed/rule.hpp:42:58: error: expected ',' or '...' before '<' token
>              virtual bool condition( const std::shared_ptr< Session > session );
>                                                           ^
> C:/build/restbed/source/corvusoft/restbed/rule.hpp:44:45: error: 'shared_ptr' in namespace 'std' does not name a template type
>              virtual void action( const std::shared_ptr< Session > session, const std::function< void ( const std::shared_ptr< Session > ) >& callback ) = 0;
>                                              ^
> C:/build/restbed/source/corvusoft/restbed/rule.hpp:44:55: error: expected ',' or '...' before '<' token
>              virtual void action( const std::shared_ptr< Session > session, const std::function< void ( const std::shared_ptr< Session > ) >& callback ) = 0;

...
My toolchain: gcc 4.9.3

**What am I doing wrong?**

**Comment by ben-crowhurst** [comment]
>  requires compiler and library support for the ISO C++ 2011 standard.

**Comment by silart-teplomonitor** [comment]
Toolchain gcc 4.9.3 is support C++11. How can I pass -std=gnu++11 in your build script for activation this option?

**Comment by ben-crowhurst** [comment]
The GCC toolchain is already supplied with the appropriate switch: https://github.com/Corvusoft/restbed/blob/master/cmake/build_configuration.cmake#L50

**Comment by ben-crowhurst** [comment]
Ah! This clause will cause it to fail: https://github.com/Corvusoft/restbed/blob/master/cmake/build_configuration.cmake#L45

**Comment by ben-crowhurst** [comment]
I'll look to have this issue resolved sometime this week.

**Comment by ben-crowhurst** [comment]
@silart-teplomonitor I'm currently out of reach of a Windows machine to replicate your setup.  Would you be willing to submit a [Pull Request](https://yangsu.github.io/pull-request-tutorial/)?

**Comment by silart-teplomonitor** [comment]
I make pull request
