### ISSUE TITLE
Build with OpenSSL

### ISSUE THREAD

**Issue by silart-teplomonitor** [Corvusoft/restbed#115]
When I execute cmake command with option BUILD_SSL=YES:
cmake \
-G"MSYS Makefiles" \
-DCMAKE_BUILD_TYPE=Debug \
-DCMAKE_C_COMPILER=i686-w64-mingw32-gcc \
-DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++ \
-DBUILD_TESTS=no \
-DBUILD_EXAMPLES=YES \
-DBUILD_SSL=YES \
-DBUILD_SHARED=YES \
-DCMAKE_INSTALL_PREFIX=/c/Tools/restbed ..

cmake error occurred:  Failed to locate OpenSSL dependency.  see restbed/dependency/openssl;
What am I doing wrong? In restbed/dependency/openssl folder there are many files.

**Comment by ben-crowhurst** [comment]
The build script is failing to find the OpenSSL dependency. 

```
cd restbed/dependency/openssl
./config; make shared
```
