### ISSUE TITLE
Error handler isn't work

### ISSUE THREAD

**Issue by silart-teplomonitor** [Corvusoft/restbed#117]
I tried to use your example "error_handling" and saw one thing. When exception thrown in method handler, i. e. in faulty_method_handler(), error handlers resource_error_handler() and service_error_handler() weren't execute. What did i do wrong? I used only example code.

**Comment by ben-crowhurst** [comment]
Please provider your client request.

**Comment by silart-teplomonitor** [comment]
I used Internet explorer. URI was: http://localhost:1984/resources/1 and http://localhost:1984/resources/2.
I run example under gdb and installed breakpoints in handlers. I caught GET request event and I didn' catch error events in appropriate handlers.

**Comment by silart-teplomonitor** [comment]
After calling method faulty_method_handler(), exception thrown. This exception didn't catch therefore process crashed.

**Comment by ben-crowhurst** [comment]
I shall do my best to resolve this issue shortly.

**Comment by ben-crowhurst** [comment]
I'd love to act surprised, however this appears to be a very Windows specific issue.   Feature is working on Mac OSX, FreeBSD, and Linux.

**Service Error Handler**

```
developer$ curl -w'\n' -v -XGET 'http://localhost:1984/resources/1'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 1984 (#0)
GET /resources/1 HTTP/1.1
User-Agent: curl/7.35.0
Host: localhost:1984
Accept: */*

< HTTP/1.1 5000 No Appropriate Status Message Found
< Connection: close
< Content-Length: 36
< 
* Closing connection 0
Custom Service Internal Server Error
```

**Resource Error Handler**
```
developer$ curl -w'\n' -v -XGET 'http://localhost:1984/resources/2'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 1984 (#0)
> GET /resources/2 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:1984
> Accept: */*
> 
< HTTP/1.1 6000 No Appropriate Status Message Found
< Connection: close
< Content-Length: 37
< 
* Closing connection 0
Custom Resource Internal Server Error
```

Will attempt to replicate your symptoms this afternoon.

**Comment by silart-teplomonitor** [comment]
I solved this problem. I included Restbed library in my project as static library. If you want to get shared build (with dependencies) you need link libgcc as shared, i. e, need link with -lgcc_s library (instead -lgcc). If you link with -lgcc for shared build, your exceptions will not pass across different shared libraries and will not be caught.
http://www.cplusplus.com/forum/general/153878

If you want to have a static build (without dependencies), you need pass options "-static -static-libgcc -static-libstdc++" to linker and link with -lgcc -lstdc++ libraries.

All cases works is fine.

**Comment by ben-crowhurst** [comment]
Great catch! no pun intended.  Thank you for feed your results back to the community.
