### ISSUE TITLE
example can't handle lots of requests

### ISSUE THREAD

**Issue by mcheung63** [Corvusoft/restbed#121]
example can't handle lots of requests, i use jmeter (100 threas x 2000 request per thread), some of them failed. How to make sure all requests succcess return?

**Comment by ben-crowhurst** [comment]
Please present the example and jmeter configuration.

**Comment by ben-crowhurst** [comment]
Any further details available?

**Comment by lhammond** [comment]
+1

**Comment by mcheung63** [comment]
I am so sorry, my jmeter has memory lack, this is not related to restbed and restbed is perfect.
