### ISSUE TITLE
How to Extract Http GET request parameters

### ISSUE THREAD

**Issue by MasihAkbari** [Corvusoft/restbed#122]
Hi
I have a question that might sounds a little silly but i can't figure out how can i  extract http get request keys and values. for example i want to send this request:
http://xxx.xxx.xxx.xxx/myaction?id=5?res=2
how can i get "id" and "res" values in my get method handler?
thanks.

**Comment by ben-crowhurst** [comment]
See Request:: get_query_parameter and Request::has_query_parameter methods.
