### ISSUE TITLE
Session::set_header() should be called Session::add_header()

### ISSUE THREAD

**Issue by ignitenet-martynas** [Corvusoft/restbed#123]
The name of Session::set_header() kind of implies that it overwrites any existing headers with the same name which is a problem when persistent connections and Session::yield() are used: it results in identically-named headers "accumulating" in the Session object and getting passed back to the client.

I feel that Session::set_header() should be renamed to Session::add_header() because that's what it does effectively. And Session::set_header() could be reimplemented so that it actually overwrites any existing header(s) with the same name.

I don't think this should be a real backwards compatibility problem as the symptoms are only noticeable with persistent connections and I doubt that there's a lot of software that uses Restbed and relies on current behavior of set_header().

Otherwise the behavior should be clearly documented, but then I feel that the best documentation is self-documenting code and hence intuitively named methods.

**Comment by ben-crowhurst** [comment]
Agreed.  Are you willing to submit a PR with the necessary changes?

This behaviour would also be required on Request and Response classes to maintain a consistent look and feel?

Documentation is in development. However, as you stated self-documenting code is of a greater important.

**Comment by ben-crowhurst** [comment]
I shall make the necassary changes to the upcoming WebSocketMessage class.

**Comment by ignitenet-martynas** [comment]
I'll submit a PR in a day or two, thanks!

**Comment by ignitenet-martynas** [comment]
Apologies, I got held up. I'll submit the PR tomorrow, August 8

**Comment by ben-crowhurst** [comment]
Not all, take your time. Version 4.5 won't be released for the next couple of months.

**Comment by ignitenet-martynas** [comment]
Sorry, I made a mess here. Still new to Git. The latest pull request is the right one.
