### ISSUE TITLE
make failed!

### ISSUE THREAD

**Issue by sunglowfavor** [Corvusoft/restbed#124]
/home/restbed-4.0/source/corvusoft/restbed/http.cpp:269:108: note: candidate is:
In file included from /home/restbed-4.0/source/corvusoft/restbed/http.cpp:22:0:
/home/restbed-4.0/source/corvusoft/restbed/detail/socket_impl.hpp:70:24: note: size_t restbed::detail::SocketImpl::read(int)
                 size_t read( const std::shared_ptr< asio::streambuf >& data, const std::size_t length, std::error_code& error );
                        ^
/home/restbed-4.0/source/corvusoft/restbed/detail/socket_impl.hpp:70:24: note:   candidate expects 1 argument, 3 provided
/home/restbed-4.0/source/corvusoft/restbed/http.cpp:276:31: error: ‘asio’ has not been declared
         const auto data_ptr = asio::buffer_cast< const Byte* >( request->m_pimpl->m_buffer->data( ) );
                               ^
/home/restbed-4.0/source/corvusoft/restbed/http.cpp:276:50: error: expected primary-expression before ‘const’
         const auto data_ptr = asio::buffer_cast< const Byte* >( request->m_pimpl->m_buffer->data( ) );
                                                  ^
/home/restbed-4.0/source/corvusoft/restbed/http.cpp:278:35: error: base operand of ‘->’ is not a pointer
         request->m_pimpl->m_buffer->consume( size );
                                   ^
make[2]: *** [CMakeFiles/restbed.dir/source/corvusoft/restbed/request.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/restbed.dir/source/corvusoft/restbed/http.cpp.o] Error 1
make[1]: *** [CMakeFiles/restbed.dir/all] Error 2
make: *** [all] Error 2

**Comment by ben-crowhurst** [comment]
Any update on this situation?

**Comment by sunglowfavor** [comment]
Download the master branch to build then failed ,Then using thy way that git clone --recursive https://github.com/corvusoft/restbed.git  ,problem solved, thanks!
By the way  I am a student in China and
my English is not very good...

**Comment by ben-crowhurst** [comment]
Great to hear!  Don't stop to ask any further questions if you need help.

Your english is very good.
