### ISSUE TITLE
restbed::Settings::set_root() seems to break restbed::Request::get_path_parameter() 

### ISSUE THREAD

**Issue by nickjhathaway** [Corvusoft/restbed#131]
If I modify the example code from [servering_html,](https://github.com/Corvusoft/restbed/blob/4.0/example/serving_html/source/example.cpp) and add 
```cpp
settings->set_root("/ssv/");
```
and run the compiled example when I go to http://localhost:1984/ssv/static/index.html, `request->get_path_parameter("filename")` now returns **"static"** rather than **"index.html"**, and if were to add another parameter in the resource object like so 

```cpp
resource->set_path("/static/{number: [0-9]+}/{filename: [a-z]*\\.html}");
```
and run and go to http://localhost:1984/ssv/static/10/index.html, `request->get_path_parameter("number")` returns **"static"** and `request->get_path_parameter("filename")` returns **"10"**  so everything seems to be off by one.  So I'm wondering if I'm suppose to be doing something differently with setting paths and getting path parameters when setting a root as well, if I'm doing something wrong, or if setting a root isn't currently supported.  

Thanks for any help and advice!

**Comment by ben-crowhurst** [comment]
Looks to me like a bug Nick.  I'll attempt to replicate and resolve this issue today.

**Comment by ben-crowhurst** [comment]
The root path was not being taken into consideration during path parameter extraction.

When setting up the path endpoint within the service the root path is prepended. however, it fails to alter the path parameter declaration which is used for comparing incoming paths and those of resource routes.

The addition of new features, over time, has lead to system elements that have organically evolved into less than desirable outcomes.

I've created an additional issue highlighting the need to refactor the service code, see #132.

**Comment by nickjhathaway** [comment]
Yeah I tracked down if you change, https://github.com/Corvusoft/restbed/blob/4.0/source/corvusoft/restbed/detail/service_impl.cpp#L553, from 
```cpp
const auto declarations = String::split( m_resource_paths.at( sanitised_path ), '/' );
```
to 
```cpp
const auto declarations = String::split(m_settings->get_root( ) + "/" +  m_resource_paths.at( sanitised_path ), '/' );
```
it would fix this case but not sure if m_resource_paths is also checked in other locations and needs to be modified to include the root always anyways for other possible cases.  

Do you know if there is an estimated time for release of milestone 4.5?  I was thinking of porting over from another http service manager to restbed but like the ability to set root.  
 
Thanks!

**Comment by nickjhathaway** [comment]
Also hate to be a bother, but I noticed with the change in your commit, https://github.com/Corvusoft/restbed/commit/cb9bb7ad585af6f020260f85d6882dffbf3f99cf, that there is another corner case where if someone sets a root name with more than one slash in it the indexing will get off again for example if someone did, 
```cpp
settings->set_root("/ssv/other/");
```
Then your fix will only erase **ssv** but not **other**, now I can't really think of scenario where someone would do this but I thought I would point it out as another pitfall, the change I suggest above would handle this corner case as well 
```cpp
const auto declarations = String::split(m_settings->get_root( ) + "/" +  m_resource_paths.at( sanitised_path ), '/' );
```
and would stay consistent with how things are being checked here, https://github.com/Corvusoft/restbed/blob/4.0/source/corvusoft/restbed/detail/service_impl.cpp#L621 

but just a suggestion

-Nick

**Comment by ben-crowhurst** [comment]
Nick agree completely. I quickly rushed a fix prior to other engagements, apologies.

I shall make you suggested fix this afternoon (NZT). 

4.5 is scheduled this this year..

**Comment by nickjhathaway** [comment]
Awesome, thanks!

**Comment by ben-crowhurst** [comment]
Nick your changes have been applied and tested.

4.5 should be out in the next few months, we're currently working on getting the WebSocket implementation product ready.

**Comment by ben-crowhurst** [comment]
If you have any further issues don't hesitate to raise more issues; and more and more...

**Comment by nickjhathaway** [comment]
Thanks! and will do, thanks for the speedy response!
