### ISSUE TITLE
Some system errors occured on Windows (MinGW, MSYS2)

### ISSUE THREAD

**Issue by silart-teplomonitor** [Corvusoft/restbed#133]
Modified example **serving_html** for problem demonstration.
```c++
int main( const int, const char** )
{
	Service service;

	auto res = std::make_shared< Resource >( );
	res->set_path("/images/{filename: .*}");
	res->set_method_handler("GET", [](const std::shared_ptr<restbed::Session > session)
	{
		const auto request = session->get_request( );
		const string filename = request->get_path_parameter( "filename" );

		ifstream stream(filename, ios::in | ios::binary);
		if ( stream.is_open( ) )
		{
			const string body = string( istreambuf_iterator< char >( stream ), istreambuf_iterator< char >( ) );
			const multimap< string, string > headers
			{
				{ "Content-Type", "image/jpeg" },
				{ "Content-Length", ::to_string( body.length( ) ) }
			};

			session->close( OK, body, headers );
		}
		else
		{
			session->close( NOT_FOUND );
		}
	});
	service.publish(res);
    
	res = std::make_shared<Resource>( );
	res->set_path("/");
	res->set_method_handler("GET", [](const std::shared_ptr<restbed::Session > session)
	{
		ifstream stream("index.html", ifstream::in);
		if ( stream.is_open( ) )
		{
			const string body = string( istreambuf_iterator< char >( stream ), istreambuf_iterator< char >( ) );
			const multimap< string, string > headers
			{
				{ "Content-Type", "text/html" },
				{ "Content-Length", ::to_string( body.length( ) ) }
			};

			session->close( OK, body, headers );
		}
		else
		{
			session->close( NOT_FOUND );
		}
	});
	service.publish(res);

	auto settings = make_shared< Settings >( );
	settings->set_port( 80 );
	settings->set_worker_limit(4);
	settings->set_default_header( "Connection", "close" );
	service.start( settings );
	return EXIT_SUCCESS;
}
```
Server has a simple web-page published as "/" and some large images published as "/images/*.jpg":

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Corvusoft - Restbed</title>
</head>
<body>
	<p>
		Hello, World!
	</p>
	<p><img src="/images/1.jpg" alt="1"></p>
	<p><img src="/images/2.jpg" alt="2"></p>
	<p><img src="/images/3.jpg" alt="3"></p>
	<p><img src="/images/4.jpg" alt="4"></p>
	<p><img src="/images/5.jpg" alt="5"></p>
</body>
</html>
```
For the appearance of a problem you need:

1. Execute server under debugger and install breakpoints in throws. I use "break __cxa_throw" on GDB.

1. Start Web Browser and put http://localhost/ into url field.

1. Wait 5-10 second.

Server will throw exception in ServiceImpl::parse_request() function (service_impl.cpp:713), in nested call SocketImpl::read() function (socket_impl.cpp:346). This exception will be caught and some text will be written in log. Exception threw after load web-page in browser i. e. after send response to client. Exception will be thrown when async_read_until() function error returned. _Why did function async_read_until() call? Browser doesn't send next request._ 

If you update your browser, server will throw exception again after 5-10 seconds.
Thrown exception has an error codes: **ERROR_CONNECTION_ABORTED**(1236) and **ERROR_FILE_NOT_FOUND**(2).

[Windows Error Codes](https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms681381(v=vs.85).aspx) 

Problem is not always, but often enough. If you publish one resource only, problem will be rarely.
I use:
- I use Windows 7 Ultimate (32 bit) in VirtualBox;
- Latest Restbed, your master branch;
- Asio 1.11.0;
- Firefox 48.0.1, Chrome 52.0.2743.116 m, Internet Explorer 11;

Have you any ideas?

**Comment by ben-crowhurst** [comment]
I'll spend sometime investigating this issue tomorrow. 

ERROR_CONNECTION_ABORTED:  What setting do you have for  Settings::set_connection_timeout?
ERROR_FILE_NOT_FOUND: Is it attempting to find a favicon?

**Comment by silart-teplomonitor** [comment]
I have a default value for timeout connection, not call  Settings::set_connection_timeout().
No, exception threw after web-page loading. Web-page haven't favicon.
If you want, I can share this project in bitbucket.org for you. You would need install Windows, MSYS2, MinGW and clone my project. It project contains Restbed as module, only headers modified. Restbed module was updated today as your master branch.

**Comment by ben-crowhurst** [comment]
Browsers will still ask for a favicon regardless if you have one in your project or not.  The default connection timeout is 5 seconds I believe.  Your browser will most likely have sent a 'Connection: keep-alive' header, are you processing this correctly?

Feel free to share your code base.

**Comment by silart-teplomonitor** [comment]
My project: [link](https://bitbucket.org/silart/webrestbed)
For build need:
- MSYS2 [this](https://msys2.github.io)
- MinGW

Debug build:
- make PLATFORM="win32" BUILD="debug" ASIO_DIR=/c/Tools/asio-1.11.0 JOBS=4 all

Release build:
- make PLATFORM="win32" BUILD="release" ASIO_DIR=/c/Tools/asio-1.11.0 JOBS=4 all

**Comment by silart-teplomonitor** [comment]
Branch: abortProblem

**Comment by silart-teplomonitor** [comment]
I have these headers:
**Request** URL:http://localhost/images/2.jpg
Request Method:GET
Status Code:200 OK
Remote Address:[::1]:80
**Response Headers:**
Connection:close
Content-Length:322343
Content-Type:image/jpeg
**Request Headers:**
Accept:image/webp,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
Cache-Control:max-age=0
Connection:keep-alive
Host:localhost
Referer:http://localhost/
User-Agent:Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by silart-teplomonitor** [comment]
When I use development tools in Google Chrome, I saw resources which browser get. It is published resources only. I not see that browser request favicon resource.
![chrome](https://cloud.githubusercontent.com/assets/8257962/17896295/4b1b3d9a-697a-11e6-9877-e57a8b9fd729.png)

**Comment by silart-teplomonitor** [comment]
For my test project I use MinGW toolchain: [here](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.3/threads-posix/dwarf/i686-4.9.3-release-posix-dwarf-rt_v4-rev1.7z/download)

If you have other toolchain, you need modify TARGET variable in project/platforms/win32/trait.mk for correct build.

**Comment by ben-crowhurst** [comment]
Thanks for the additional data.  I'll attempt to have a look at this today.

**Comment by ben-crowhurst** [comment]
Sorry for the delay.  I will have some feedback the next couple of days.

**Comment by silart-teplomonitor** [comment]
I deployed my project WebRestbed on Linux Mint and I have never it problem. I did use Firefox only.

**Comment by ben-crowhurst** [comment]
Not yet had a chance to created an environment to replicate your issue, however my feeling was it was a MinGW specific issue.

Good to hear you have moved to a more professional environment.

**Comment by ben-crowhurst** [comment]
Given this issue is not a native windows defect.  Can you submit a PR resolving the issue and/or close the ticket.

**Comment by silart-teplomonitor** [comment]
What should I do? Please explain.

**Comment by ben-crowhurst** [comment]
We're unwilling to fix this issue as it is not a native platform issue.  If you'd like to correct the issue yourself and submit a Pull Request we'd happily apply the patch.
