### ISSUE TITLE
fail to install openssl, help me

### ISSUE THREAD

**Issue by wujiangyun** [Corvusoft/restbed#134]
My environment: win7, 64bit, vs2013 

When i compile OPENSSL for x64 as the INSTALL.W64 file. i was prompted an error:

ms\uplink.c(11) : fatal error C1083: Can't open file “windows.h”: No such fi
le or directory
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio 12.
0\VC\bin\cl.EXE"”: return code “0x2”
Stop.

Can any body help me to solve this?

**Comment by ben-crowhurst** [comment]
Have you followed the instructions outlined in issue #17
