### ISSUE TITLE
Building with Clang on Ubuntu

### ISSUE THREAD

**Issue by nickjhathaway** [Corvusoft/restbed#135]
Hi,
I ran into some trouble when trying to build restbed on Ubuntu 14.04 with clang++-3.8 and I figured out it's because in the cmake file cmake/build_configuration.cmake in tag 4.0 which is now cmake/configuration.cmake in master, there is a check on line 34 for clang that automatically adds the compile flag "-stdlib=libc++" but using clang doesn't always mean libc++ will be used and this especially true of ubuntu where apt-get install clang-3.8 doesn't even install libc++ and clang uses libstdc++ by default.  

So the build fails on Ubuntu since libc++ can't be found, I tried to solve the issue by adding "-stdlib=libstdc++" to environmental CXXFLAGS but since "-stdlib=libc++" is added after environmental CXXFLAGS, "-stdlib=libc++" is honored and not "-stdlib=libstdc++".  

So it would be great if either just the default compiler library that is clang is set up to use is allowed (which would be done by just removing the addition of -stdlib=libc++ on line 34) or if the order on line 34 could be reversed so it would be 
```
set( CMAKE_CXX_FLAGS "-stdlib=libc++ ${CMAKE_CXX_FLAGS}" )
```
instead to make it easier to support clang that is using libstdc++ 

Thanks!
Nick

**Comment by ben-crowhurst** [comment]
Thanks Nick, Will take a look and action shortly.

**Comment by ben-crowhurst** [comment]
Nick, I've opted to remove ```-stdlib=libc++``` altogether.   When we first started developing Restbed C++11 support was not as broad as is it today.

I love deleting code/config, less is more :feelsgood:

**Comment by nickjhathaway** [comment]
excellent, thanks!
