### ISSUE TITLE
Build Errors on Raspbian Jessie

### ISSUE THREAD

**Issue by elkvis** [Corvusoft/restbed#136]
I'm trying to build on Raspbian Jessie, on my RPi3, and I'm getting the error asio/io_service_strand.hpp: no such file...

Is there a specific version of asio that is required?  I'm using version 1.10.6 from the raspbian stretch repository.

**Comment by ben-crowhurst** [comment]
Restbed has been primarily tested with 722f7e2. This can be found at http://github.com/corvusoft/asio-dependency.  I strongly suggest you follow the build instructions outlined in the README.md

Please note ASIO will be updated very shortly (next couple of days) to include the latest OpenSSL 1.1 supported version.

**Comment by elkvis** [comment]
I did a little more investigation, and it seems that the asio package on Raspbian Jessie is somehow missing  that header file altogether.  I don't know  how they overlooked it, but it's clearly missing.

I think this issue can be closed.  I'll make my complaint with the maintainers of the Stretch repository for Raspbian.

**Comment by ben-crowhurst** [comment]
Thanks for letting us know.  If you require anymore help please do raise another ticket.

**Comment by aberaud** [comment]
@elkvis You need the asio master branch to build (version 1.11). Asio "stable" branch (1.10) doesn't include this file.
Asio examples don't build with latest libstdc++ but the library itself (header-only) works fine.

**Comment by aviau** [comment]
Would it be possible to have restbed build with 1.10?

**Comment by ben-crowhurst** [comment]
ASIO 1.10?

**Comment by aviau** [comment]
Yes.

ASIO 1.11 is not yet available in Debian due to it being the dev branch. I'd love to be able to build restbed with ASIO 1.10.

Currently, Debian has restbed 4.0 and cannot upgrade because of this.

It could take a very long time for asio 1.11 to make it to the stable branch.

**Comment by ben-crowhurst** [comment]
If you supply a PR with the necessary changes we will be more than happy to take a look.
