### ISSUE TITLE
Add pkg-config file

### ISSUE THREAD

**Issue by aberaud** [Corvusoft/restbed#138]
On UNIX systems, a pkg-config file would help to integrate restbed in other programs.

**Comment by ben-crowhurst** [comment]
Is pkg-config functionality not very similar to cmake find modules?  Whats the benefit of having both entities?

**Comment by aberaud** [comment]
Hi,
pkg-config files are more common and are compatible with both cmake and autotools : CMake will find them with _find_package_ and Autotools with _PKG_CHECK_MODULES_. 

Providing a pkg-config file allows all kind of libraries to use restbed seamlessly.
Also the design of pkg-config files is usually very simple, much simpler than cmake find modules: it's just a standard list of paths and build flags.
