### ISSUE TITLE
Build issues with 4.0

### ISSUE THREAD

**Issue by szotsaki** [Corvusoft/restbed#140]
Upon building the latest version (4.0) for openSUSE, I noticed some build issues which prevent a successful package creation:
- librestbed.so has no proper .so name (the very same issue is here: https://github.com/savoirfairelinux/opendht/issues/75 )
- librestbed.so goes into `/usr/library/` instead of `/usr/lib` or `/usr/lib64`.
- building examples creates `/usr/example/` and `/usr/resource` paths. Probably you don't want them to be that global.

**Comment by ben-crowhurst** [comment]
@szotsaki would you be will to submit a PR with the desired changes?

The output path can be specified via```-DCMAKE_INSTALL_PREFIX=/output-directory```. However the default path will remain the repository folder in which the project was checked out.

**Comment by ben-crowhurst** [comment]
Please keep in mind, any PR need to be cross compatible with environments other than *nix.
