### ISSUE TITLE
Empty request in response causing an exception.

### ISSUE THREAD

**Issue by IOBYTE** [Corvusoft/restbed#142]
I'm getting an exception in the following code which is a modified http_client example.   Attempting to fetch the body of the response causes the exception because the request in the response is empty.  I assumed the future returned from async would keep the request around for the life of the future.
```
future<shared_ptr<Response>> make_request( )
{
    auto request = make_shared< Request >( Uri( "http://www.corvusoft.co.uk:80/?query=search%20term" ) );
    request->set_header( "Accept", "*/*" );
    request->set_header( "Host", "www.corvusoft.co.uk" );

    return Http::async( request, nullptr );
}

int main( const int, const char** )
{
    auto future = make_request( );

    auto response = future.get( );

    fprintf( stderr, "Printing async response\n" );
    print( response );

    return EXIT_SUCCESS;
}
```

**Comment by ben-crowhurst** [comment]
The response has no public request available in HEAD.  I would suggest moving to HEAD.

Solution you stated in #141 will of course resolve your issue.
