### ISSUE TITLE
Problems on systems without atomic support

### ISSUE THREAD

**Issue by Lawei** [Corvusoft/restbed#144]
I ran into a problem when trying to compile restbed for ARMv5 architecture, as it does not support atomics (_ATOMIC_INT_LOCK_FREE = 1_, look [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64735)). 
This leads to a libstdc++ which does not support _std::future_, _std::current_exception_ and _std::rethrow_exception_.

As i don't need client functionality, i created a workaround by just disabling all that atomic stuff with a check for _ATOMIC_INT_LOCK_FREE_ in preprocessor ([patch for restbed-4.0](https://github.com/Corvusoft/restbed/files/476310/restbed-4.0_noatomic.patch.zip)). Do you have any other way around this?

**Comment by ben-crowhurst** [comment]
I'm afraid I don't have a better work around for this issue, ARMv7 is obviously the best option but not a very helpful comment.

Thank you for the patch.
