### ISSUE TITLE
http service access

### ISSUE THREAD

**Issue by PradeepChoudhari** [Corvusoft/restbed#146]
Hi,  
This is not an issue, it's query, as twitter handle and support@courvusoft.co.uk replied me to post it on github 'https://github.com/Corvusoft/restbed/issues/new' so posting here.

I am exploring Restbed and want to deploy on Linux system, I have few below query.

1. Does 'restbed' has its own http server or to access restbed remotely I have to use other HTTP server.
2. If 'restbed' has its own http server then how should be my setup to send http request remotely (from other machine) to restbed.
3. If I have to use other HTTP server then which http server is best to use with 'restbed'. 
4. If I have to use other HTTP server then how should be my setup to send http request remotely (from other machine) to restbed.

**Comment by ben-crowhurst** [comment]
To create a service see this [example](https://github.com/Corvusoft/restbed/blob/master/example/http_service/source/example.cpp).

To create a client to interact with a service see this [example](https://github.com/Corvusoft/restbed/blob/master/example/http_client/source/example.cpp).

You'll find all the code examples [here](https://github.com/Corvusoft/restbed/tree/master/example).
