### ISSUE TITLE
Client side server sent events.

### ISSUE THREAD

**Issue by IOBYTE** [Corvusoft/restbed#147]
I have implemented server side events using chunked transfer encoding in my server and I' trying to test it in a client app.  I can't figure out how to keep the connection open and read from it after the initial response is received.  Is this possible without modifying restbed?

**Comment by ben-crowhurst** [comment]
Please present a code example.

**Comment by ben-crowhurst** [comment]
Are you talking about Transfer-Encoding on the clientside?  If so see #118

**Comment by IOBYTE** [comment]
Yes but for client receiving.  #118 is about client sending.

**Comment by IOBYTE** [comment]
I think I need something like Http::yield to do partial reads.

**Comment by ben-crowhurst** [comment]
Duplicate #118
