### ISSUE TITLE
Not able to send the content of the File as a data through the Curl command

### ISSUE THREAD

**Issue by keshav2529** [Corvusoft/restbed#149]
Hi,

I am trying to use the example of transfer_encoding_request which is available at restbed/example/transfer_encoding_request/

The transfer_encoding_request has two sub directories
1. resource (where the resource file is available)
2. source (where the source code is available)

As suggested in the souce_code (example.cpp) i have used the below curl command to send the file as a resouce to the server.
curl -w'\n' -v -X POST --header "Transfer-Encoding: chunked" -d @distribution/resource/request.txt 'http://localhost:1984/resources'

Then i got the below warning

Warning: Couldn't read data from file "distribution/resource/request.txt", 
Warning: this makes an empty POST.
![image](https://cloud.githubusercontent.com/assets/22657460/19149573/260e7246-8be0-11e6-9b29-323a05ffa33d.png)

As result the body content which i received in the server is nothing(empty) please see the same in the below screen shot
![image](https://cloud.githubusercontent.com/assets/22657460/19149539/ef1c6bf8-8bdf-11e6-8de4-fb206646ce11.png)

Hence i have removed the symbol "@" which is there in curl command and then tried, this time i got the complete body content as "distribution/resource/request.txt"
please see the same in the  screenshots which i have placed in the attached file
[Screenshots.docx](https://github.com/Corvusoft/restbed/files/513517/Screenshots.docx)

![image](https://cloud.githubusercontent.com/assets/22657460/19149620/5d70c59a-8be0-11e6-81c1-ad2d2fa85d0f.png)

Please suggest the curl command with which we can send the entire file as a data.

**Comment by ben-crowhurst** [comment]
Just tested this example and everything appear to be working correctly.  Can you provide anymore detail behind curls "Warning: couldn't read data..." output.

**Comment by keshav2529** [comment]
Hi,

What is meant by @distribution in the Curl command, i haven't find anything related to it in the source code.

By the way i have created the distribution directory in my home folder, under the distribution directory i have created two sub directories (resource and example) where the resource contains the resource.txt and the example directory has example.cpp.
I created the executable for example.cpp in example directory and then started there to execute it.

Then from the home directory i have issued the below curl command to send the resource.txt file as data to the executable of example.cpp, with which the executable is not able to get the content of the file as the message content.
curl -w'\n' -v -X POST --header "Transfer-Encoding: chunked" -d @distribution/resource/request.txt 'http://localhost:1984/resources'

It looks like something i have missed out related to the word @distribution which is there in the curl command with which i am getting the empty body at the post_method_handler().

**Comment by ben-crowhurst** [comment]
When you perform a `make install` a directory is created restbed/distribution.

**Comment by ben-crowhurst** [comment]
Have you managed to follow the installation instructions within the README.md?

**Comment by keshav2529** [comment]
It is working fine, thanks for your help ben-crowhurst
