### ISSUE TITLE
New Restbed release

### ISSUE THREAD

**Issue by aberaud** [Corvusoft/restbed#150]
Hi,
We use Restbed as a C++ REST client in our project.
It turned out that the Restbed API changed significantly since the last official release, the most important breaking change for us being `restbed::Response::get_header ` returning the size instead of modifying the parameter.
In parallel, we also make a packaging effort to get Restbed in the next Debian release, however getting the old API would be an issue for us.
I don't know the state of the current codebase, but do you think it would be possible to make a new release soon, so it could be the first version to be in Debian ?
Thanks

**Comment by ben-crowhurst** [comment]
We're just completing the WebSocket implementation and Documentation. At which point we could be persuaded to bump a release out.

How soon is soon?

**Comment by ben-crowhurst** [comment]
4.5 will be available no later than December 31st 2016.

**Comment by aberaud** [comment]
Cool thanks

**Comment by zorun** [comment]
I see that the 4.5 milestone has been closed 22 days ago, should we expect the 4.5 release soon?

**Comment by ben-crowhurst** [comment]
Correct, we've failed to place an appropriate tag.  I shall rectify this situation shortly.
