### ISSUE TITLE
Visual Studio 2015 cannot run/compile http_service example

### ISSUE THREAD

**Issue by cjustas** [Corvusoft/restbed#155]
Cannot compile out of box http_service example.

VS version: 
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3

http_service\source\example.cpp(37): error C2440: 'initializing': cannot convert from 'std::string' to 'std::size_t'
http_service\source\example.cpp(37): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
`size_t content_length = request->get_header("Content-Length", 0);

Thank you!`

**Comment by ben-crowhurst** [comment]
Please pull from HEAD.
