### ISSUE TITLE
GCC version < 4.9

### ISSUE THREAD

**Issue by wujiangyun** [Corvusoft/restbed#156]
My gcc version: 4.8.5, OS: CentOS7
When i excute the cmake:
cmake [-DBUILD_TESTS=YES] [-DBUILD_EXAMPLES=YES] [-DBUILD_SSL=NO] [-DBUILD_SHARED=YES] [-DCMAKE_INSTALL_PREFIX=/output-directory] ..
I was reported:
  GCC version < 4.9
 Your system default compiler is GCC. The  project makes use of c+11 features presend only in versions of gcc >= 4.9.

Does the gcc4.8.5 not support c++11 features?

**Comment by ben-crowhurst** [comment]
Please upgrade your complier to a C++11 compliant edition.
