### ISSUE TITLE
Efficient asynchronous design

### ISSUE THREAD

**Issue by lynnard** [Corvusoft/restbed#157]
We're using restbed to construct a http server to serve chunk-encoded responses (keep-alive connections that stream data); and an immediate effect we run into is that the total number of these 'streaming' clients is limited by the number of worker threads.

In order to support a reasonable amount of users + keep the server responsive, we would have to crank up the worker thread number (to thousands or more?); but my understanding is that each thread here is an OS thread that can be potentially expensive - on top of that, the total number of threads is limited by `threads-max` on linux.

The same problem probably applies to websocket connections too - so I'm wondering if there's already any thought on this? Potentially a better design would be efficient coroutines multiplexed on top of threads: like what golang has, but not sure if there is any equivalent in c++?

**Comment by ben-crowhurst** [comment]
You should absolutely not be limited by the number of threads.

Please present a code example detailing your implementation.

**Comment by lynnard** [comment]
Maybe there is a misunderstanding here on my part - but if it's not limited by the number of worker threads, how does it actually work? I mean, if the request handler doesn't return and keeps running - how does the thread running that handler somehow switches out to do some other work?

**Comment by ben-crowhurst** [comment]
Session::yield registers an asynchronous callback allowing the thread to proceed to alternative work.  

Have a look into ASIO and it's runloop.

**Comment by lynnard** [comment]
OK, seems like our code was not using that optional callback argument - thus the blocking on threads. (I didn't realize yield takes a callback arg). Thanks for the clarification.

Just a side note: I notice that most functions in the header files don't have any comments or documentation, do you keep doc in a different place or there is just not enough doc at the moment?

**Comment by ben-crowhurst** [comment]
Documentation is in the works and will be available before close of 2016.  We're currently completing the WebSocket implementation.
