### ISSUE TITLE
Pass shared_ptr by reference is more efficient

### ISSUE THREAD

**Issue by lynnard** [Corvusoft/restbed#161]
I see many callback api code like this:

```
void yield( const Bytes& data, const std::function< void ( const std::shared_ptr< Session > ) >& callback = nullptr );
```

Is there any reason why we can't use

```
const std::function< void ( const std::shared_ptr< Session >& ) >&
```

as callback instead?

**Comment by ben-crowhurst** [comment]
Passing by-reference would fail to increment the std::shared_ptr reference counter.  This would lead to resources being reclaimed before we'd had a chance to use them.

**Comment by lynnard** [comment]
If the callback finishes without having to hold onto that shared ptr in the future - there is no need to increment and then decrement the reference count.

On the other hand, if the callback does need to use the pointer after it finishes (e.g., by using it in another lambda); then it will need to copy the ptr, and incrementing the reference count correctly.

See here: http://stackoverflow.com/questions/3310737/shared-ptr-by-reference-or-by-value

**Comment by ben-crowhurst** [comment]
Given Restbeds asynchronous nature, how do you know when the callback will be invoked?  It may remain on the run-loop for sometime before being called.

I would suggest a few tests.

**Comment by ben-crowhurst** [comment]
From the linked article

> Shortly, there is no reason to pass by value, unless there is multi-threading going on, but this needs to be considered separatel

**Comment by lynnard** [comment]
I think the 'multithreading' it's referring to concerns the case where you want to copy shared_ptr *when using it in another thread that can run after the current stack finishes*.

As I said before, in such case we do need to do copy - e.g. when there is a nested lambda callback. e.g.

```
void doWork(const shared_ptr<Object> &obj) {
  // run something
  scheduleCallback(3s, [ obj ] {
     // do something with obj in the future
  });
}
```

But as you can see this is handled properly - the moment the shared_ptr is captured by the lambda, the reference count is incremented as it gets copied.

For what's happening in the current stack, using pass-by-value in place by const ref achieves nothing more than incrementing the ref count at the beginning and decrementing it when finishes. And this cost is not that cheap.

**Comment by ben-crowhurst** [comment]
OK I'm willing to give it a shot.  Lets move on the more important side of this refactor.  How do we validate it?

Given we remove all references from Session how can we be assured no pointers are going to be reclaimed?

**Comment by ben-crowhurst** [comment]
This article maybe of interest to you.

https://web.archive.org/web/20130930101140/http://cpp-next.com/archive/2009/08/want-speed-pass-by-value
