### ISSUE TITLE
source/corvusoft/restbed/detail/socket_impl.hpp:24:38: fatal error: asio/io_service_strand.hpp: No such file or directory

### ISSUE THREAD

**Issue by MatthewButterfly** [Corvusoft/restbed#166]
source/corvusoft/restbed/detail/socket_impl.hpp:24:38: fatal error: asio/io_service_strand.hpp: No such file or directory

error when doing make.

**Comment by ben-crowhurst** [comment]
Are you following the build steps stated in the readme markdown?

**Comment by aviau** [comment]
Hello!

I am also getting this issue while building with the system-provided asio.

I am building this way because I am preparing the new Debian package for restbed.

**Comment by ben-crowhurst** [comment]
Please ensure you have at least ASIO 1.11.
