### ISSUE TITLE
HTTP request with empty data received

### ISSUE THREAD

**Issue by jackalsh** [Corvusoft/restbed#169]
I am running simpliest example from README file to run server.
On Arch machine everything works great, hovewer, running the same code on Centos 7 behaves very strange.
curl -H "Content-type: application/json" -XPOST -d '{"data":6}' http://127.0.0.1:1984/resource

It prints empty line. Simlple debug show, that body variable in request is empty and content length is equals to zero. But from the other side, I can see, that I send correct http request.

`
POST /resource HTTP/1.1
User-Agent: curl/7.29.0
Host: 127.0.0.1:1984
Accept: */*
Content-type: application/json
Content-Length: 10

{"data":6}
`

Can you please advice how can I debug this issue? Thanks in advance.

**Comment by ben-crowhurst** [comment]
OK lets see what we can do about this.  Can you please present your complete example client and server?

**Comment by ben-crowhurst** [comment]
@jackalsh have you manged to figure out your issue?

**Comment by ben-crowhurst** [comment]
@jackalsh?

**Comment by MasihAkbari** [comment]
I Could not replicate this Issue on CentOS 7.1.1503 (Linux 3.10.0-229.el7.x86_64 x86_64)
i made a shell script and curl call 10000 times to the web service and every call get it's reply successfully

**Comment by ben-crowhurst** [comment]
@MasihAkbari This was my conclusion also, thanks for confirming.

**Comment by ben-crowhurst** [comment]
Closing, most likely user error; non-responsive.
