### ISSUE TITLE
OpenSSL/GPL licensing issue

### ISSUE THREAD

**Issue by aberaud** [Corvusoft/restbed#170]
Hello,
What is Corvusoft position regarding compatibility between OpenSSL license and AGPL ?

I noticed your license doesn't include an OpenSSL exception.
Would that mean it's illegal to distribute an (A)GPL-licenced project including Restbed and its OpenSSL dependency ?

Thanks

**Comment by ben-crowhurst** [comment]
Our understanding is you free to use OpenSSL with any license given you abide by the [licensing terms](https://www.openssl.org/source/license.html).

>  Redistribution and use in source and binary forms, with or without
>  modification, are permitted provided that the following conditions
>  are met:
>  
>  1. Redistributions of source code must retain the above copyright
>     notice, this list of conditions and the following disclaimer. 
>  
>  2. Redistributions in binary form must reproduce the above copyright
>     notice, this list of conditions and the following disclaimer in
>     the documentation and/or other materials provided with the
>     distribution.
>  
>  3. All advertising materials mentioning features or use of this
>     software must display the following acknowledgment:
>     "This product includes software developed by the OpenSSL Project
>     for use in the OpenSSL Toolkit. (http://www.openssl.org/)"
>  
>  4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
>     endorse or promote products derived from this software without
>     prior written permission. For written permission, please contact
>     openssl-core@openssl.org.
>  
>  5. Products derived from this software may not be called "OpenSSL"
>     nor may "OpenSSL" appear in their names without prior written
>     permission of the OpenSSL Project.
>  
>  6. Redistributions of any form whatsoever must retain the following
>     acknowledgment:
>     "This product includes software developed by the OpenSSL Project
>     for use in the OpenSSL Toolkit (http://www.openssl.org/)"

**Comment by aberaud** [comment]
Sorry for this late answer.
My understanding is that some people think that condition 6 is incompatible with the GPL by putting restrictions on redistribution.
