### ISSUE TITLE
How to notice a SLOW POST from within a server application?

### ISSUE THREAD

**Issue by KiNgMaR** [Corvusoft/restbed#171]
Hi there,

thanks for making restbed, it's working really well. One question came up however: I want to use the HTTP server component. Naturally, I want to log all requests, including failed ones. One possibility for a request to fail is this:

        ~ $ curl -XPOST -d 'test=test' -vv -H 'Content-Length: 50' http://test:8081/test1
        * About to connect() to test port 8081
        *   Trying 10.0.0.1... connected
        * Connected to test (10.0.0.1) port 8081
        > POST /test1 HTTP/1.1
        > Host: test:8081
        > Accept: */*
        > Content-Length: 50
        > Content-Type: application/x-www-form-urlencoded
        >
        > test=testEmpty reply from server
        * Connection #0 to host test left intact
        curl: (52) Empty reply from server
        * Closing connection #0

Please notice that we send a Content-Length of 50, but only 10 bytes of data. The server-side handler looks something like this:

    size_t content_length = session->get_request()->get_header("Content-Length", 0);

    session->fetch(content_length, [](const std::shared_ptr<restbed::Session>, const restbed::Bytes& body)
    {
        session->close(...);
    });

Now the timeout in the socket's read() method handles this and closes the TCP connection. However, there doesn't seem to be a way for the application to receive an info about this happening... or is there? Could this result in a dangling ``shared_ptr<Session>``?

See also: https://blog.qualys.com/securitylabs/2011/07/07/identifying-slow-http-attack-vulnerabilities-on-web-applications

**Comment by ben-crowhurst** [comment]
Hey @KiNgMaR, looks like you're right. We don't seem to offer away of setting a custom timeout handler. I smell a new feature :tada: 

``` C++
void SocketImpl::connection_timeout_handler( const shared_ptr< SocketImpl > socket, const error_code& error )
{
    if ( error )
    {
        return;
    }
            
    if ( socket == nullptr or socket->m_timer->expires_at( ) > steady_clock::now( ) )
    {
        return;
    }
            
    socket->close( );
}
```

**Comment by ben-crowhurst** [comment]
We could invoke the error_handler with a std::runtime_error detailing timeout condition?

```C++
void set_error_handler( const std::function< void ( const int, const std::exception&, const std::shared_ptr< Session > ) >& value );
```
Rather ugly method signature, 5.0 has it in its cross hairs.

**Comment by KiNgMaR** [comment]
Hey @ben-crowhurst, thanks for looking into it! Any type of handler would be fine with me, I just need to be sure that I can be notified about any and all failed requests. To that end, I think that using the error_handler is a more consistent way than adding a separate timeout handler. 👍

**Comment by ben-crowhurst** [comment]
I will look to get this completed in the next couple of weeks. Sorry for the delay.

**Comment by ben-crowhurst** [comment]
I'm going to implement this with the following semantics.

```C++
void set_error_handler( const std::function< void ( const int, const std::exception&, const std::shared_ptr< Session > ) >& value );
```
Will be invoked with a 408 (Request Timeout) status code.

> _408 Request Timeout_
> The server timed out waiting for the request. According to HTTP specifications: "The client did not produce a request within the time that the server was prepared to wait. The client MAY repeat the request without modifications at any later time."

This will be implemented today 9th June 2017, any objections on the implementation please let me know.

**Comment by ben-crowhurst** [comment]
The implementation is somewhat wanting, however it should cover your requirement.  Please review and let us known if this is acceptable.

Note we are also handing in the session prior to closing the connection.

**Comment by ben-crowhurst** [comment]
Please reopen this ticket if it fails to satisfy your criteria.

**Comment by ben-crowhurst** [comment]
Note 5.0, due for public beta release this july, will resolve this matter in a more well rounded manner.
