### ISSUE TITLE
Fetch large requests without using chunked Transfer-Encoding.

### ISSUE THREAD

**Issue by CheyenneForbes** [Corvusoft/restbed#173]
this is to give an idea of what I want, but when I try it it doesnt "fetch" if the length isnt the "Content-Length". Basically I want to fetch parts of the request data similar to using a delimiter as in the "transfer_encoding_request" example but using a "maxSize". I want to do this for performance reasons (push the chunks to my object store as they reach the web servers) I am parsing multipart/formdata
```
auto maxSize = 2_mb;
get_data(const shared_ptr< Session > session){
   session->fetch( maxSize, [parse, add_to_file]( const shared_ptr< Session > session, const Bytes & body ){
     if(body.size()>0){ 
        auto chunk = parse(body.data()).file_chunk;
        add_to_file(chunk);
        get_data(session);
     else{
        session->close( OK, "File saved", { { "Content-Length", "10" }, { "Connection", "close" } } );
     }
  }
}
```

**Comment by ben-crowhurst** [comment]
What is your client command?

**Comment by CheyenneForbes** [comment]
"but when I try it doesn't fetch".
server code:
```
void get_method_handler( const shared_ptr< Session > session )
{
    const auto request = session->get_request( );
    
    ifstream stream( "test.html", ifstream::in );
    
    if ( stream.is_open( ) )
    {
        const string body = string( istreambuf_iterator< char >( stream ), istreambuf_iterator< char >( ) );
        
        const multimap< string, string > headers
        {
            { "Content-Type", "text/html" },
            { "Content-Length", ::to_string( body.length( ) ) }
        };
        session->close( OK, body, headers );
    }
    else
    {
        session->close( NOT_FOUND );
    }
}

void get_data(const shared_ptr< Session > session, size_t maxSize){	
  session->fetch( maxSize, [ maxSize ]( const shared_ptr< Session > session, const Bytes & body )mutable
  {
	size_read = body.size();
	if (size_read)
	{
		std::cout << "got more data, try to see if theres more" << "\n\r";
		get_data(session, maxSize);
	}
	else{
                std::cout << "no more data, now closing the connection" << "\n\r";
		session->close( OK, "done sending", { { "Content-Length", "12" }, { "Connection", "close" } } );
	}
  });
}

void post_method_handler( const shared_ptr< Session > session )
{
	const auto request = session->get_request( );
	
        size_t maxSize = 4 * 1024;

	get_data(session, maxSize);
}

int main( const int, const char** )
{
    auto resource = make_shared< Resource >( );
    resource->set_path( "/" );
    resource->set_method_handler( "GET", get_method_handler );
    resource->set_method_handler( "POST", post_method_handler );

    auto rest_settings = make_shared< Settings >( );
    rest_settings->set_port( 8080 );
    rest_settings->set_default_header( "Connection", "close" );
	
    Service service;
    service.publish( resource );
    service.start( rest_settings );

    return EXIT_SUCCESS;
}
```

client code:

```
<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<meta charset="utf-8"/>
		<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>
	</head>
	<body>
		<form class="form-horizontal wpc_contact" enctype="multipart/form-data" id="contact" method="post" name="13" novalidate="novalidate">
			<input class="input-file" id="fileInput" name="file" type="file"> <button class="btn btn-success">Button</button>
		</form>
		<script>
		window.formData = new FormData();
		formData.append('section', 'general');
		formData.append('action', 'previewImg');
		// Main magic with files here
		//formData.append('image', $('input[type=file]')[0].files[0]);
		$("button").on("click", function(e){
			e.preventDefault();
			$.ajax({
			   url: '/',
			   data: formData,
			   type: 'POST',
			   contentType: false,
			   processData: false
			})
		})
		</script>
	</body>
</html>
```

**Comment by ben-crowhurst** [comment]
So what happens? If it doesn't fetch what is it doing?

Please describe what is happening.

**Comment by ben-crowhurst** [comment]
With knowing what the problem is it's very hard to help.  Reading your code I ponder maxSize. If the value is larger than the data available on the socket it will block; off the top of my head.

**Comment by CheyenneForbes** [comment]
When I say it doesnt fetch I meant.. the callback of session->fetch(..){} doesnt get called the first time if i use the "maxSize" value instead of the value that comes in the "Content-Length" header. Also using he value that comes in the "Content-Length" header only works the first time (meaning if I call another "session->fetch(..){}" nothing happens), I thought if I "fetch" and there is nothing the code inside the callback of session->fetch(..){} would be called with the size of "Bytes &body" being zero.. try my server code and use the client code to upload a video and you will see the issue

**Comment by ben-crowhurst** [comment]
Yep I think it should block waiting on the data.  It will run once maxSize bytes are available.

**Comment by CheyenneForbes** [comment]
okay understood, 2 more questions

- Is there anyway to know if the code should "fetch" more data? like if anymore chunks are available without using chunked Transfer-Encoding.


- In regards to the length being more, does it block if the length is less than the actual data?

**Comment by ben-crowhurst** [comment]
1. The Socket will be exposed in version 5.0, the only way to determine if data is available is via valid HTTP mechanisms (Content-Length, Transfer-Encoding).

2. Yes the socket will block for Settings::set_connetion_timeout duration for data you have requested. If it does not present itself the socket with closed. Once again in version 5.0 the connection timeout handler will be exposed for further processing.
