### ISSUE TITLE
Default to use OPENSSL system library on UNIX

### ISSUE THREAD

**Issue by nunojpg** [Corvusoft/restbed#174]
OPENSSL is a major dependency in size and security implications, and some applications that use restbed will end up using also openssl directly.

Linking statically to a specific version of OPENSSL looks to not be required, and so desirable, for restbed.

So it should default to using the system library, with the option to compile the bundled dependency.

As a CMake implementation example and explanation, look at: https://github.com/uclouvain/openjpeg/tree/master/thirdparty

If you think this is a good idea, I can implement it and pull request.

**Comment by ben-crowhurst** [comment]
5.0 is addressing this very matter. Thanks for validating our thinking :+1:
