### ISSUE TITLE
Building on Ubuntu 16.04 make target "all" failing

### ISSUE THREAD

**Issue by ejyanezp** [Corvusoft/restbed#176]
Hi, 

I followed the instructions supplied on the project's Github page section "Build", they are very easy to follow, this is the output of the cmake command when I try to build with SSL (without SSL I can build all):

-----------------------------------------------
eduardo@ubuntu:~/CppDevelopment/restbed/build$ cmake -DBUILD_TESTS=YES -DBUILD_EXAMPLES=YES -DBUILD_SSL=YES -DBUILD_SHARED=YES -DCMAKE_INSTALL_PREFIX=../bin ..
   Copyright 2013-2016, Corvusoft Ltd, All Rights Reserved.

-- Found ASIO include at: /home/eduardo/CppDevelopment/restbed/dependency/asio/asio/include
-- Found Kashmir include at: /home/eduardo/CppDevelopment/restbed/dependency/kashmir
-- Found OpenSSL library at: /usr/lib/x86_64-linux-gnu/libssl.so
-- Found OpenSSL include at: /usr/include
-- Found Crypto library at: /usr/lib/x86_64-linux-gnu/libcrypto.so
-- Failed to locate PAM, skipping example.
-- Found Syslog include at: /usr/include
-- Found Catch include at: /home/eduardo/CppDevelopment/restbed/dependency/catch/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eduardo/CppDevelopment/restbed/build
eduardo@ubuntu:~/CppDevelopment/restbed/build$ 

---------------------------------------------

As cmake detected you can see that ssl and crypto libraries are present in my Ubuntu box. Then I submit the command:
$ make -j 5 install

This is the output of the make command:

----------------------------------------------
eduardo@ubuntu:~/CppDevelopment/restbed/build$ make -j 5 install
Scanning dependencies of target restbed
[  0%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/uri.cpp.o
[  1%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/rule.cpp.o
[  1%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/string.cpp.o
[  2%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/request.cpp.o
[  2%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/http.cpp.o
[  2%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/service.cpp.o
[  2%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/session.cpp.o
[  3%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/resource.cpp.o
[  3%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/response.cpp.o
[  3%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/settings.cpp.o
[  4%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/web_socket.cpp.o
[  4%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/ssl_settings.cpp.o
[  4%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/session_manager.cpp.o
[  5%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/http_impl.cpp.o
[  5%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/web_socket_message.cpp.o
[  5%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/socket_impl.cpp.o
[  6%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/service_impl.cpp.o
[  6%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/session_impl.cpp.o
[  6%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/web_socket_impl.cpp.o
[  7%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/web_socket_manager_impl.cpp.o
[  7%] Linking CXX shared library librestbed.so
[  7%] Built target restbed
Scanning dependencies of target web_socket
Scanning dependencies of target session_manager
Scanning dependencies of target https_client_verify_peer
Scanning dependencies of target signal_handling
Scanning dependencies of target https_service
[  7%] Building CXX object example/CMakeFiles/session_manager.dir/session_manager/source/example.cpp.o
[  8%] Building CXX object example/CMakeFiles/https_client_verify_peer.dir/https_client/source/verify_peer.cpp.o
[  8%] Building CXX object example/CMakeFiles/web_socket.dir/web_socket/source/example.cpp.o
[  8%] Building CXX object example/CMakeFiles/https_service.dir/https_service/source/example.cpp.o
[  9%] Building CXX object example/CMakeFiles/signal_handling.dir/signal_handling/source/example.cpp.o
[  9%] Linking CXX executable example/https_client_verify_peer
[ 10%] Linking CXX executable example/https_service
[ 10%] Built target https_client_verify_peer
[ 10%] Linking CXX executable example/signal_handling
Scanning dependencies of target publishing_multipath_resources
[ 11%] Building CXX object example/CMakeFiles/publishing_multipath_resources.dir/publishing_multipath_resources/source/example.cpp.o
[ 11%] Built target https_service
[ 11%] Linking CXX executable example/session_manager
Scanning dependencies of target transfer_encoding_response
[ 11%] Built target signal_handling
[ 12%] Building CXX object example/CMakeFiles/transfer_encoding_response.dir/transfer_encoding_response/source/example.cpp.o
Scanning dependencies of target https_client_verify_none
[ 12%] Building CXX object example/CMakeFiles/https_client_verify_none.dir/https_client/source/verify_none.cpp.o
[ 12%] Built target session_manager
Scanning dependencies of target publishing_resources
[ 12%] Building CXX object example/CMakeFiles/publishing_resources.dir/publishing_resources/source/example.cpp.o
[ 13%] Linking CXX executable example/web_socket
/usr/bin/ld: CMakeFiles/web_socket.dir/web_socket/source/example.cpp.o: undefined reference to symbol 'BIO_ctrl@@OPENSSL_1.0.0'
//lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
example/CMakeFiles/web_socket.dir/build.make:95: recipe for target 'example/example/web_socket' failed
make[2]: *** [example/example/web_socket] Error 1
CMakeFiles/Makefile2:186: recipe for target 'example/CMakeFiles/web_socket.dir/all' failed
make[1]: *** [example/CMakeFiles/web_socket.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 13%] Linking CXX executable example/publishing_multipath_resources
[ 13%] Linking CXX executable example/https_client_verify_none
[ 13%] Linking CXX executable example/transfer_encoding_response
[ 13%] Built target publishing_multipath_resources
[ 13%] Built target transfer_encoding_response
[ 13%] Built target https_client_verify_none
[ 14%] Linking CXX executable example/publishing_resources
[ 14%] Built target publishing_resources
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

-------------------------------------------------

The symbol "BIO_ctrl@@OPENSSL_1.0.0" belongs to the libcrypto.so.1.0.0 library as you can see:

root@ubuntu:/lib/x86_64-linux-gnu# readelf -a libcrypto.so.1.0.0 | grep BIO_ctrl
   454: 0000000000110e60   211 FUNC    GLOBAL DEFAULT   13 BIO_ctrl@@OPENSSL_1.0.0

I don't know why the linker does not find the symbol for the web_socket example (after finding ssl on the previous example https_service). How could I collaborate with you in order to find the problem? (As you know, RESTFull services without SSL is a NO-GO)

Thanks in advanced for your time and attention.

Regards, 
Eduardo.

**Comment by callum-kirby** [comment]
Looks as if its not finding, linking, the libcrypto dependency.  Try building the version of OpenSSL that comes with restbed.

Off the top of my head:
```
cd dependency/openssl
./Config
make
```

no need for make install.

**Comment by callum-kirby** [comment]
The WebSocket example only consumes the Base64 component from OpenSSL so... guess your version is missing that aspect?  This conclusion is renforced by the HTTPS client examples building without fail.

**Comment by ejyanezp** [comment]
Hi Callum, thanks for your attention :)

I switched to the OpenSSL code that comes with restbed dendencies, I compiled it (conf, make, make test) and droped using the libraries that come with Ubuntu 16.04, here are the results (not success)

--------------------------------------------------

eduardo@ubuntu:~/CppDevelopment/restbed/build$ cmake -DBUILD_TESTS=YES -DBUILD_EXAMPLES=YES -DBUILD_SSL=YES -DBUILD_SHARED=YES -DCMAKE_INSTALL_PREFIX=../bin ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
   Copyright 2013-2016, Corvusoft Ltd, All Rights Reserved.
-- Found ASIO include at: /home/eduardo/CppDevelopment/restbed/dependency/asio/asio/include
-- Found Kashmir include at: /home/eduardo/CppDevelopment/restbed/dependency/kashmir
-- Found OpenSSL library at: /home/eduardo/CppDevelopment/restbed/dependency/openssl/libssl.a
-- Found OpenSSL include at: /home/eduardo/CppDevelopment/restbed/dependency/openssl/include
-- Found Crypto library at: /home/eduardo/CppDevelopment/restbed/dependency/openssl/libcrypto.a
-- Failed to locate PAM, skipping example.
-- Found Syslog include at: /usr/include
-- Found Catch include at: /home/eduardo/CppDevelopment/restbed/dependency/catch/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eduardo/CppDevelopment/restbed/build

----------------------------------------------------------
eduardo@ubuntu:~/CppDevelopment/restbed/build$ make -j 5 install
Scanning dependencies of target restbed
[  1%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/rule.cpp.o
[  1%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/http.cpp.o
[  1%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/uri.cpp.o
[  1%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/string.cpp.o
[  2%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/request.cpp.o
[  2%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/service.cpp.o
[  2%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/session.cpp.o
[  3%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/resource.cpp.o
[  3%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/response.cpp.o
[  3%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/settings.cpp.o
[  4%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/web_socket.cpp.o
[  4%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/ssl_settings.cpp.o
[  4%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/session_manager.cpp.o
[  5%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/http_impl.cpp.o
[  5%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/web_socket_message.cpp.o
[  5%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/socket_impl.cpp.o
[  6%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/service_impl.cpp.o
[  6%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/session_impl.cpp.o
[  6%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/web_socket_impl.cpp.o
[  7%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/detail/web_socket_manager_impl.cpp.o
[  7%] Linking CXX shared library librestbed.so
/usr/bin/ld: ../dependency/openssl/libssl.a(s3_meth.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
../dependency/openssl/libssl.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/restbed.dir/build.make:590: recipe for target 'librestbed.so.4.5.0' failed
make[2]: *** [librestbed.so.4.5.0] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/restbed.dir/all' failed
make[1]: *** [CMakeFiles/restbed.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

------------------------------------------------
I don't know where to put the -fPIC option, I think I'll have to study cmake to help you ;).

Which platform do you use for development?
** Mine:
- cmake version 3.5.1
- GNU Make 4.1
- g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
- Linux ubuntu 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Regards,
Eduardo.

**Comment by ejyanezp** [comment]
Answering your second comment:

The Ubuntu library I was using: libssl-dev (I installed it using apt-get).

----------------------------------------

root@ubuntu:/usr/lib/x86_64-linux-gnu# dpkg -l | grep ssl
ii  libflac8:amd64                             1.3.1-4                                       amd64        Free Lossless Audio Codec - runtime C library
ii  libgnutls-openssl27:amd64                  3.4.10-4ubuntu1.1                             amd64        GNU TLS library - OpenSSL wrapper
ii  libio-socket-ssl-perl                      2.024-1                                       all          Perl module implementing object oriented interface to SSL sockets
ii  libnet-smtp-ssl-perl                       1.03-1                                        all          Perl module providing SSL support to Net::SMTP
ii  libnet-ssleay-perl                         1.72-1build1                                  amd64        Perl module for Secure Sockets Layer (SSL)

### ii  libssl-dev:amd64                           1.0.2g-1ubuntu4.5                             amd64        Secure Sockets Layer toolkit - development files

ii  libssl-doc                                 1.0.2g-1ubuntu4.5                             all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64                          1.0.2g-1ubuntu4.5                             amd64        Secure Sockets Layer toolkit - shared libraries
ii  libwavpack1:amd64                          4.75.2-2                                      amd64        audio codec (lossy and lossless) - library
ii  openssl                                    1.0.2g-1ubuntu4.5                             amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  ssl-cert                                   1.0.37                                        all          simple debconf wrapper for OpenSSL

-------------------------------------

I enquired the library files of the package for "Base64", these are the results:

root@ubuntu:/lib/x86_64-linux-gnu# readelf -a libssl.so.1.0.0 | grep Base
(no symbols listed)
root@ubuntu:/usr/lib/x86_64-linux-gnu# nm -a libssl.a | grep Base
(no symbols listed)

So yes, the Ubuntu 16.04 version of SSL is missing the Base64 aspect.

Tell me what else could I do to help the project.

Regards,
e.

**Comment by ben-crowhurst** [comment]
The command to build OpenSSL on Linux is `./Config; make all`.

**Comment by ben-crowhurst** [comment]
OK it appears building with `-DBUILD_SHARED=YES` is causing the problem.

**Comment by ben-crowhurst** [comment]
Found the problem.  Within the Web Socket example we use the Base64 components without linking the ssl/crypto libs.  This issue is only presenting itself Linux to our knowledge.

Will push a fix shortly.

**Comment by ben-crowhurst** [comment]
@ejyanezp I've pushed a fix for this issue, you should be able to use the native OpenSSL that comes bundled with your distro.

Please validate the fix and let me know of any further issues.

**Comment by ejyanezp** [comment]
Excellent!, I validated and the compilation run smoothly on Ubuntu 16.04.

I used the command:

```
eduardo@ubuntu:~/CppDevelopment/restbed/build$ cmake -DBUILD_TESTS=YES -DBUILD_EXAMPLES=YES -DBUILD_SSL=YES -DBUILD_SHARED=YES -DCMAKE_INSTALL_PREFIX=../bin ..
   Copyright 2013-2016, Corvusoft Ltd, All Rights Reserved.
-- Found ASIO include at: /home/eduardo/CppDevelopment/restbed/dependency/asio/asio/include
-- Found Kashmir include at: /home/eduardo/CppDevelopment/restbed/dependency/kashmir
-- Found OpenSSL library at: /usr/lib/x86_64-linux-gnu/libssl.so
-- Found OpenSSL include at: /usr/include
-- Found Crypto library at: /usr/lib/x86_64-linux-gnu/libcrypto.so
-- Failed to locate PAM, skipping example.
-- Found Syslog include at: /usr/include
-- Found Catch include at: /home/eduardo/CppDevelopment/restbed/dependency/catch/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eduardo/CppDevelopment/restbed/build
eduardo@ubuntu:~/CppDevelopment/restbed/build$ 

```
Please note i compiled successfully against Ubuntu 16.04 SSL/Crypto installed libraries with apt-get (not the project dependencies).

If I could serve you for anything else, please let me know.

Regards,

**Comment by ben-crowhurst** [comment]
Thanks for your help.
