### ISSUE TITLE
Reuse client connection (Http::fetch) until user calls a "disconnect()" function or timeout

### ISSUE THREAD

**Issue by CheyenneForbes** [Corvusoft/restbed#179]

**Comment by ben-crowhurst** [comment]
The socket is not closed by the client unless you invoke `Http:close`.

**Comment by CheyenneForbes** [comment]
does it "auto close" if I dont call Http:close?

**Comment by ben-crowhurst** [comment]
The destructor will call close when the object is reclaimed or the server closes the connection.
