### ISSUE TITLE
Replace ${CMAKE_SOURCE_DIR} with ${PROJECT_SOURCE_DIR}

### ISSUE THREAD

**Issue by gpean** [Corvusoft/restbed#186]
Using ${CMAKE_SOURCE_DIR} in the CMakeLists files make it impossible to embed restbed as part of a bigger project through "add_subdirectory" because it will reference the root of the top level project (if any), when what you expect is getting the root directory for restbed itself.

The simple fix is that you should change CMAKE_SOURCE_DIR into PROJECT_SOURCE_DIR, which ensures that you will get to the root of restbed, and not to the root of the top level project.

**Comment by ben-crowhurst** [comment]
Do you have a pull request available?

**Comment by ben-crowhurst** [comment]
Close as this was merged.
