### ISSUE TITLE
"/dev/urandom" 

### ISSUE THREAD

**Issue by michaelaeriksen** [Corvusoft/restbed#188]
"/dev/urandom" does not exists on Windows!

**Comment by ben-crowhurst** [comment]
Your point being?

**Comment by michaelaeriksen** [comment]
When I try to run the web_socket example it fails when trying to open the "/dev/urandom" file
```
class DevRandom : public randomstream<DevRandom>, unique<DevRandom>
{
    std::ifstream file;

public:
    DevRandom() : file("/dev/random", std::ios::binary)
    {
        if (!file)
            throw std::runtime_error("failed to open random device.");
    }

    void read(char *buffer, std::size_t count)
    {
        file.read(buffer, count);
    }
};
```

**Comment by michaelaeriksen** [comment]
On Windows I replaced 

            kashmir::uuid_t uuid;
            kashmir::system::DevRand random;
            random >> uuid;
            stringstream stream;
            stream << uuid;
            const auto key = stream.str( );

with

            UUID uuid;
            UuidCreate(&uuid);
            unsigned char * str;
            UuidToStringA(&uuid, &str);
            std::string s((char*)str);
            RpcStringFreeA(&str);
            const auto key = s;

**Comment by michaelaeriksen** [comment]
I'm not sure why you use some UNIX specific random generator instead of std::random or some other implementation. 

Maybe look at this http://www.pcg-random.org/posts/cpps-random_device.html

**Comment by ben-crowhurst** [comment]
@michaelaeriksen This relates to a third party dependency, Kashmir.  

Please in the future for sake of all Open Source communities, provide detail around your comments.  Help us help you.

This issue will be resolved with the upcoming Restbed 5.0 release.

Thanks for flagging the issue.

**Comment by Manish244** [comment]
@ben-crowhurst  Is there any planned release date for 5.0.

**Comment by ben-crowhurst** [comment]
Tentative yes.  We are aiming for a January 2018 beta release date.

**Comment by ben-crowhurst** [comment]
This issue has been resolved by using the core OpenSSL functionality and dropping the Kashmir dependency from the websocket example.
