### ISSUE TITLE
Request :: get_body failed?

### ISSUE THREAD

**Issue by sotex** [Corvusoft/restbed#190]
Why use `Request :: get_body` to get the result is empty?
Is it possible to get the requested `body` content correctly only when using `Session::Fetch (lengtht, [] (const shared_ptr <Session> session, const Bytes & body)`

**Comment by ben-crowhurst** [comment]
Fetch is required for transfer-encoding.

**Comment by ben-crowhurst** [comment]
Please provide an example of what you are trying to do.
