### ISSUE TITLE
Allow Cross-Origin Requests

### ISSUE THREAD

**Issue by CheyenneForbes** [Corvusoft/restbed#191]
I tried:
`rest_settings->set_default_header( "Access-Control-Allow-Origin", "*");`
but I still cant access my rest service from another site I get:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://172.17.0.2:8080/posts. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

**Comment by ben-crowhurst** [comment]
And is the header missing?

**Comment by CheyenneForbes** [comment]
is `rest_settings->set_default_header( "Access-Control-Allow-Origin", "*");` enough?

**Comment by ben-crowhurst** [comment]
And is the heading missing?

**Comment by CheyenneForbes** [comment]
No

**Comment by ben-crowhurst** [comment]
We'll attempt to reproduce and have a fix shortly.

**Comment by dozyh** [comment]
I was looking for a C++ library for REST. Your rude response to CheyenneForbes second post asking for clarification on what you said has resulted in me continuing my search elsewhere.

**Comment by ben-crowhurst** [comment]
Performed the following test, No error found.  Once again please check the header is returned.

```C++
//System Includes
#include <map>
#include <thread>
#include <memory>
#include <chrono>
#include <functional>

//Project Includes
#include <restbed>

//External Includes
#include <catch.hpp>

//System Namespaces
using std::thread;
using std::string;
using std::multimap;
using std::shared_ptr;
using std::make_shared;
using std::chrono::seconds;

//Project Namespaces
using namespace restbed;

//External Namespaces

void get_handler( const shared_ptr< Session > session )
{
    session->close( OK, "", { { "Connection", "close" } } );
}

TEST_CASE( "client fails to calculate correct response body length", "[http]" )
{
    auto resource = make_shared< Resource >( );
    resource->set_path( "test" );
    resource->set_method_handler( "GET", get_handler );
    
    auto settings = make_shared< Settings >( );
    settings->set_port( 1984 );
    settings->set_default_header( "Access-Control-Allow-Origin", "*" );
    
    shared_ptr< thread > worker = nullptr;
    
    Service service;
    service.publish( resource );
    service.set_ready_handler( [ &worker ]( Service & service )
    {
        worker = make_shared< thread >( [ &service ] ( )
        {
            auto request = make_shared< Request >( );
            request->set_method( "GET" );
            request->set_port( 1984 );
            request->set_host( "localhost" );
            request->set_path( "/test" );
            
            auto response = Http::sync( request );
            
            REQUIRE( 200 == response->get_status_code( ) );
            REQUIRE( "*" == response->get_header( "Access-Control-Allow-Origin" ) );
            
            service.stop( );
        } );
    } );
    service.start( settings );
    worker->join( );
}
```

**Comment by CheyenneForbes** [comment]
Hi @dozyh @callum-kirby and @MasihAkbari even tho ben was a bit rude I'd still recommend you to use and contribute to restbed, theres nothing as good as it :)

**Comment by Ahmed-Hussein-Karam** [comment]
> is `rest_settings->set_default_header( "Access-Control-Allow-Origin", "*");` enough?

Yes, it worked for me. Thakns

**Comment by TaeZStkyoht** [comment]
If you use Authorization (Bearer etc.) and you implemented a Authentication Handler of service with service's set_authentication_handler call, then you should;
- in service settings:
        settings->set_default_header("Access-Control-Allow-Headers", "Authorization");
- In the begining of your Authentication Handler function: 
        const auto& request = session->get_request();
	if (request->get_method() == "OPTIONS") {
		session->close(OK);
		return;
	}
