### ISSUE TITLE
Allow parameter names to include underscores

### ISSUE THREAD

**Issue by CheyenneForbes** [Corvusoft/restbed#192]
in `corvusoft/restbed/detail/service_impl.cpp` I think `static const regex pattern( "^\\{[a-zA-Z0-9]+: ?(.*)\\}$" );` should be changed to `static const regex pattern( "^\\{[_a-zA-Z0-9]+: ?(.*)\\}$" );` to allow parameter names to include underscores (eg. user_id)

**Comment by ben-crowhurst** [comment]
Will implement regression test and resolve shortly. 

Thanks you.

**Comment by ben-crowhurst** [comment]
Please provide a test case illustrating your intended purpose.

**Comment by CheyenneForbes** [comment]
some developers prefer to use user_id than UserId in some cases... "feels" cleaner in some cases, for example the protobuf library

**Comment by ben-crowhurst** [comment]
If we go down this road we might as well extend it to include a lot more e.g -_|~`, etc...

**Comment by ben-crowhurst** [comment]
We've implemented the requested enhancement and can now state that path parameter names may include underscores, hyphens, and alphanumerics.

**Comment by ben-crowhurst** [comment]
Due to CI issues the project has been reverted.  I'll make this change available tomorrow at the latest.

**Comment by ben-crowhurst** [comment]
OK this is no in master :1st_place_medal:
