### ISSUE TITLE
Problem upgrading session to websocket

### ISSUE THREAD

**Issue by gouzaa** [Corvusoft/restbed#198]
I don't know what I do wrong, but i'm not able to open a websocket. 

First of all, let me say that i'm using the latest version of the code. I'm trying to run the providing example "web_socket" but it fails. Trying x64 both release and debug.

![image](https://cloud.githubusercontent.com/assets/7569626/24547528/4887b016-15de-11e7-91d7-c0cafb03b93d.png)

It cannot pass this line of code 

`session->upgrade( SWITCHING_PROTOCOLS, headers, [ ]( const shared_ptr< WebSocket > socket )`

This is what I did 
- Cloned the repo
- Compiled openssl depency using INSTALL.W64 procedure
- Using CMake to build both restbed (with openssl because I know that web_socket example needs it) and examples 
- Running web_socket.exe.

at this point everything is ok. But I'm not able to establish a connection

What am I doing wrong ?

**Comment by gouzaa** [comment]
Ok, forget about it. I found that it is related to #188 
The mentioned fix will do the job

**Comment by ben-crowhurst** [comment]
Closing as a duplicate. Thanks for your input, fix is on the way.
