### ISSUE TITLE
Error in websocket example

### ISSUE THREAD

**Issue by stkrwork** [Corvusoft/restbed#199]
When using the web_socket example, i get an error bad file descriptor on the console right after closing the connection.

Here is the log:
Sent welcome message to 3a64fe9d-cf53-48c4-a9f3-b1a830d55cd7.
Closed connection to 3a64fe9d-cf53-48c4-a9f3-b1a830d55cd7.
WebSocket Errored 'Bad file descriptor' for 3a64fe9d-cf53-48c4-a9f3-b1a830d55cd7.

i use the simple websocket client extension in chrome as a debug client.

The example does not crash.

**Comment by ben-crowhurst** [comment]
Thanks for reporting this will look into it shortly.

**Comment by stkrwork** [comment]
Is there any update to this?

**Comment by stkrwork** [comment]
After looking into the source code, I saw that by adding a check for m_is_open in socket_impl.cpp in the read and write functions, this error disappears.

**Comment by ben-crowhurst** [comment]
Awesome please provide a PR. Sorry we haven't made time for this yet we are beavering away with the upcoming 5.0 release.

**Comment by stkrwork** [comment]
#208 is the pull request

**Comment by ben-crowhurst** [comment]
Thanks, I'll action this before end of the week.

**Comment by ben-crowhurst** [comment]
Attempted to look into this however formatting has gone loopy as all the whitespace has changed.

https://github.com/Corvusoft/restbed/pull/208/commits/2966cfeb5593ba4efc776a0dc3a1bc8fcd0afaba

Please format the code as per restbed/tool/astyle/options prior to committing.  To ease future development we have supplied a pre-commit hook under restbed/tool/git/pre-commit.

**Comment by stkrwork** [comment]
I made another commit that highlights the changes i made.

**Comment by stkrwork** [comment]
#210 new pull request, old one got deleted somehow

**Comment by ben-crowhurst** [comment]
Greate work @stkrwork.
