### ISSUE TITLE
get_query_parameter with double type

### ISSUE THREAD

**Issue by mipac** [Corvusoft/restbed#200]
the template overload of  get_query_parameter does not support "double" type:
`double x = request->get_query_parameter("x", 0.0);`

I don't know if it is wanted
The function declaration is too complicated for me ;)

in request.hpp:
```
template< typename Type, typename std::enable_if< std::is_arithmetic< Type >::value, Type >::type = 0 >
Type get_query_parameter( const std::string& name, const Type default_value ) const
```

but I don't understand why double would not be an arithmetic type??

my conf:
```
gcc (Debian 4.9.2-10) 4.9.2
Codename:	jessie
```

**Comment by ben-crowhurst** [comment]
What is the outcome of running your code? error message?

**Comment by mipac** [comment]
This is the compilation error:

```
calcul_dsp_rest_api.h:172:66:` error: no matching function for call to ‘restbed::Request::get_query_parameter(const char [6], double) const’
         double dt_ms = request->get_query_parameter("dt_ms",  0.0);
                                                                  ^
include/corvusoft/restbed/request.hpp:99:18: note: template<class Type, typename std::enable_if<std::is_arithmetic<_Tp>::value, Type>::type <anonymous> > Type restbed::Request::get_query_parameter(const string&, Type) const
             Type get_query_parameter( const std::string& name, const Type default_value ) const
                  ^
corvusoft/restbed/request.hpp:99:18: note:   template argument deduction/substitution failed:
include/corvusoft/restbed/request.hpp:98:113: error: ‘std::enable_if<true, double>::type {aka double}’ is not a valid type for a template non-type parameter
             template< typename Type, typename std::enable_if< std::is_arithmetic< Type >::value, Type >::type = 0 >
               ^
include/corvusoft/restbed/request.hpp:104:25: note: std::string restbed::Request::get_query_parameter(const string&, const string&) const
             std::string get_query_parameter( const std::string& name, const std::string& default_value ) const;
                         ^
include/corvusoft/restbed/request.hpp:104:25: note:   no known conversion for argument 2 from ‘double’ to ‘const string& {aka const std::basic_string<char>&}’
include/corvusoft/restbed/request.hpp:106:25: note: std::string restbed::Request::get_query_parameter(const string&, const std::function<std::basic_string<char>(const std::basic_string<char>&)>&) const
             std::string get_query_parameter( const std::string& name, const std::function< std::string ( const std::string& ) >& transform = nullptr ) const;
                         ^
include/corvusoft/restbed/request.hpp:106:25: note:   no known conversion for argument 2 from ‘double’ to ‘const std::function<std::basic_string<char>(const std::basic_string<char>&)>&’

```

the error is the same with float type
this template overload works with int/short/long/unsigned... but not for floating point type

**Comment by ben-crowhurst** [comment]
Thanks, we'll take a look this week.

**Comment by mipac** [comment]
If I write the template condition like that it seems to be OK:

```
template < typename T, typename = enable_if_t< is_arithmetic< T >::value > >
T demo( const string& s, const T default_value ) {
    T r;
    stringstream os( s );
    os >> r;
    if ( os.fail( ) )
        r = default_value;

    return r;
}

double x = demo( "2.4", 8.0 );             // OK, x = 2.4
size_t i = demo( "123", 789ul );           // OK, i = 123
size_t j = demo( "bad test", 789ul );      // OK, j = 789
string s = demo( "bad test", "bad" );      // NOK not arithmetic
char*  p = demo( "bad test", &x );         // NOK not arithmetic


```

**Comment by ben-crowhurst** [comment]
I'll give a shot thanks.

**Comment by ben-crowhurst** [comment]
Complier error:
> candidate template ignored: substitution failure [with Type = double]:
> a non-type template parameter cannot have type 'typename
> std::enable_if<std::is_arithmetic<double>::value, double>::type' (aka 'double') Type get_header(
> const std::string& name, const Type default_value ) const

C++11 specification:

> 14.3.2/1      Template non-type arguments      [temp.arg.nontype]
> 
> A template-argument for a non-type, non-template template-parameter shall be one of:
> 
> - for a non-type template-parameter of integral or enumeration type, a converted constant expression (5.19) of the type of the template-parameter;
>  - the name of a non-type template-parameter; or
> - a constant expression (5.19) that designates the address of an object with static storage duration and external or internal linkage or a function with external or internal linkage, including function templates and function template-ids but excluding non-static class members, expressed (ignoring parentheses) as & id-expression, except that the & may be omitted if the name refers to a function or array and shall be omitted if the corresponding template-parameter is a reference; or
> - a constant expression that evaluates to a null pointer value (4.10); or
> - a constant expression that evaluates to a null member pointer value (4.11); or
> - a pointer to member expressed as described in 5.3.1.

You example is working due to C++14, which is evident by the use of [std::enable_if_t](http://en.cppreference.com/w/cpp/types/enable_if).

**Comment by ben-crowhurst** [comment]
This enhancement will be released with Restbed 5.0, which is due for public consumption no later than the 30th June 2017.

Thanks for your patience.

**Comment by mipac** [comment]
good news! 
for the user googling the issue: just get the parameter with a string and use stod() to convert to double.

thank you very much

**Comment by ben-crowhurst** [comment]
@mipac We've not built this functionality directly into Restbed;  You must provide a default value.

```
double default_value = 0.0;
double value = Request::get_header( "my-var", default_value );
```

See HEAD for the latest code changes.
