### ISSUE TITLE
is it possible to set underlying sockets option?

### ISSUE THREAD

**Issue by mipac** [Corvusoft/restbed#205]
for example to allow reusing ip:port
or to change snd/recv buffers, etc...

**Comment by ben-crowhurst** [comment]
Not in a portable fashion, no.  We currently force reusing ip:port, however we offer no means of changing the send and receive buffers.

What is your specific use case?

**Comment by mipac** [comment]
I haven't a specific use case, I just wonder what I can "tweak" 
reusing ip:port is what I need first and this is already the case
I often  have to boost send buffers in my socket apps when I stream binaries

I open the question "too fast", sorry for the noise :)

**Comment by ben-crowhurst** [comment]
Not a problem, we love interacting and growing the community around Restbed 👍
