### ISSUE TITLE
Filling the body of a response

### ISSUE THREAD

**Issue by ehsun-zad** [Corvusoft/restbed#209]
First of all how could I fill the body of my response on the server side with a struct? For example I have:
Struct student
{
     int id = 10;
     string name = "someone";
}
My second question is about the receiving body on the client side. The get_body().data() provides byte and I don't know how could I receive a struct with byte?
And my last question is that, do I need to parse the body (such as the mentioned struct) into XML or json at the server and the client side?

**Comment by ben-crowhurst** [comment]
Restbed is not an object-relational mapping solution. It is designed for creating HTTP services.

Have a look at our reply to [How to Create Restful Web Services using c++ language and JSON Parser](http://stackoverflow.com/questions/25057819/how-to-create-restful-web-services-using-c-language-and-json-parser) to get a better idea of how you might approach this problem.

**Comment by ehsun-zad** [comment]
It means that I have to use an external JSON parser (or XML parser) with all RESTful frameworks? Sorry for asking, but do you know any RESTful framework with built in parser?
And it may seems irrelevant, but do you suggest RESTful frameworks or SOAP frameworks (such as KDSOAP and gSOAP) for situations in which object-relational mapping is needed?

**Comment by ben-crowhurst** [comment]
That is a very broad question with a very in-depth explanation required.  This is why your question on [StackOverflow](http://stackoverflow.com/questions/43839332/providing-restful-service-in-c-frameworks/43863657#43863657) is being down voted.
