### ISSUE TITLE
Ideas for reducing build time.

### ISSUE THREAD

**Issue by ben-crowhurst** [Corvusoft/restbed#215]
This ticket is for any and everyone to drop in ideas for reducing the build time.  CI is taking a considerable length of time and we need this to drop now the team is increasing.

**Comment by ben-crowhurst** [comment]
We could move the examples into static documentation?

**Comment by callum-kirby** [comment]
@ben-crowhurst I agree. Examples are taking far too long when build.

**Comment by ben-crowhurst** [comment]
We have converted the examples into documentation.  This has reduced the build, maintenance, and validation cycle.
