### ISSUE TITLE
Meet snprintf' : is not a member of 'std'? and the other error

### ISSUE THREAD

**Issue by LZS1991** [Corvusoft/restbed#220]
When i compiled the source code with the vs2013, some error occured.
1.snprintf' : is not a member of 'std'
2.error C2797: 'restbed::detail::SettingsImpl::m_status_messages',
so why these happen?i think we should meet no problem when we compile it

**Comment by ben-crowhurst** [comment]
Visual Studio 2013 is not supported, upgrade to 2015 or 2017.

**Comment by LZS1991** [comment]
OK，Thank you very much，i hava solve it by using the vs2015
