### ISSUE TITLE
how can i use this library to create a restful server?Where can i get a demo

### ISSUE THREAD

**Issue by LZS1991** [Corvusoft/restbed#221]

**Comment by bsenftner** [comment]
Download and check out the “example” directory. There you will find a series of small sample programs that each individually demonstrate 1-2 aspects of what you’ll want for your REST server. I suggest you start with either the http_service or the https_service example and grow from there, adding features demonstrated in the other examples.

There is no single document walking one through creating a full featured REST server, but if you have any experience with REST, the examples show one how to do everything you’ll need. 

Sincerely,
-Blake Senftner
Developer, MBA, Technology CEO, Mad Scientist 

---> Blake loves the Planet Earth and is proud to display this email with Recycled Electrons. <---

**Comment by LZS1991** [comment]
Thank you，i will have a try！At the same time，i want to say，if the demos can include a restful demo，it will be great
