### ISSUE TITLE
Compiling RestBED in CLion

### ISSUE THREAD

**Issue by Paaaaaaul** [Corvusoft/restbed#222]
Hi,
I am new to RestBED and coding with C++ on Mac (Prior experience on Windows without CMakeFiles).
I having an issue when compiling my main.cpp file with the following error:

`/Users/adjust/Documents/Development/main.cpp:6:10: fatal error: 'restbed' file not found`

I also have following make error:
`make[3]: *** [CMakeFiles/Development.dir/main.cpp.o] Error `1
`make[2]: *** [CMakeFiles/Development.dir/all] Error 2`
`make[2]: *** [CMakeFiles/Development.dir/rule] Error 2`

I am working on OS X. My CMakeLists.txt tells me it found the path of the restbed library and include and sets it accordingly. However, I want to note that because I am new and found it to be working for the CMakeLists I cloned restbed into the directory of the project itself. 
I did not post main.cpp as it used the #includes from the example and I am sure <restbed> is fine.

**CMakeLists :**
```
`

cmake_minimum_required(VERSION 3.7)
project(Development)



set(CMAKE_CXX_STANDARD 11)

set(CMAKE_BINARY_DIR "./build")
set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR})
set(LIBRARY_OUTPUT_PATH ${CMAKE_BINARY_DIR})

#Version Number
set(Development_VERSION_MAJOR 1)
set(Development_VERSION_MINOR 0)


find_path( restbed_SOURCE CMakeLists.txt HINTS "${CMAKE_SOURCE_DIR}/restbed" )

if ( restbed_SOURCE )
    set( restbed_FOUND TRUE )
    set( restbed_BUILD "${CMAKE_CURRENT_BINARY_DIR}/restbed_build" )
    set( restbed_DISTRIBUTION "${CMAKE_CURRENT_BINARY_DIR}/distribution" )

    include( ExternalProject )
    ExternalProject_Add( restbed SOURCE_DIR ${restbed_SOURCE}
            PREFIX restbed_build
            INSTALL_DIR ${restbed_DISTRIBUTION}
            CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${restbed_DISTRIBUTION} -DBUILD_SSL=${BUILD_SSL} -DBUILD_SHARED=NO )

    set( restbed_INCLUDE "${restbed_DISTRIBUTION}/include" )
    set( restbed_LIBRARY "${restbed_DISTRIBUTION}/library/${CMAKE_STATIC_LIBRARY_PREFIX}restbed${CMAKE_STATIC_LIBRARY_SUFFIX}" )

    message( STATUS "${Green}Found Restbed include at: ${restbed_SOURCE}${Reset}" )
else ( )
    message( FATAL_ERROR "${Red}Failed to locate Restbed dependency.${Reset}" )
endif ( )


file(GLOB_RECURSE RESTBED_LIBRARY_FILES
        "${RESTBED_LIBRARY_DIR}/*.a"
        )

include_directories(${RESTBED_INCLUDE_DIR})




set(SOURCE_FILES main.cpp)
add_executable(Development ${SOURCE_FILES})

target_link_libraries(Development ${RESTBED_LIBRARY_FILES})
`
```

Thank you in advance!

**Comment by ben-crowhurst** [comment]
@Paaaaaaul Have you tried building it on the command line first? If so what errors appear?

Please provide a complete example.

**Comment by Paaaaaaul** [comment]
Sorry for the late reply, I found my own mistake which occured within the `set (restbed_Distribution "${CMAKE_CURRENT_BINARY_DIR}/distribution")` because it should have been PROJECT_SOURCE_DIR instead. In the end, the path was just wrong and therefor it was not able to find the distribution folder.

I am gonna close this issue

**Comment by ben-crowhurst** [comment]
Ok thanks for letting us know. Good luck.
