### ISSUE TITLE
Graciously stopping service still not available

### ISSUE THREAD

**Issue by Paaaaaaul** [Corvusoft/restbed#226]
I don't want to sound rude there is still no update on how to stop the server the right way for `kill -s SIGTERM <PID>`. All your example shows is that the handlers listening to the signals but in the same example you let your service continue after it received the signal. Furthermore, you cannot change the function parameters of your function to be called when a signal is sent to the program even if its your own because set_signal_handler only takes the SIG and callback function as input, so trying to pass the service object does not work either.

Looking for recommendations, advice how to use Service's function stop() in case of a `kill` command

**Comment by ben-crowhurst** [comment]
Capture the service in the lambda and call service->stop( )?

**Comment by ben-crowhurst** [comment]
I've reopened your previous ticket.
