### ISSUE TITLE
500 Internal Server Error - return regex_error

### ISSUE THREAD

**Issue by T4lus** [Corvusoft/restbed#228]
Hi, 

I have 5 ressources path : 
Universe : /api/universe/{confToken: .*}/{seed: .*}
Galaxy : /api/universe/{confToken: .*}/{universeSeed: .*}/{seed: .*}
Cluster : /api/universe/{confToken: .*}/{universeSeed: .*}/{galaxySeed: .*}/{seed: .*}
Star : /api/universe/{confToken: .*}/{universeSeed: .*}/{galaxySeed: .*}/{clusterSeed: *}/{seed: .*}
Planet : /api/universe/{confToken: .*}/{universeSeed: .*}/{galaxySeed: .*}/{clusterSeed: *}/{starSeed: .*}/{seed: .*}

Universe, Galaxy and Cluster work well but when I'm trying to get on Star or Planet I'm getting `500 Internal Server Error`  and I get `regex_error` on the return body

**Comment by ben-crowhurst** [comment]
A first glance it looks to be a dodgy URL pattern `{clusterSeed: }`.  We'll attempt to replicate your symptoms. In the meantime could you provide a completer server and client example.

**Comment by T4lus** [comment]
Thanks

I forgot the `.` before the `*` in my routing rules
maybe a better error message could be usefull

**Comment by ben-crowhurst** [comment]
What did the regex_error message say?

**Comment by T4lus** [comment]
just `regex_error` showing which rules is faulty can be usefull

**Comment by ben-crowhurst** [comment]
Will look to have the error throw on setting the path.
