### ISSUE TITLE
can not get_port

### ISSUE THREAD

**Issue by dillion007** [Corvusoft/restbed#229]
Uri uri = Uri("http://192.168.11.103:8080/ephod-server/monitoringEquipment/findByPrisonId?prisonId=330382111");
	auto request = make_shared< Request >(uri);

	auto future = Http::async(request, [](const shared_ptr< Request >, const shared_ptr< Response > response)
	{for (const auto header : response->get_headers())
	{
		fprintf(stderr, "Header '%s' = '%s'\n", header.first.data(), header.second.data());
	}

	if (response->has_header("Transfer-Encoding"))
	{
		Http::fetch("\r\n", response);
	}
	else
	{
		auto length = response->get_header("Content-Length", 0);

		Http::fetch(length, response);
		fprintf(stderr, "Body:           %.*s...\n", length, response->get_body().data());
	}
	});

response is 400, then i found it could not get port

	auto host = request->get_host();
        auto port = request->get_port();
        auto path = request->get_path();
	auto query_parameters = request->get_query_parameters();

host, path, query_parameters can get value, but port can not

**Comment by ben-crowhurst** [comment]
Please provide a complete server/client example and will take a look.

**Comment by dillion007** [comment]
#include <memory>
#include <future>
#include <cstdio>
#include <cstdlib>
#include <restbed>

using namespace std;
using namespace restbed;

int main(const int, const char**)
{
	Uri uri = Uri("http://192.168.11.103:8080/ephod-server/monitoringEquipment/findByPrisonId?prisonId=330382111");
	auto request = make_shared< Request >(uri);

	auto future = Http::async(request, [](const shared_ptr< Request >, const shared_ptr< Response > response)
	{for (const auto header : response->get_headers())
	{
		fprintf(stderr, "Header '%s' = '%s'\n", header.first.data(), header.second.data());
	}

	if (response->has_header("Transfer-Encoding"))
	{
		Http::fetch("\r\n", response);
	}
	else
	{
		auto length = response->get_header("Content-Length", 0);

		Http::fetch(length, response);
		fprintf(stderr, "Body:           %.*s...\n", length, response->get_body().data());
	}
	});


	auto path = request->get_path();
	auto port = request->get_port();
	auto authority = request->get_host();
	auto query_parameters = request->get_query_parameters();
	auto scheme = request->get_version();

	getchar();
	return 0;
}

**Comment by dillion007** [comment]
this is client source, server is on the other computer, write by java, and my friend said he can not get query parameters

**Comment by dillion007** [comment]
this is another uri(https://www.bing.com), since no server code

```
#include <memory>
#include <future>
#include <cstdio>
#include <cstdlib>
#include <restbed>

using namespace std;
using namespace restbed;

int main(const int, const char**)
{
	Uri uri = Uri("https://www.bing.com/search?q=cpprestsdk");
	auto request = make_shared< Request >(uri);

	auto future = Http::async(request, [](const shared_ptr< Request >, const shared_ptr< Response > response)
	{
		for (const auto header : response->get_headers())
		{
			fprintf(stderr, "Header '%s' = '%s'\n", header.first.data(), header.second.data());
		}

		if (response->has_header("Transfer-Encoding"))
		{
			Http::fetch("\r\n", response);
		}
		else
		{
			auto length = response->get_header("Content-Length", 0);

			Http::fetch(length, response);
			fprintf(stderr, "Body:           %.*s...\n", length, response->get_body().data());
		}
	});


	auto path = request->get_path();
	uint16_t iPort = request->get_port();
	auto authority = request->get_host();
	auto query_parameters = request->get_query_parameters();
	auto scheme = request->get_version();

	getchar();
	return 0;
}
```

**Comment by ben-crowhurst** [comment]
I'll look into this today and have feedback for you in the next couple of hours.

**Comment by ben-crowhurst** [comment]
Just tried the following with no issues spotted.  I'm afraid the problem seems to be in your code.  Without the complete source to spot your error I can be of very little assistance.

```C++
TEST_CASE( "client fails to calculate correct response body length", "[http]" )
{
	Uri uri = Uri( "https://www.google.com/search?q=passiveAggression" );
	auto request = make_shared< Request >( uri );

	auto future = Http::async( request, [ ]( const shared_ptr< Request >, const shared_ptr< Response > response )
	{
		for ( const auto header : response->get_headers( ) )
		{
			fprintf( stderr, "Header '%s' = '%s'\n", header.first.data( ), header.second.data( ) );
		}

		if ( response->has_header("Transfer-Encoding" ) )
		{
			Http::fetch( "\r\n", response );
		}
		else
		{
			auto length = response->get_header( "Content-Length", 0 );
			Http::fetch( length, response );

			fprintf( stderr, "Body:           %.*s...\n", length, response->get_body( ).data( ) );
		}
	});

	auto path = request->get_path( );
    fprintf( stderr, "path: %s\n", path.data( ) );

	auto port = request->get_port( );
    fprintf( stderr, "port: %d\n", port );

	auto host = request->get_host( );
    fprintf( stderr, "host: %s\n", host.data( ) );

	auto version = request->get_version( );
    fprintf( stderr, "version: %.1f\n", version );

	auto parameters = request->get_query_parameters( );
    for ( auto parameter : parameters )
        fprintf( stderr, "Query parameter %s = %s\n", parameter.first.data( ), parameter.second.data( ) );
}
```

**Output**

> path: /search
> port: 443
> host: www.google.com
> version: 1.1
> Query parameter q = passiveAggression
> Header 'Alt-Svc' = 'quic=":443"; ma=2592000; v="39,38,37,36,35"'
> Header 'Cache-Control' = 'private'
> Header 'Content-Length' = '293'
> Header 'Content-Type' = 'text/html; charset=UTF-8'
> Header 'Date' = 'Thu, 13 Jul 2017 20:33:20 GMT'
> Header 'Location' = 'https://www.google.com.au/search?q=passiveAggression&gws_rd=cr&ei=ENlnWafTCsWl8QXD8oCYCQ'
> Header 'P3P' = 'CP="This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info."'
> Header 'Server' = 'gws'
> Header 'Set-Cookie' = 'NID=107=LpwQOGP_JuNYCRfxDqUkVW4_TGNbRlVn5RzzBAcYUYapJHFOot-k9KfRY4w6m0Kz6-YG4XkSypION-OzY_tHE51jsZ4ywxkMn8CXNEUnoJRdDZizgy8OLJMoST8L8tCw; expires=Fri, 12-Jan-2018 20:33:20 GMT; path=/; domain=.google.com; HttpOnly'
> Header 'X-Frame-Options' = 'SAMEORIGIN'
> Header 'X-XSS-Protection' = '1; mode=block'
> Body:           <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
> <TITLE>302 Moved</TITLE></HEAD><BODY>
> <H1>302 Moved</H1>
> The document has moved
> <A HREF="https://www.google.com.au/search?q=passiveAggression&amp;gws_rd=cr&amp;ei=ENlnWafTCsWl8QXD8oCYCQ">here</A>.
> </BODY></HTML>
> ...
>

**Comment by ben-crowhurst** [comment]
Closing and no response from user.
