### ISSUE TITLE
Please default CMAKE_INSTALL_LIBDIR to 'lib', not 'library'

### ISSUE THREAD

**Issue by yurivict** [Corvusoft/restbed#232]
https://github.com/Corvusoft/restbed/blob/master/CMakeLists.txt#L83

'lib' is a common directory on all UNIX-based systems.

**Comment by ben-crowhurst** [comment]
And other operating systems.

**Comment by aviau** [comment]
This is also an issue in Debian.

I had to create a patch: 

- https://anonscm.debian.org/cgit/collab-maint/restbed.git/tree/debian/patches/usr-lib.patch?id=ace39055565e1c0bb038fda45794bd1c457c4234

**Comment by viohex** [comment]
I write another script to installing into lib not library

**Comment by ben-crowhurst** [comment]
Is the build option `CMAKE_INSTALL_LIBDIR` no sufficient?

**Comment by yurivict** [comment]
It is sufficient, but why force everybody use this option when majority of OSes uses lib?

**Comment by ben-crowhurst** [comment]
Mainly because we get the same argument from developers on other environments.  Happy to hear the build switch is sufficient.

**Comment by ignitenet-martynas** [comment]
Can we then have the default be environment-dependent?

**Comment by ben-crowhurst** [comment]
Please provide a PR with the necessary changes for consideration.

- Linux
- BSD
- Solaris
- Windows
- etc...

**Comment by yurivict** [comment]
I think ```CMAKE_INSTALL_LIBDIR``` should be used. This will close the issue.

**Comment by ben-crowhurst** [comment]
Could you point me in the direction of the documentation for CMAKE_INSTALL_LIBDIR?

**Comment by ben-crowhurst** [comment]
Sorry found the documentation.  It would appear to only support GNU systems, no?

**Comment by yurivict** [comment]
> Sorry found the documentation. It would appear to only support GNU systems, no?

No, it is supported on the FreeBSD which isn't a GNU system.

**Comment by ben-crowhurst** [comment]
And others?  Please understand we have customers that operate across all of the popular OSes.

**Comment by ben-crowhurst** [comment]
It would really help to understand the driving factors behind this change.  What is the problem that will be solved?

**Comment by yurivict** [comment]
What system uses 'library' directory for libraries?

**Comment by ben-crowhurst** [comment]
None of them thats the point.  I can see you have passion for this feature.

> It would really help to understand the driving factors behind this change. What is the problem that will be solved?

**Comment by yurivict** [comment]
make is supposed to be cross-platform. Hard-coded 'library' name is clearly wrong. You should use what cmake offers.

**Comment by yurivict** [comment]
> None of them, thats the point. I can see you have passion for this feature.

Nope. I had to patch away 'library' for the FreeBSD port. Plus, I usually try to get such problems fixed upstream. That's all, no room for passion here.

**Comment by ben-crowhurst** [comment]
https://askubuntu.com/questions/264211/why-do-people-say-make-install-is-bad

**Comment by yurivict** [comment]
> https://askubuntu.com/questions/264211/why-do-people-say-make-install-is-bad

They talk about configure, not cmake.

**Comment by ben-crowhurst** [comment]
@yurivict happy to review a patch that covers all the above mentioned OSes.

**Comment by yurivict** [comment]
> happy to review a patch that covers all the above mentioned OSes.

The problem description should be sufficient for devs to easily fix it.

**Comment by ignitenet-martynas** [comment]
> None of them, thats the point. I can see you have passion for this feature.

Wait, what do you mean "none of them"? On Unix-based systems librestbed is installed in a directory of its own ("library" as opposed to "lib"), apart from the rest of the libraries and most importantly -- in a directory where the dynamic linker isn't looking when executables are being loaded. The workarounds are a) patching restbeds CMakeLists.txt to install to "lib" (what we do here) b) adding special command line switches that specify additional runtime library paths to the linking step of our executable (ugly).

How is that not a problem to be solved?

I think something trivial like
`    if(NOT DEFINED CMAKE_INSTALL_LIBDIR)
        set(CMAKE_INSTALL_LIBDIR "library")
    endif()`
... and then using CMAKE_INSTALL_LIBDIR would preserve backwards compatibility on systems where CMAKE_INSTALL_LIBDIR is not supported (not sure if any) and make the others happy by installing into their "native" library dirs. Am I missing something here?

**Comment by ben-crowhurst** [comment]
We've implemented @ignitenet-martynas suggestion in the 4.7 release branch.
`if(NOT DEFINED CMAKE_INSTALL_LIBDIR)
set(CMAKE_INSTALL_LIBDIR "library")
endif()`
