### ISSUE TITLE
bug about "HTTP response status line malformed:"

### ISSUE THREAD

**Issue by viohex** [Corvusoft/restbed#233]
hello developers:
         I discover a bug of Http component.
         when server return me "HTTP/1.1 200 OK" which as begin line. Http can handle data sucessfully,  but sometimes our server return me "HTTP/1.1 200", the Http throw me an error.
This bug is result from the  RegEx "^([a-zA-Z]+)\\/(\\d*\\.?\\d*) (\\d+) (.+)\\r$" which is locate in file detail/http_impl.cpp:242L. 
       I change the RegEx to  "^([a-zA-Z]+)\\/(\\d*\\.?\\d*) (\\d+) (.*)\\r$"  which can handle "HTTP/1.1 200" successfully like handling "HTTP/1.1 200 OK".
       Thanks the restbed at lastly!

**Comment by ben-crowhurst** [comment]
I'll create a regression test and have this mainlined for the 4.6.1 release.

**Comment by ben-crowhurst** [comment]
I've made the required changes to the client code.  Unfortunately a regression test was easy to create without breaking the behaviour of Restbed.  This would require a hole new release, I've scheduled it for 5.0.

Please validate the fix.
