### ISSUE TITLE
 string_view is only available with C++17

### ISSUE THREAD

**Issue by hujie187** [Corvusoft/restbed#235]
Hi, I try to install restbed on windows with thehelp of the  tutorial in the link [https://github.com/Corvusoft/restbed/issues/17](url)
but in the last step,run cmake give me the following error:

Build FAILED.

"C:\restbed\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\restbed\build\restbed.vcxproj" (default target) (3) ->
(ClCompile target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\string_view(11): fat
al error C1189: #error:  string_view is only available with C++17. [C:\restbed\build\restbed.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\string_view(11): fat
al error C1189: #error:  string_view is only available with C++17. [C:\restbed\build\restbed.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\string_view(11): fat
al error C1189: #error:  string_view is only available with C++17. [C:\restbed\build\restbed.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\string_view(11): fat
al error C1189: #error:  string_view is only available with C++17. [C:\restbed\build\restbed.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\string_view(11): fat
al error C1189: #error:  string_view is only available with C++17. [C:\restbed\build\restbed.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\string_view(11): fat
al error C1189: #error:  string_view is only available with C++17. [C:\restbed\build\restbed.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\string_view(11): fat
al error C1189: #error:  string_view is only available with C++17. [C:\restbed\build\restbed.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\string_view(11): fat
al error C1189: #error:  string_view is only available with C++17. [C:\restbed\build\restbed.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\string_view(11): fat
al error C1189: #error:  string_view is only available with C++17. [C:\restbed\build\restbed.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\string_view(11): fat
al error C1189: #error:  string_view is only available with C++17. [C:\restbed\build\restbed.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\string_view(11): fat
al error C1189: #error:  string_view is only available with C++17. [C:\restbed\build\restbed.vcxproj]

    0 Warning(s)
    11 Error(s)

Can anyone help me the problem?thanks!

**Comment by ben-crowhurst** [comment]
This appears to be an issue with [Microsoft](https://developercommunity.visualstudio.com/content/problem/9696/c17-not-available-by-default.html).

**Comment by ben-crowhurst** [comment]
A workaround `cmake -G "Visual Studio 14 2015 Win64"`

**Comment by ben-crowhurst** [comment]
Unfortunately there is no `/std:c++11` switch

- https://blogs.msdn.microsoft.com/vcblog/2016/06/07/standards-version-switches-in-the-compiler/

**Comment by ben-crowhurst** [comment]
Settings `/std:c++latest` appears to resolve the issue. I'm not sure what the wider implications maybe.

**Comment by ben-crowhurst** [comment]
Unfortunately the tests are now failing, looking into it.

**Comment by hujie187** [comment]
Thank you for you help.I'm planning to try to change my compiler from VS2017 to VS CE2015 and see if it works.

**Comment by ben-crowhurst** [comment]
How did you come along with 2015?

**Comment by hujie187** [comment]
With 2015,the older errors are gone.But it gives 3 new errors，complaining that "ambiguous call to overloaded functions"

**Comment by ben-crowhurst** [comment]
Please supply the error messages.  Our Windows build servers are showing a clean build.

**Comment by hujie187** [comment]
Somehow it compiled succeed with VS 2015. 
The previous error about"ambiguous call to overloaded functions" is familiar to the "Error 2 error C2668" in issue#52[https://github.com/Corvusoft/restbed/issues/52](url).

**Comment by ben-crowhurst** [comment]
I've managed to solve this issue by supplying `/std:c++latest /MT` and building with the following set of commands.

```
cd restbed\dependency\openssl
perl Configure VC-WIN64A
ms\do_win64a
nmake -f ms\ntdll.mak
nmake -f ms\ntdll.mak test
set PATH=restbed\dependency\openssl\out32dll;%PATH%
```

```
cd restbed
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" -DBUILD_EXAMPLES=YES -DBUILD_TESTS=YES ..
cmake --build . --target ALL_BUILD --config Release
ctest
```

- `/std:c++latest` switch forces the system to implement the most current C++ standard.
- `/MT` switch informs the system to have no dependency on VC runtime libraries. 

I'll provide a new build shortly.

**Comment by ben-crowhurst** [comment]
Ok pushed the required changes. Please validate and let me known of any issues.

**Comment by nunojpg** [comment]
Hi,

I fail to understand the reason to hardcode a MT build. What is the reason to not respect MD builds? Both MT and MD were building fine on appveyor :/

Thanks

**Comment by 1bytee** [comment]
In my opinion, MT builds should be available via an option but not forced.

**Comment by ben-crowhurst** [comment]
Please submit a PR with your recommend changes.
