### ISSUE TITLE
Feature request: simple HTTP-request-uri wrapper that transparently handles chunked encoding

### ISSUE THREAD

**Issue by bredelings** [Corvusoft/restbed#236]
Hi,

I apologize if this feature request is not targeted quite right.  Specifically it seems like perhaps it ought to be targeted to 'restless', but its not clear, and also the restless codebase seems to be basically unchanged for some time.  I'm posting this request here because its not clear to me (sorry) how to use both restless and restbed at the same time, and it seems almost possible to handle HTTP 1.1 using restbed alone, so I suspect I'm missing something.

That said, the feature request is basically that restbed (or restless) add a function that takes a URI and just return the content under the assumption that, if the response uses transfer-encoding: chunked that there will be a last chunk.  Based on my (very limited) understanding of HTTP, it seems like hiding content-length and chunked encoding under the hood of a wrapper function is supposed to be possible.

The background is that we (http://www.opentreeoflife.org) are using restbed to construct a new server to implement our web api, and in responding to some of the queries, the server should issue http requests to another server.  So, the flow looks like

client <---> server <---> other server

I'm copying some java code into C++, and that code simply does 

```
URL url = new URL(studyBase + studyId + "?output_nexml2json=1.2.1");
            HttpURLConnection conn = (HttpURLConnection)(url.openConnection());
            if (conn.getResponseCode() == STATUS_OK) {
BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream(), "UTF-8"));
```

I think I understand how to implement https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.4.6 using code from this example here: https://github.com/Corvusoft/restless/blob/master/example/asynchronous_http/source/example.cpp

But, we don't need anything fancy like AIO, so it seems like this would be a helpful part of the official library.  Could this feature be added?  If not, then what approach should we take?

**Comment by ben-crowhurst** [comment]
Hello,

So be clear, you are asking how to perform the HTTP Chunked Transfer-Encoding request-response cycle using Restless and Restbed in concert?

**Comment by bredelings** [comment]
Well, let's say my questions are:

1.  Can I handle Chunked Transfer-Encoding using just restbed?
- Is it possible to create a Session to a specific Uri in restless, or only in restbed?  The chunked examples assume we already have a session, but I don't see how to create one in restbed.
- Alternatively, can we handle chunked transfers with Http::fetch("\r\n", response) followed by Http::fetch(length, response)?

2. If it is not possible to handle this in restbed, then I wonder how to use both restbed and restless together.
- It seems like the restless build process strangely includes restbed inside restless, instead of linking to restbed.

Again, my apologies if I am confused about all these things.

**Comment by ben-crowhurst** [comment]
1. Restbed is able to hand server-side Transfer-Encoding, see examples. Restbed is a server only framework.
2. Restless is pre-1.0 and will have a 1.0 release on 14th August 2017; Breaking API changes are coming.

**Comment by bredelings** [comment]
OK, so it sounds like
1. It is NOT possible (or not supported) to handle Transfer-Encoding as a client using restbed.
2. In order for a server to act as a client, we need to use both restless and restbed simultaneously.
3. We should probably just wait until Aug 14th or so do deal with that.
So I guess the question is indeed:
4. How do you link both restbed and restless into an application?

**Comment by ben-crowhurst** [comment]
Restbed has been extracted out of the Restless library making linking far easier.  We will have an update out this week reflecting that change.  I will leave this ticket open and supply an example showing how to combine both solutions.

**Comment by ben-crowhurst** [comment]
Thanks for your patience.

**Comment by ben-crowhurst** [comment]
5.0 will make the integration of Restbed and Restless far easier, this will be achieved by moving to the std::networking TS.
