### ISSUE TITLE
Installation and Step by step tutorial

### ISSUE THREAD

**Issue by sivapooja** [Corvusoft/restbed#238]
Hi where can i find installation tutorial and step by step learning tutorial? the example is in alphabetical order so i don't know where to start?

**Comment by ben-crowhurst** [comment]
Why not start with the README.md example?

**Comment by sivapooja** [comment]
I am getting error while installing restbed on fedora linux

`
[hanuman@localhost ~]$ git clone --recursive https://github.com/corvusoft/restbed.git
Cloning into 'restbed'...
remote: Counting objects: 13089, done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 13089 (delta 78), reused 114 (delta 41), pack-reused 12917
Receiving objects: 100% (13089/13089), 3.67 MiB | 423.00 KiB/s, done.
Resolving deltas: 100% (8328/8328), done.
Checking connectivity... done.
Submodule 'dependency/asio' (https://github.com/corvusoft/asio-dependency) registered for path 'dependency/asio'
Submodule 'dependency/catch' (https://github.com/corvusoft/catch-dependency) registered for path 'dependency/catch'
Submodule 'dependency/kashmir' (https://github.com/corvusoft/kashmir-dependency) registered for path 'dependency/kashmir'
Submodule 'dependency/openssl' (https://github.com/corvusoft/openssl-dependency) registered for path 'dependency/openssl'
Cloning into '/home/hanuman/restbed/dependency/asio'...
Cloning into '/home/hanuman/restbed/dependency/catch'...
Cloning into '/home/hanuman/restbed/dependency/kashmir'...
Cloning into '/home/hanuman/restbed/dependency/openssl'...
Submodule path 'dependency/asio': checked out 'f5c570826d2ebf50eb38c44039181946a473148b'
Submodule path 'dependency/catch': checked out '8ebe94ca2ea1e6ae7765f65d2f3aec08c9a85ae2'
Submodule path 'dependency/kashmir': checked out '2f3913f49c4ac7f9bff9224db5178f6f8f0ff3ee'
Submodule path 'dependency/openssl': checked out 'a6406c95984a1009f5676bbcf60cc0d6db107af4'
[hanuman@localhost ~]$ mkdir restbed/build
[hanuman@localhost ~]$ cd restbed/build
[hanuman@localhost build]$ cmake -DBUILD_TESTS=YES -DBUILD_EXAMPLES=YES -DBUILD_SSL=NO
**CMake Error: The source directory "/home/hanuman/restbed/build" does not appear to contain CMakeLists.txt.**
Specify --help for usage, or press the help button on the CMake GUI.
`

but the CMakeLists.txt is on the **/home/hanuman/restbed** directory

**Comment by ben-crowhurst** [comment]
You must add `..` to the cmake line.  See the build instructions on the README.md.

```
git clone --recursive https://github.com/corvusoft/restbed.git
mkdir restbed/build
cd restbed/build
cmake [-DBUILD_TESTS=YES] [-DBUILD_EXAMPLES=YES] [-DBUILD_SSL=NO] [-DBUILD_SHARED=YES] [-DCMAKE_INSTALL_PREFIX=/output-directory] ..
make [-j CPU_CORES+1] install
make test
```

**Comment by sivapooja** [comment]
Another error

[hanuman@localhost build]$ make [-j CPU_CORES+1] install
make: *** No rule to make target '[-j'.  Stop.

**Comment by siddharudh** [comment]
Hi Sivapooja,

You shouldn't copy paste the build instructions exactly. Something in brackets means it's an optional argument which you can skip or provide substituting values that suit your system's environment.

For example, if your system has 4 CPU cores, you can run make install as follows:

$ make -j5 install

Or, simply

$ make install

Please learn cmake and make related concepts yourself and avoid bothering the developers unless you feel there's some issue related to restbed library itself.

**Comment by sivapooja** [comment]
Hi i am getting error while compiling test program
`
[hanuman@localhost MyCpp]$ g++  -std=c++11 -g -I /home/hanuman/siva/MyCpp/restbed/distribution/include example.cpp -o example -L/home/hanuman/siva/MyCpp/restbed/distribution/library -lrestbed
/home/hanuman/siva/MyCpp/restbed/distribution/library/librestbed.a(http_impl.cpp.o): In function `restbed::detail::HttpImpl::socket_setup(std::shared_ptr<restbed::Request> const&, std::shared_ptr<restbed::Settings const> const&)':
http_impl.cpp:(.text+0x778): undefined reference to `pthread_condattr_setclock'
/home/hanuman/siva/MyCpp/restbed/distribution/library/librestbed.a(http_impl.cpp.o): In function `asio::execution_context::service* asio::detail::service_registry::create<asio::detail::scheduler, asio::execution_context>(void*)':
http_impl.cpp:(.text._ZN4asio6detail16service_registry6createINS0_9schedulerENS_17execution_contextEEEPNS4_7serviceEPv[_ZN4asio6detail16service_registry6createINS0_9schedulerENS_17execution_contextEEEPNS4_7serviceEPv]+0x93): undefined reference to `pthread_condattr_setclock'
/home/hanuman/siva/MyCpp/restbed/distribution/library/librestbed.a(socket_impl.cpp.o): In function `restbed::detail::SocketImpl::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short, std::function<void (std::error_code const&)> const&)':
socket_impl.cpp:(.text+0x298a): undefined reference to `pthread_create'
socket_impl.cpp:(.text+0x29e9): undefined reference to `pthread_detach'
/home/hanuman/siva/MyCpp/restbed/distribution/library/librestbed.a(socket_impl.cpp.o): In function `asio::detail::resolver_service<asio::ip::tcp>::~resolver_service()':
socket_impl.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED0Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x10d): undefined reference to `pthread_detach'
socket_impl.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED0Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x127): undefined reference to `pthread_join'
socket_impl.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED0Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x14b): undefined reference to `pthread_detach'
/home/hanuman/siva/MyCpp/restbed/distribution/library/librestbed.a(socket_impl.cpp.o): In function `asio::detail::resolver_service<asio::ip::tcp>::shutdown()':
socket_impl.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv]+0x97): undefined reference to `pthread_join'
socket_impl.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv]+0xb3): undefined reference to `pthread_detach'
/home/hanuman/siva/MyCpp/restbed/distribution/library/librestbed.a(socket_impl.cpp.o): In function `asio::detail::resolver_service<asio::ip::tcp>::~resolver_service()':
socket_impl.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED2Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0xfd): undefined reference to `pthread_detach'
socket_impl.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED2Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x117): undefined reference to `pthread_join'
socket_impl.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED2Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x13b): undefined reference to `pthread_detach'
/home/hanuman/siva/MyCpp/restbed/distribution/library/librestbed.a(socket_impl.cpp.o): In function `asio::detail::resolver_service<asio::ip::tcp>::notify_fork(asio::execution_context::fork_event)':
socket_impl.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEE11notify_forkENS_17execution_context10fork_eventE[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEE11notify_forkENS_17execution_context10fork_eventE]+0x70): undefined reference to `pthread_create'
socket_impl.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEE11notify_forkENS_17execution_context10fork_eventE[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEE11notify_forkENS_17execution_context10fork_eventE]+0xcd): undefined reference to `pthread_join'
socket_impl.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEE11notify_forkENS_17execution_context10fork_eventE[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEE11notify_forkENS_17execution_context10fork_eventE]+0x10d): undefined reference to `pthread_detach'
/home/hanuman/siva/MyCpp/restbed/distribution/library/librestbed.a(socket_impl.cpp.o): In function `asio::execution_context::service* asio::detail::service_registry::create<asio::detail::resolver_service<asio::ip::tcp>, asio::io_context>(void*)':
socket_impl.cpp:(.text._ZN4asio6detail16service_registry6createINS0_16resolver_serviceINS_2ip3tcpEEENS_10io_contextEEEPNS_17execution_context7serviceEPv[_ZN4asio6detail16service_registry6createINS0_16resolver_serviceINS_2ip3tcpEEENS_10io_contextEEEPNS_17execution_context7serviceEPv]+0x13c): undefined reference to `pthread_condattr_setclock'
/home/hanuman/siva/MyCpp/restbed/distribution/library/librestbed.a(http.cpp.o): In function `restbed::Http::async(std::shared_ptr<restbed::Request>, std::function<void (std::shared_ptr<restbed::Request>, std::shared_ptr<restbed::Response>)> const&, std::shared_ptr<restbed::Settings const> const&)':
http.cpp:(.text+0x2f09): undefined reference to `pthread_create'
/home/hanuman/siva/MyCpp/restbed/distribution/library/librestbed.a(http.cpp.o): In function `asio::detail::posix_global_impl<asio::system_context>::~posix_global_impl()':
http.cpp:(.text._ZN4asio6detail17posix_global_implINS_14system_contextEED2Ev[_ZN4asio6detail17posix_global_implINS_14system_contextEED5Ev]+0x156): undefined reference to `pthread_join'
http.cpp:(.text._ZN4asio6detail17posix_global_implINS_14system_contextEED2Ev[_ZN4asio6detail17posix_global_implINS_14system_contextEED5Ev]+0x178): undefined reference to `pthread_detach'
collect2: error: ld returned 1 exit status


`

**Comment by siddharudh** [comment]
Add "-lpthread" to your compile command

**Comment by sivapooja** [comment]
Thanks working now

**Comment by sivapooja** [comment]
Hi,
suddenly i am getting error while compiling, yesterday the same command works.
`
[hanuman@localhost MyCpp]$ g++  -std=c++11 -g -I /home/hanuman/siva/MyCpp/restbed/distribution/include myrest.cpp -o myrest -L/home/hanuman/siva/MyCpp/restbed/distribution/library -lrestbed –lpthread

g++: error: –lpthread: No such file or directory

`
