### ISSUE TITLE
Getting error while posting json 

### ISSUE THREAD

**Issue by sivapooja** [Corvusoft/restbed#240]
Hi i am getting 400 bad request error if i post json to my test api. this is my code

`
#include <string>
#include <memory>
#include <cstdlib>
#include <restbed>
#include <fstream>
#include <iomanip>
#include "json.hpp"

using namespace std;
using namespace restbed;
using json = nlohmann::json;

void service_ready_handler( Service& )
{
    fprintf( stderr, "Hey! The service is up and running." );
}

void post_json_method_handler( const shared_ptr< Session > session )
{

	const auto request = session->get_request( );
	int content_length = request->get_header( "Content-Length", 0 );
    

	  session->fetch( content_length, [ ]( const shared_ptr< Session > session, const Bytes & body )
    {
	/*
	string jsonStr = string( body.begin(), body.end() );
	json j = "{ \"happy\": true, \"pi\": 3.141 }"_json;
	std::ofstream o("test.json");
	o << std::setw(2) << j << std::endl; */
        
	const multimap< string, string > headers
    	{
        	//{ "Content-Length", ::to_string(jsonStr.length()) },
		{ "Content-Length", "30" },
        	{ "Content-Type", "application/json" }
    	}; 

        session->close( OK, "{ \"happy\": true, \"pi\": 3.141 }", headers);
    } );
	

    
    
}

void failed_filter_validation_handler( const shared_ptr< Session > session )
{
    session->close( 400 );
}

int main( const int, const char** )
{
    auto resource = make_shared< Resource >( );
    resource->set_path( "/resource" );
    resource->set_failed_filter_validation_handler( failed_filter_validation_handler );
    resource->set_method_handler( "POST", { { "Accept", "application/json" }, { "Content-Type", "application/json" } }, &post_json_method_handler );
    
    auto settings = make_shared< Settings >( );
    settings->set_port( 1984 );
    settings->set_default_header( "Access-Control-Allow-Origin", "*" );
    settings->set_default_header( "Connection", "close" );
    
    
    Service service;
    service.publish( resource );
    service.set_ready_handler( service_ready_handler ); 
    service.start( settings );
    
    return EXIT_SUCCESS;
}

`
Curl command

`

[hanuman@localhost ~]$ curl -w'\n' -v -X POST 'http://192.168.0.34:1984/resource' -H'Accept: application/json' -d '{"username":"siva", "password":"1234"}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.0.34...
* TCP_NODELAY set
* Connected to 192.168.0.34 (192.168.0.34) port 1984 (#0)
> POST /resource HTTP/1.1
> Host: 192.168.0.34:1984
> User-Agent: curl/7.50.3
> Accept: application/json
> Content-Length: 38
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 38 out of 38 bytes
< HTTP/1.1 400 Bad Request
< Access-Control-Allow-Origin: *
< Connection: close
< 
* Curl_http_done: called premature == 0
* Closing connection 0

`

**Comment by ben-crowhurst** [comment]
Did you send a `Content-Type` of `application/json`?
