### ISSUE TITLE
Deploy on tomcat server

### ISSUE THREAD

**Issue by sivapooja** [Corvusoft/restbed#241]
Hi how to deploy the api created with restbed on tomcat web server?

**Comment by ben-crowhurst** [comment]
Why would you want too?

**Comment by sivapooja** [comment]
Because that is customer requirement, must deploy it on tomcat server. so is it possible to deploy restbed api on tomcat server?

**Comment by ben-crowhurst** [comment]
If you're using Restbed in a commercial environment, please contact your support representative for appropriate feedback. 

Remember to quote your CPL license key.
