### ISSUE TITLE
Request->get_body() returns nothing

### ISSUE THREAD

**Issue by hey-fafou** [Corvusoft/restbed#243]
Hi, I am writing a POST method handler:

```
void ApiServer::postRobot(const std::shared_ptr<restbed::Session> session) {
    std::string body;
    body = restbed::String::to_string(session->get_request()->get_body());
    session->close(restbed::OK, body);
}
```

I am sending a simple POST request with "hello" in the body, but I got nothing in the response.

Am I using `get_body()` in a wrong manner ?

Thanks,

Wilfred

**Comment by ben-crowhurst** [comment]
Please see examples for implementation details.

https://github.com/Corvusoft/restbed/blob/master/example/http_service/source/example.cpp
