### ISSUE TITLE
Not entering session->fetch when getting a file

### ISSUE THREAD

**Issue by Headdy44** [Corvusoft/restbed#247]
Hello,
When using postman, I'm trying to upload a file via POST (I tried various types and size), and it won't enter the session->fetch.
If I only send texts, no problem. If there is a file or text and file, it won't work.

It's not throwing any error or displaying anything, it just act as if the session->fetch does not exist.

I'm on a ubuntu 14.04.

void handler_post_user(const std::shared_ptr< Session > session) {

	const auto &request = session->get_request();
	json result;

	auto apiKey = request->get_header(config["apikey_header"].get<std::string>().c_str());
	auto authToken = request->get_header(config["authToken_header"].get<std::string>().c_str());

	size_t content_length = request->get_header("Content-Length", 0);

	std::cout << "CONTENT LENGTH : " << content_length << std::endl;
	std::string bData;
	try {
		session->fetch(content_length, [request](const std::shared_ptr <Session> session, const Bytes &body) {
			std::cout << "entered\n";
			fprintf(stdout, "%d\n", (int) body.size());
			session->close(OK, "Hello, World!", {{"Content-Length", "13"},
			                                     {"Connection",     "keep-alive"}});
		});
		std::cout << "DBG5\n";
	}catch (std::exception &e){
		std::cerr << "SESSION FETCH ERROR" << std::endl;
		std::cerr << e.what();
	}
}

Thanks for looking it up!

**Comment by ben-crowhurst** [comment]
Could you provide the client request being sent?

**Comment by ben-crowhurst** [comment]
Any luck on the over the wire data?

**Comment by Headdy44** [comment]
yep, problem was because I was not doing all my job inside the session fetch, so I was closing the session before the file was transfered. I managed to fetch a file or some datas, but I can't handle when both are send  via POSTMAN form-data. The content-length become 0 or the body is empty. I think the problem come from POSTMAN itself,  and I will check when we will do our form submission via our own applications. In the meanwhile, here's my snippet, for anyone wondering how to handle file and datas.
When the header possess a value for the key "fileName", It will treat it as a file. Otherwise, it will treat it as a form filled with datas.

json file_reception(json result, const Bytes& body){

				char *bData;
				if ((bData = (char*)std::malloc(content_length)) == NULL){
					result["status"] = "err";
					result["err"] = "malloc failed in file reception";
					return result;
				}
				memcpy(bData, body.data(), content_length);
				FILE *pfile;
				std::string filepath = execPath.c_str();
				filepath += "/tmp/" + filename; 
				if ((pfile = fopen(filepath.c_str(), "wb")) == NULL){
					result["status"] = "err";
					result["err"] = "file opening failed in file reception";
					return result;					
				}
				fwrite(bData, sizeof(char), content_length, pfile);
				fclose(pfile);
				result["file"] = "file \"" + filename + "\" received";
				free(bData);
				return result;
}

void handler_post_user(const std::shared_ptr< Session > session) {

	const auto &request = session->get_request();
	auto apiKey = request->get_header(config["apikey_header"].get<std::string>().c_str());
	auto authToken = request->get_header(config["authToken_header"].get<std::string>().c_str());

	std::string filename = request->get_header("fileName", "none");	
	size_t content_length = request->get_header("Content-Length", 0);
	session->fetch(content_length, [request, content_length](const std::shared_ptr<Session> session, const Bytes& body) {
			json result;
		try {
			std::stringstream s;
			json bodyData;
			std::string tmp;
			if (filename != "none"){
				result = file_reception(result, body);
			}else{
				s << body.data();
				std::string bData;
				bData = s.str();
				bodyData = postParser(bData); 
				result["status"] = "ok";
				result["data"] = bodyData;
				if (bodyData.find("dbg") != bodyData.end()){
					std::cout << "DBG : " << std::endl << bodyData << std::endl;
				}else{
					result["users"] = insertRequest(bodyData)["data"];				
				}
			}
			session->close(OK, result.dump(4), {{"Content-Type",   "application/json"},
			                                    {"Content-Length", std::to_string(result.dump(4).length())},
			                                    {"Connection",     "close"}});
			std::cout << "SESSION CLOSED" << std::endl;
		} catch (std::exception &e) {
			std::stringstream message;

			message << "ERROR: fetching bodyData from session Fetch (handle post user):" << std::endl << e.what()
			        << std::endl;
			result["status"] = "err";
			result["message"] = message.str();
			session->close(BAD_REQUEST, result.dump(4), {{"Content-Type",   "application/json"},
			                                             {"Content-Length", std::to_string(result.dump(4).length())}});
			return;
		}
	});
}
