### ISSUE TITLE
Link errors for example.cpp build under RHEL 6.9

### ISSUE THREAD

**Issue by jayb1122** [Corvusoft/restbed#253]
Make Install linking breaks when -DBUILD_EXAMPLES=YES or -DBUILD_TESTS=YES are included with cmake. Make Install without examples or tests works fine. Please help! 

Thanks,
Jay

Build Steps:
	git clone --recursive https://github.com/corvusoft/restbed.git
	mkdir restbed/build
	cd restbed/build
	cmake -DCMAKE_CXX_COMPILER=/usr/local/bin/gcc-6.4.0 -DBUILD_EXAMPLES=YES -DBUILD_SSL=YES -DBUILD_SHARED=YES -DCMAKE_INSTALL_PREFIX=/opt/restbed ..
	make -j 10 install

-- The CXX compiler identification is GNU 6.4.0
-- Check for working CXX compiler: /usr/local/bin/gcc-6.4.0
-- Check for working CXX compiler: /usr/local/bin/gcc-6.4.0 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
   Copyright 2013-2017, Corvusoft Ltd, All Rights Reserved.
-- Found ASIO include at: /share/restbed/dependency/asio/asio/include
-- Found Kashmir include at: /share/restbed/dependency/kashmir
-- Found OpenSSL library at: /usr/lib64/libssl.so
-- Found OpenSSL include at: /usr/include
-- Found Crypto library at: /usr/lib64/libcrypto.so
-- Found PAM include at: /usr/include
-- Found PAM library at: /usr/lib64/libpam.so
-- Found Syslog include at: /usr/include
-- The C compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /share/restbed/build

# make install

. . .     [Link errors go on for pages and pages]

Linking CXX static library librestbed.a
[ 37%] Built target restbed
Scanning dependencies of target authentication
[ 38%] Building CXX object example/CMakeFiles/authentication.dir/authentication/source/example.cpp.o
Linking CXX executable example/authentication
../librestbed.a(service.cpp.o): In function `std::thread::_State_impl<std::_Bind_simple<restbed::Service::start(std::shared_ptr<restbed::Settings const> const&)::{lambda()#2} ()()> >::~_State_impl()':
service.cpp:(.text+0x1c): undefined reference to `std::thread::_State::~_State()'
../librestbed.a(service.cpp.o): In function `_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag.isra.222':
service.cpp:(.text+0x4e): undefined reference to `std::__throw_logic_error(char const*)'
service.cpp:(.text+0xa3): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
../librestbed.a(service.cpp.o): In function `restbed::Service::Service()':
service.cpp:(.text+0x136): undefined reference to `operator new(unsigned long)'
service.cpp:(.text+0x157): undefined reference to `operator delete(void*)'
../librestbed.a(service.cpp.o): In function `restbed::Service::stop()':
service.cpp:(.text+0x288): undefined reference to `std::thread::join()'
service.cpp:(.text+0x380): undefined reference to `operator delete(void*)'
service.cpp:(.text+0x459): undefined reference to `operator delete(void*)'
../librestbed.a(service.cpp.o): In function `restbed::Service::~Service()':
service.cpp:(.text+0x4bd): undefined reference to `__cxa_begin_catch'
service.cpp:(.text+0x4ee): undefined reference to `operator delete(void*)'
service.cpp:(.text+0x4f3): undefined reference to `__cxa_end_catch'
../librestbed.a(service.cpp.o): In function `restbed::Service::get_uptime() const':
. . .

**Comment by ben-crowhurst** [comment]
What is your build environment? compiler version, etc...

**Comment by ben-crowhurst** [comment]
I've confirmed this issue is not present and/or reproducible on `Fedora 29 x64` using the default build instructions.
