### ISSUE TITLE
client receive multiple response from server

### ISSUE THREAD

**Issue by hujiecs** [Corvusoft/restbed#255]
Hi, I'm new to http programming, and for a simple hello world client-server example. I wander if the server handler can send response multiple times, as following:

> void get_handler(const shared_ptr< Session > session)
{
	        for (int i = 0; i < 5; i++) {
		            session->yield(200, "Hello, World!", { { "Content-Length", "13" },{ "Connection", "keep-alive" } });
	        }
}

If the code was right, and the client side is like:

> auto response = Http::sync(request);
	print(response);

how can I receive all the 5 response on the client side?
Thank you very much!

**Comment by AmarOk1412** [comment]
@hujie187 something like

```cpp
while (restbed::Http::is_open(req)) {
    restbed::Http::fetch(13, reply);
    std::string body;
    reply->get_body(body);
    reply->set_body(""); // Reset the body for the next fetch
    std::cout << body < std::endl;
}
```
