### ISSUE TITLE
Is the http_service example inherently multithreaded?

### ISSUE THREAD

**Issue by GlowTube** [Corvusoft/restbed#258]
I'm just learning restbed, basing stuff on http_service.  My situation is that I expect a lot of binary POSTs, doing considerable processing on the data for each one -- making it likely that the processing for consecutive POSTs will overlap.  When post_method_handler is called by the framework with a 'session' parameter, is threading implied -- meaning, if the processing for POST "A" is still in progress when POST "B" arrives, are things ok because POST "B" will occupy a new session?

And if the above is true, how many simultaneous sessions are permitted by the framework?

Thanks!

**Comment by ben-crowhurst** [comment]
Every request is given a new session object.  That is to state no requests will share the same session instance.

By default only one thread of execution is used within the run loop.  If you wish to tailor the multi-threading capabilities you can use [set_worker_limit](https://github.com/Corvusoft/restbed/blob/master/example/multithreaded_service/source/example.cpp)

**Comment by GlowTube** [comment]
Thanks Ben.  Let me confirm that I understand it correctly...

If I put up an http_service and 10 GETs roll in from various IP addresses at almost the same time, all 10 will be given unique sessions because 10 is less than the connection limit of 128.  Of those 10, the first four will execute concurrently because my CPU supports 4 simultaneous threads and I've set the worker_limit to that value.  The 5th one will wait until a thread execution unit is free and then proceed.  Is that right?

Also, do any restbed users try to wrap these services in application-level pthreads to achieve near-concurrency another way?  Application threads are subject to scheduling, true, but you can create so many more of them than the raw concurrency level of the hardware would allow.  Just wondering.

Thanks.

**Comment by ben-crowhurst** [comment]
No, all requests will run concurrently when another blocks performing I/O for example.

Please see [RunLoop Management](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Multithreading/RunLoopManagement/RunLoopManagement.html#//apple_ref/doc/uid/10000057i-CH16-SW1) for a better understanding of how run-loops work.

**Comment by ben-crowhurst** [comment]
@GlowTube may I close this issue?  Do you understand how Restbed is utilizing threads via a run/event loop?

**Comment by katemamba** [comment]
I think what @GlowTube said is correct. I have simple handler with async GET call, and worker limit is set to 8 for my machine. I send 50 requests to the server endpoint at same time and here is the output 

`start########################### {}1542366590163
start########################### {}1542366590163
start########################### {}1542366590163
start########################### {}1542366590163
start########################### {}1542366590163
time########################### {}1542366590164
time########################### {}1542366590164
time########################### {}1542366590164
time########################### {}1542366590164
time########################### {}1542366590164
start########################### {}1542366590165
start########################### {}1542366590165
start########################### {}1542366590165
time########################### {}1542366590188
time########################### {}1542366590188
time########################### {}1542366590188
start########################### {}1542366591108
time########################### {}1542366591109
start########################### {}1542366591114
start########################### {}1542366591116
time########################### {}1542366591116
time########################### {}1542366591117
start########################### {}1542366591121
time########################### {}1542366591122
start########################### {}1542366591126
time########################### {}1542366591127
start########################### {}1542366591134
time########################### {}1542366591135
start########################### {}1542366591146
time########################### {}1542366591148
start########################### {}1542366591159
time########################### {}1542366591160
start########################### {}1542366592030
time########################### {}1542366592032
start########################### {}1542366592038
start########################### {}1542366592038
time########################### {}1542366592039
time########################### {}1542366592039
start########################### {}1542366592046
time########################### {}1542366592047
start########################### {}1542366592081
time########################### {}1542366592082
start########################### {}1542366592090
time########################### {}1542366592092
start########################### {}1542366592103
time########################### {}1542366592105
start########################### {}1542366592119
time########################### {}1542366592121
start########################### {}1542366592961
time########################### {}1542366592962
start########################### {}1542366592998
time########################### {}1542366592999
start########################### {}1542366593006
time########################### {}1542366593007
start########################### {}1542366593010
time########################### {}1542366593011
start########################### {}1542366593014
time########################### {}1542366593015
start########################### {}1542366593045
time########################### {}1542366593046
start########################### {}1542366593053
time########################### {}1542366593054
start########################### {}1542366593061
time########################### {}1542366593062
start########################### {}1542366593913
time########################### {}1542366593915
start########################### {}1542366593923
time########################### {}1542366593924
start########################### {}1542366593960
time########################### {}1542366593961
start########################### {}1542366593964
time########################### {}1542366593965
start########################### {}1542366593966
time########################### {}1542366593967
start########################### {}1542366593968
time########################### {}1542366593969
start########################### {}1542366593974
time########################### {}1542366593975
start########################### {}1542366593983
time########################### {}1542366593985
start########################### {}1542366594875
time########################### {}1542366594877
start########################### {}1542366594883
time########################### {}1542366594885
start########################### {}1542366594888
time########################### {}1542366594890
start########################### {}1542366594891
time########################### {}1542366594893
start########################### {}1542366594896
time########################### {}1542366594897
start########################### {}1542366594933
time########################### {}1542366594934
start########################### {}1542366594946
time########################### {}1542366594947
start########################### {}1542366594960
time########################### {}1542366594961
start########################### {}1542366595806
time########################### {}1542366595807
start########################### {}1542366595847
time########################### {}1542366595848`
 
The time denoted after the print is "start###"(when restbed session lambda is started) and "time###" when restbed session is ending in milliseconds. So here clearly, the 8 starting threads launched simultaneously and then on start### ,time### come one by one. The handler is empty and includes just a print statement. So the difference between start and time for each thread shouldnt be more than 2 miliseconds.

code to reproduce
`end_resource->set_method_handler("GET", std::bind(&Handler::FuncHandler, handler, _1));

FuncHandler(const std::shared_ptr<restbed::Session>& _session)
{
try{
const auto request  = _session->get_request();
        auto content_length = request->get_header("Content-Length", 0);
        _session->fetch(static_cast<size_t>(content_length),
                        [request, this](const std::shared_ptr<restbed::Session> _session,
                                        const restbed::Bytes&) {
           cout<< start####<<time_since_epoch()/miliseconds(0)<<endl;
/// empty func with print
           cout<<time### <<time_since_epoch()/miliseconds(0)<<endl;
}catch(std::exception &ex){
//ex print
}
}
`
@ben-crowhurst please take a look. All requests are not running concurrently.The sample code is pretty much the same and doesnt contain anything other than print statements and returns session.I can give complete reproducible code in a day.
