### ISSUE TITLE
Building with OpenSSL on Windows (VS2017)

### ISSUE THREAD

**Issue by wajsic** [Corvusoft/restbed#261]
I can't seem to get it working on Windows since all guides are written for Linux (make). Does anyone know how to proceed? Managed to get it working without OpenSSL but I'm stuck now,

**Comment by ben-crowhurst** [comment]
See #17  for details.

**Comment by mikim** [comment]
install miniconda3 and it will work smoothly

**Comment by wajsic** [comment]
Is there any chance to build Restbed with OpenSSL completely statically without DLLs needed for OpenSSL

**Comment by ben-crowhurst** [comment]
I'm sure there is a way.  We are in the process of removing direct dependency on any one library so OpenSSL can be switched out for other implementations.

**Comment by ben-crowhurst** [comment]
@wajsic Please pull latest and use the static version of Restbed.  This now has SSL statically linked.   Give it a bash; I'd love any feedback.
