### ISSUE TITLE
Link object to a service?

### ISSUE THREAD

**Issue by AmarOk1412** [Corvusoft/restbed#262]
Hi.

is it possible to link an handler to an object? I don't find any example in the repository.

For example, if I need to call a method on an instance, I can't do a handler like:
```cpp
void
getId(const std::shared_ptr<restbed::Session>& session, const std::shared_ptr<Object>& obj)
{
    const auto request = session->get_request();
    int content_length = std::stoi(request->get_header("Content-Length", "0"));

    session->fetch(content_length,
        [](const std::shared_ptr<restbed::Session> s, const restbed::Bytes& b)
        {
            if (!obj)
              s->close(restbed::OK, "", {{"Content-Length", "0"}});
            auto id = obj->getId().toString(); //obj is a object given by the application
            s->close(restbed::OK, id, {{"Content-Length", std::to_string(id.length())}});
        }
    );
}

//with (for example)
//...
auto o = std::make_shared<Object>();
resource->set_method_handler("GET", getId); // and something here
//...
```

Did I miss something? Can be useful to monitor via HTTP an object in the application which contains a Restbed server and which can be modified by another method.

**Comment by ben-crowhurst** [comment]
This can be achieved with [std::bind](http://en.cppreference.com/w/cpp/utility/functional/bind) and friends.

See [RESTQ](https://github.com/Corvusoft/restq) for an example.

**Comment by AmarOk1412** [comment]
Thanks, I'll try.
