### ISSUE TITLE
session->fetch () is slow when handling the post message

### ISSUE THREAD

**Issue by mikim** [Corvusoft/restbed#264]
I'm testing with handling the post msg.
https://github.com/Corvusoft/restbed/blob/master/example/http_service/source/example.cpp

I noticed that entrance of callback function is slow approx. 1 sec after entrance of post handler with less than 100KB jpg img.

Is there a workaround on this issue?

**Comment by ben-crowhurst** [comment]
Will take a deeper look thanks.

**Comment by ben-crowhurst** [comment]
I don't seem to be experiencing this issue. Can you show how you recorded the 1 sec delay?

**Comment by ben-crowhurst** [comment]
Please note the callback function will not be invoked until all of the data supplied has been flushed down the network socket.  Without further information, I can only assume a low/slow network connection.
