### ISSUE TITLE
Cancel a fetch running in another thread?

### ISSUE THREAD

**Issue by AmarOk1412** [Corvusoft/restbed#271]
Hi,

If in one thread you have something like:

```cpp
restbed::Http::async(req,
   [](const std::shared_ptr<restbed::Request>& req,
      const std::shared_ptr<restbed::Response>& reply) {
      (...)
      while (restbed::Http::is_open(req)) {
          restbed::Http::fetch("\n", reply);
          (...)
      }
  });
```
And if in another thread I call

```cpp
restbed::Http::close(req);
```

the connection is correctly closed, but the fetch will block the first thread to finish (and can't finish, because it will never receives `\n`)

Note: Same result with a timeout

Note2: No problem with server side requests (if you have a weak_ptr on the req)

**Comment by AmarOk1412** [comment]
Ok.

Got a patch. I will make a PR today.

Note: I found another bug linked to this. `Http::fetch()` ignore events like `Http::close`or connection timeout given in Settings (but works for `Session::fetch`). For example:

```cpp
auto settings = std::make_shared<restbed::Settings>();
std::chrono::seconds timeout(10);
settings->set_connection_timeout(timeout);

restbed::Http::async(req,
    [this](const std::shared_ptr<restbed::Request>& req,
             const std::shared_ptr<restbed::Response>& reply) {
    if (code == 200) {
        restbed::Http::fetch("\n", reply); // After 10 seconds, the connection will not be closed.
    }
}, settings);
```

**Comment by ben-crowhurst** [comment]
@AmarOk1412  can this issue be closed now?

**Comment by AmarOk1412** [comment]
Yes. Thx.
