### ISSUE TITLE
Path parameter expected behaviour?

### ISSUE THREAD

**Issue by carlosb** [Corvusoft/restbed#275]
## The problem
Take the following example, where I want to specify whether to get a verbose response or not:

```c++
/**
 * Client Usage:
 *    curl -w'\n' -v -XGET 'http://localhost:1984/resource/verbose?<0 OR 1>'
 */
#include <string>
#include <memory>
#include <cstdlib>
#include <restbed>

using namespace std;
using namespace restbed;

void get_method_handler( const shared_ptr< Session > session )
{
    const auto& request = session->get_request( );
    
    const string body = request->get_path_parameter( "verbose" );
    session->close( OK, body, { { "Content-Length", ::to_string( body.size( ) ) } } );
}

int main( const int, const char** )
{
    auto resource = make_shared< Resource >( );

    resource->set_path( "/resource/verbose?{verbose: (0|1)}" ); // THIS CAUSES THE ERROR

    resource->set_method_handler( "GET", get_method_handler );
    
    auto settings = make_shared< Settings >( );
    settings->set_port( 1984 );
    settings->set_default_header( "Connection", "close" );
    
    Service service;
    service.publish( resource );
    service.start( settings );
    
    return EXIT_SUCCESS;
}
```
When making a request I get the following error:
```
One of *?+{ was not preceded by a valid regular expression.
```
Of course I could just change the path to
```
/resource/verbose/{verbose: (0|1)}
```
and this works, but this defeats my purpose of offering comprehensibility.

## What I've tried

- Escaping with `\?`
- Using `[0-1]` instead of `(0|1)`
- Plainly using `.+`

Each time met with the same error.

I've also tried simply using:
```
/resource/verbose{verbose: .+}
```
to see if I can concatenate strings. For this case, I am met with the following error:
```
The expression contained an invalid range in a {} expression.
```

My two questions:

- Is this intended behaviour?
- Does restbed use the standard library to parse regex?

**Comment by ben-crowhurst** [comment]
We'll start investigating your ticket this week.

**Comment by ben-crowhurst** [comment]
Sorry we haven't got back to you yet.  We will look into this shortly.

**Comment by carlosb** [comment]
Hello, I confused your path parameters with query parameters, which is what I wanted to do all along. So the solution would really be **use query parameters**. I will close the issue.
