### ISSUE TITLE
server send chunked data cannot detect client shut down

### ISSUE THREAD

**Issue by hujiecs** [Corvusoft/restbed#278]
Hi there, I got a problem with restbed.
I wrote a simple server that continuously send a response in chunked encoding,and I use curl as a client. 
The problem is that if client is shut down after sometime, but the Server never knows about it, it keeps sending response. But I tests whether the session is open everytime before I send the response, and it seems not working.
This really confuses me, where is the problem? 

```
void void_callback(const shared_ptr< Session > session) {
}
void post_method_handler(const shared_ptr< Session > session)  
{
       session->yield(OK, "1\r\n\n\r\n", { { "Transfer-Encoding", "chunked" } }, void_callback);
       while (session->is_open()) 
	         session->yield("10\r\nchunked encoding\r\n", void_callback);
}
```

**Comment by ben-crowhurst** [comment]
Please provide a complete server/client example.

**Comment by ben-crowhurst** [comment]
Closing as no further information was provided.
