### ISSUE TITLE
make failure related to architecture x86_64

### ISSUE THREAD

**Issue by brianblakewong** [Corvusoft/restbed#279]
I'm very new to this stuff so I am probably doing something dumb. I am trying to use restbed in a project. My CMakeLists.txt file looks like this:
```
cmake_minimum_required(VERSION 2.8.9)
set (CMAKE_CXX_STANDARD 11)
set(PROJECT_SOURCE_DIR ~/evex)
set(restbed_SOURCE "${PROJECT_SOURCE_DIR}/restbed")

if ( restbed_SOURCE )
    message(found restbed source)
    set(restbed_INCLUDE "${PROJECT_SOURCE_DIR}/restbed/distribution/include")
    set(restbed_LIBRARY "${PROJECT_SOURCE_DIR}/restbed/distribution/library")
endif()

file(GLOB_RECURSE restbed_LIBRARY_FILES "${restbed_LIBRARY}/*.a")

message(${restbed_LIBRARY})
project(tester)
include_directories (${restbed_INCLUDE})
add_executable (tester ../src/test.cc)
target_link_libraries(tester ${restbed_LIBRARY_FILES})
```

When I run `cmake ..` and then `make` I get this error:
```
[ 50%] Linking CXX executable tester
Undefined symbols for architecture x86_64:
  "restbed::Service::start(std::__1::shared_ptr<restbed::Settings const> const&)", referenced from:
      _main in test.cc.o
```
I have tried `cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..` as well but that didn't help.

Potentially relevant: I'm running this on Mac OS X

I appreciate all help!

**Comment by ben-crowhurst** [comment]
Thanks for reporting this.  Have you had any luck with a resolution?

**Comment by ben-crowhurst** [comment]
@brianblakewong I've just validated a build on the following platform.

`Darwin Bens-MacBook-Pro-2.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`

I've discovered no issues.

**Comment by ben-crowhurst** [comment]
Have you managed to resolve your local build issues?

**Comment by brianblakewong** [comment]
Thanks for checking in. Wasn't able to resolve the issue and ended up going with a different library. Sounds like it must have been something weird on my end since you weren't able to reproduce.
