### ISSUE TITLE
multipart/form-data not working

### ISSUE THREAD

**Issue by AlexGrd** [Corvusoft/restbed#280]
Hi. 

I have been trying to send a message using a POST multipart/form-data request but with not success. The parameters and body message is identical with what I send using postman (and in postman the request is ok). 

	auto request = make_shared< Request >(Uri("http://127.0.0.1:8080/ProcessImage"));
	request->set_header("Accept", "*/*");
	request->set_header("Host","127.0.0.1:8080");
	request->set_method("POST");
	request->set_header("Content-Type", "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW");
	request->set_header("Cache-Control", "no-cache");
	string imgContent = "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\n"
		"Content-Disposition: form-data; name=\"image\"\r\n"
		"\r\n"
		"test\r\n"
		"------WebKitFormBoundary7MA4YWxkTrZu0gW--\r\n";
	request->set_body(imgContent
	auto response = Http::sync(request);

Is there a way to see the final raw request message?
Is there something wrong with my implementation or is there any known issues about this topic?

Thank you.

**Comment by ben-crowhurst** [comment]
Please take the time to read the documentation.

```HTTP::to_bytes( request )```

**Comment by wenqf11** [comment]
@AlexGrd  Hi, Alex, I also use restbed to post http multipart form data, just like you mentioned in https://stackoverflow.com/questions/48609620/send-post-multipart-form-data-request-using-restbed-c.  I also got an error 400 bad request, Do you know how to solve it ?

**Comment by AlexGrd** [comment]
@wenqf11 Hey. Unfortunately, if I remember correctly, I didn't find a solution for this problem and ended up using a workaround by modifying the workflow a bit. So I can't really help with this, sry.

**Comment by wenqf11** [comment]
@AlexGrd ok, thanks anyway.
