### ISSUE TITLE
Video streaming example

### ISSUE THREAD

**Issue by GlowTube** [Corvusoft/restbed#282]
When one connects to the URL of an IP camera, the web server inside the camera returns a continuous stream of video frames, usually in MJPEG or H.264 encoding.  I would like to duplicate this behavior with restbed in response to a GET.  I know it’s related to the keep-alive flag, but an example would be great, and I assume I’m not the first with this need.  Is there anything I can study?  BTW I love restbed for short textual GET responses, use it all the time.  Thanks.

**Comment by ben-crowhurst** [comment]
https://en.wikipedia.org/wiki/Chunked_transfer_encoding

**Comment by ben-crowhurst** [comment]
Any luck with your implementation?  Do you still require our assistance?
