### ISSUE TITLE
How to fill data in restbed client? 

### ISSUE THREAD

**Issue by aksnzhy** [Corvusoft/restbed#283]
When using curl we can use -d 'hello world' to set the data. How to do that in restbed client? I didn't see any example. I try to use set_body() but the server just receive an empty body.

**Comment by aksnzhy** [comment]
This problem has been solved by adding

**Comment by aksnzhy** [comment]
But when I call 

session->close(OK, data, {{"Content-Length", to_string(data.size())}});

The body of response in client is empty.

**Comment by ben-crowhurst** [comment]
Please provide a complete example.

**Comment by aksnzhy** [comment]
server code: 

```
 static void post_method_handler(
    const std::shared_ptr<restbed::Session> session) {
    const auto request = session->get_request();
    size_t content_length = request->get_header("Content-Length", 0);
    session->fetch(content_length, 
        [request](
          const std::shared_ptr<restbed::Session>& session, 
          const restbed::Bytes& body) {
      
      // do something get a string data: res_str
     
      session->close(restbed::OK, res_str, 
        {
          {"Content-Length", std::to_string(res_str.size())},
          {"Content-Type", "application/json"},
          {"Connection", "close"}
        });
    });
  }
```

client code:

```
    auto tmp_request = std::make_shared<restbed::Request>(restbed::Uri(uri_.c_str()));
    tmp_request->set_path("/");
    tmp_request->set_method("POST");
    std::string content = request->SerializeToString();
    tmp_request->set_body(content);
    tmp_request->set_header("Content-Length", std::to_string(content.size()));
    tmp_request->set_header("Content-Type", "application/json");
    auto tmp_response = restbed::Http::sync(tmp_request);
    fprintf(stderr, "Body %s\n", tmp_response->get_body().data());
```

 The client code shows Body (Null ).

**Comment by aksnzhy** [comment]
This problem has been solved. I forget to use Http::fetch() .

**Comment by thellaindudhar** [comment]
INFO_16-35-50: 356 {"channelId":5,"ecoSystemId":1,"start_time_utc":"2019-06-18 09:15:16","end_time_utc":"2019-06-18 09:29:16","primaryinput_url":"rtmp://192.168.22.112/live/commet","secondaryinput_url":"rtmp://192.168.2.10:1935/live/myStream","callback_url":"http://192.168.30.193:1252/api/MagicMoments/ndvrInitiatedCallback?callbackjson=","programId":"iretriseries_2019_g5"}�

->In the post response we are getting some extra characters how to resolve it
