### ISSUE TITLE
failed to recieve files with Transfer-Encoding: chunked approach

### ISSUE THREAD

**Issue by buchibabu123** [Corvusoft/restbed#284]
hi i am using restbed framework for the last one year without any issues for receiving JSON data and small image files with this ( restbed/example/http_service/source ) code ,but recently i got  timeout issue from sender side if I send large files, I did some search and found that Transfer-Encoding feature will help to solve it , but with this i am ended up getting more data than the original file , below is the code i am using 

void post_method_handler( const shared_ptr< Session > session )
{
const auto request = session->get_request( );
        if ( request->get_header( "Transfer-Encoding", String::lowercase ) == "chunked" )
        {

                session->fetch( "\r\n", read_chunk_size );
        }
}

void read_chunk_size( const shared_ptr< Session > session, const Bytes& data )
{
        if ( not data.empty( ) )
        {
                const string length( data.begin( ), data.end( ) );

                if ( length not_eq "0\r\n" )
                {
                        const auto chunk_size = stoul( length, nullptr, 16 ) + strlen( "\r\n" );

                        session->fetch( chunk_size, read_chunk );
                        return;
                }
        }

        session->close( OK );

        const auto request = session->get_request( );
        const auto body = request->get_body( );
fprintf( stdout, "[%d]Complete body content: %.*s\n",body.size( ), static_cast< int >( body.size( ) ), body.data( ) );
        syncfs(fd);
        close(fd);

}

void read_chunk( const shared_ptr< Session > session, const Bytes& data )
{
        static bool extra_data = false;

      /*this is to skip first Garbage data  without this i am getting the following data 
--------------------------ae1559b7ca6e5945
Content-Disposition: form-data; name="video"; filename="vector.mp4"
Content-Type: application/octet-stream

*/
        if( extra_data not_eq true ) {
                cout << "Partial body chunk: " << data.size( ) << " bytes" << endl;
                extra_data = true;
                fprintf(stderr,"size == %d\n",data.size());
                fd=open("video.mp4",O_CREAT|O_WRONLY,S_IRWXU|S_IRWXG);
        }
        else{
                write(fd,data.data(),data.size());
}
        session->fetch( "\r\n", read_chunk_size );
}

below is the command i am using for posting Video 

curl -w'\n' -v -X POST --header "Transfer-Encoding: chunked" -F "data=@/home/gaian/Downloads/MCA_Songs.mp4" 'http://localhost:1984/resources'

is there any way i can send large files using restbed ?

Thanks

**Comment by ben-crowhurst** [comment]
Please, can you supply a complete working example?

**Comment by ben-crowhurst** [comment]
I've failed to identify any issue and the original author has gone silent.

If this is still an issue first try the Transfer-Encoding example and reopen if you see a problem, thanks.
