### ISSUE TITLE
Validate Post Body in restbed server

### ISSUE THREAD

**Issue by katemamba** [Corvusoft/restbed#289]
How does restbed handle the validations whether the body sent through post is valid. For example I have a POST request to create a resource FOO, lets say it has following properties 
```
{
"id": "SER1",
"bar":"bar1",
"bar2":"bar3"
}
```
Here all are strings, and body is valid json.
 How does the server handle responses, if one of the required fields is missing, or we have to implement explicitly in handler method for missing required fields or passing number to id, when it expects a string.... I am using rapidjson as json library, does restbed provide this implementation, or we have to use json library validation explicitly for every member and its type?

Ideally this should send a response, which is invalid/bad request, which is easy.

**Comment by ben-crowhurst** [comment]
Hey,
Restbed performs no validation whatsoever.  We played with the idea a while back but realised we'd have to do validation for XML, YAML, JSON, UUEncode, etc...

This is an application level detail.
