### ISSUE TITLE
Can't get directly an ipv6 url.

### ISSUE THREAD

**Issue by AmarOk1412** [Corvusoft/restbed#290]
```cpp
restbed::Uri uri("http://[2001:41d0:303:4814::]/");
auto req = std::make_shared<restbed::Request>(uri);
restbed::Http::async(req,
            [this](const std::shared_ptr<restbed::Request>&,
            const std::shared_ptr<restbed::Response>& reply) {
                auto code = reply->get_status_code();
                // HERE code = 0 instead of 200.
            });
```

`curl http://\[2001:41d0:303:4814::\]/ ` works. The strange thing is that it works with the ipv4 address and if I enter the hostname it will resolve the ipv6 address but I can't enter directly the ipv6 into the url.

@ben-crowhurst any idea?

Have a nice day!

**Comment by ben-crowhurst** [comment]
Right-o, possibly a fault in the Restbed->ASIO integration. I'll dig deeper.

**Comment by AmarOk1412** [comment]
Ok we agree.

If I have some time this week, I'll try to investigate too.

**Comment by ben-crowhurst** [comment]
@AmarOk1412 please see HEAD for a fix.  Thanks for all your help.

**Comment by AmarOk1412** [comment]
Cool :)
