### ISSUE TITLE
RestBed compilation in RHEL7

### ISSUE THREAD

**Issue by limathew** [Corvusoft/restbed#291]
Our development and staging machines are RHEL7 or RHEL6. Whether we could use restbed for these platforms.

The latest gcc available for RHEL7 is gcc/g++ is version 4.8.5 which is below the minimum requirement of "4.9".

Do we have a version of restbed which could be used in RHEL6 and 7 machines? Our applications are in C and C++.

```
$ cmake -DBUILD_TESTS=YES -DBUILD_EXAMPLES=YES -DBUILD_SSL=NO -DBUILD_SHARED=YES -DCMAKE_INSTALL_PREFIX=. ..
CMake Error at cmake/configuration.cmake:26 (message):


  GCC version < 4.9

  Your systems default compiler is GCC.  This project makes use of c++11
  features present only in versions of gcc >= 4.9.  You can use a different
  compiler by re-running cmake with the command switch "-D
  CMAKE_CXX_COMPILER=<compiler>"
Call Stack (most recent call first):
  CMakeLists.txt:22 (include)


-- Configuring incomplete, errors occurred!

```

**Comment by ben-crowhurst** [comment]
I'm afraid not.  Restbed requires a C++11, with all the trimmings, based compiler.
