### ISSUE TITLE
Path names containing forward slashes

### ISSUE THREAD

**Issue by CheyenneForbes** [Corvusoft/restbed#295]
for example, getting:
`folder1/folder2/file.css`
with
`static_resource->set_path( "/{filepath: .*}" );`

I'm getting "resource route not found"

**Comment by ben-crowhurst** [comment]
The incoming request path is split into folders, try:

```C++
resource->set_path( "/{folder1: .*}/{folder2: .*}/{filename: .*}" );
```

or in the resource method callback just get the path from the request.

```C++
request->get_path( );
```

Please read the documentation.

**Comment by CheyenneForbes** [comment]
what if its a case where I dont know the amount of sub folders?

**Comment by ben-crowhurst** [comment]
Please read my original comment.

**Comment by ben-crowhurst** [comment]
Please state the intended purpose.  Are you try'n to allow dynamic paths.

> POST /resources/new folder
> POST /resources/new folder/new folder

**Comment by CheyenneForbes** [comment]
I created a pull request with the feature https://github.com/Corvusoft/restbed/pull/296
