### ISSUE TITLE
Why is HTTPS converted to HTTP? get_protocol and Http:to_bytes

### ISSUE THREAD

**Issue by CheyenneForbes** [Corvusoft/restbed#299]
I'm trying to implement a rule which redirects http to https but get_protocol() is http for https

**Comment by ben-crowhurst** [comment]
HTTPS never appears on the over the wire format.  Please see HTTP related [RFC](https://www.ietf.org/rfc/rfc7231.txt) message format.

**Comment by CheyenneForbes** [comment]
whats your recommended way to implement redirecting all http to https when using restbed?

**Comment by ben-crowhurst** [comment]
I recommend you follow the HTTP  standard, as stated in the RFCs.
