### ISSUE TITLE
CMake Error at cmake/Findcatch.cmake:8 (message):   Failed to locate Catch dependency.

### ISSUE THREAD

**Issue by HerbertKoelman** [Corvusoft/restbed#300]
Hello,

Does anyone know which package is missing ?

When I first run `cmake3 ..`, I was missing `ASIO` and `Catch`.

I installed both packages and the `ASIO` package is now flagged as 'found' but not the `Catch`.

Usefull infos:
- Linux RHEL 7.x86_64
- catch-devel.x86_64 (1.9.6-1.el7) is installed
- asio-devel.x86_64 (1.10.8-1.el7) is installed

**Comment by ben-crowhurst** [comment]
What path is CMake installed at?

**Comment by ben-crowhurst** [comment]
git clone --recursive https://github.com/corvusoft/restbed.git
mkdir restbed/build
cd restbed/build
cmake [-DBUILD_SSL=NO] ..
make install
make test

**Comment by HerbertKoelman** [comment]
Oups, I missed your feed back 8-) 

When your suggested sequence I get:
```
  $ cmake ..
  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.1.0 or higher is required.  You are running version 2.8.12.2
```

Therefore I use cmake3 insteadof cmake. I end up with:
```
$ cmake3 ..
Copyright 2013-2018, Corvusoft Ltd, All Rights Reserved.
-- Found ASIO include at: /usr/include
CMake Error at cmake/Findcatch.cmake:8 (message):
  Failed to locate Catch dependency.
Call Stack (most recent call first):
  CMakeLists.txt:45 (find_package)
```

**Comment by ben-crowhurst** [comment]
Have you followed the instructions as specified in the README?

**Comment by ben-crowhurst** [comment]
Delete the repository (folder) and run

> git clone --recursive https://github.com/corvusoft/restbed.git
> mkdir restbed/build
> cd restbed/build
> cmake [-DBUILD_SSL=NO] ..
> make install
> make test

**Comment by HerbertKoelman** [comment]
I'm behind a corporate firewall, so I downloaded the master branch ZIP (I cannot use git clone ...).

But for the `git clone` command, I did indeed follow the instructions I found in the README. Monday when I arrive at the office, I'll cut an paste your instructions to be super sure :-)

Can the issue be related to the fact that I can't run the `git clone` command ?

I'll let you know

**Comment by HerbertKoelman** [comment]
I've successfully run `cmake ..` on my personal Linux on which I have full access to the web.

It's now building (`make ...`)

How can I be sure that the submodules are indeed in the GitHub's ZIP ?

**Comment by ben-crowhurst** [comment]
The submodules are not apart of the zipped download.  I would recommend you perform a `git clone --recursive https://github.com/corvusoft/restbed.git` and then zip up that file.

Alternatively ensure your preinstalled packages ASIO, OPENSSL, CATCH, etc... are in a visible path when building Restbed.

**Comment by ben-crowhurst** [comment]
Has the issue been resolved @HerbertKoelman?

**Comment by vrusinov** [comment]
I have build failure on my home system and I believe it's because Catch headers are in /usr/include/catch2/ and not in any of the subdirectories.

Now, I can't send a patch due to this project's license, can anyone else include `/usr/include/catch2/` in the list of directories to search?

**Comment by ben-crowhurst** [comment]
@vrusinov I'm curious regarding your interpretation of the project license.  Why are you unable to contribute to an Affero General Public Licensed codebase?

**Comment by vrusinov** [comment]
@ben-crowhurst https://opensource.google/docs/patching/

This project is dual license so I'm also not sure how to handle that.
Note, and I need to stress it: I only used restbed on my personal hardware on my personal time. Though I steel need to follow the above patching policy.

**Comment by ben-crowhurst** [comment]
The cmake build system has had some work done on it within the 4.7 release branch, perhaps this will resolve you issue?

Closing as no clear path on how to resolve the original author's issue.

@vrusinov if you are still having problems please create a PR from your home computer with a fix.
