### ISSUE TITLE
When to use multi-threaded restbed?

### ISSUE THREAD

**Issue by CheyenneForbes** [Corvusoft/restbed#302]
I am trying to understand restbed. When to use use set_worker_limit?

- what type of application would I use it for?
- are there pros and cons?

**Comment by ben-crowhurst** [comment]
We'd recommend setting the thread limit via [hardware_concurrency](http://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency).

**Comment by CheyenneForbes** [comment]
does it allow more connections than when set_worker_limit isnt used?
