### ISSUE TITLE
Make tests optional

### ISSUE THREAD

**Issue by aberaud** [Corvusoft/restbed#304]
On restbed' master, building tests is mandatory, which implies a new mandatory dependency: Catch.

Please keep tests optional like they where before. Restbed is a low-level library to make http requests/servers. It should be almost invisible for developers and have as few dependencies as possible.  Building tests every time makes the build longer and is not necessary (you as restbed developpers should be the only actual users for the tests IMHO).

When building Restbed as part of a larger project, with complex building/packaging rules etc., having to manage a new uncommon dependency is a real hassle.

Many thanks :-)

**Comment by aberaud** [comment]
:-)

There is also the cross-compiling situation, where it's not possible to run the compiled test binaries on the host.

**Comment by juliusza** [comment]
Please reenable -DBUILD_TESTS=NO
Building tests takes ~70% CPU time.

**Comment by ben-crowhurst** [comment]
Yep, we've agreed with @aberaud original argument. Will look to reenable.

**Comment by ben-crowhurst** [comment]
This has now been resolved in the 4.7 release branch.

Thanks for everyone's help.
