### ISSUE TITLE
session->close() method does not work unless thread goes out of the method scope.  

### ISSUE THREAD

**Issue by aliufukyaman** [Corvusoft/restbed#306]
I am trying to implement a simple service-client application with restbed. I encountered something strange when trying to respond to the client with session->close() after getting the request. The session->close() method does not do what it is supposed to immediately when this line is run, it waits the post method handler to be completely finished. Maybe it is a standart for http web sercives but I'm not familiar with services.

What I'm trying is, after getting request, I parse the json data and get whatever I need. After that, I respond to the client and do some staff before leaving the post method handler, but the client does not get response till my stuff ends even though I called session->close() before completing that stuff. Any idea why is this happening and how to approach it? 

The sample code I run is below.

Thanks in advance.

```

void post_method_handler(const shared_ptr< Session > session)
{
	const auto request = session->get_request();

	size_t content_length = request->get_header("Content-Length", 0);
	{
		session->fetch(content_length, [request](const shared_ptr< Session > session, const Bytes & body)
		{
			std::string strBody(body.begin(), body.end());
			std::stringstream ss(strBody);

			boost::property_tree::ptree pt;
			boost::property_tree::read_json(ss, pt);

			std::cout << "Server got request: " << std::endl;
			std::cout << ss.str() << std::endl;

			std::string response = "{\"path\":\"response to client\"}";

			session->close(OK, response, { { "Content-Length", std::to_string(response.size()) }, { "Content-Type", "application/json" }, { "Connection", "close" } });
		});

        	//doing some time consuming stuff here but above line does not send response to the
                //client unless this stuff finishes and thread goes out of scope
		while (true)
		{
			//Some stuff to do here
		}
	}
}

int main()
{
	try
	{
		std::shared_ptr<Resource> resource = std::shared_ptr<Resource>(new Resource());// = make_shared< Resource >();
		resource->set_path("/deneme");
		resource->set_method_handler("POST", post_method_handler);

		auto settings = make_shared< Settings >();
		settings->set_bind_address("10.6.0.178");
		settings->set_port(8097);
	
		Service service;
		service.publish(resource);
		service.start(settings);
	}
	catch (const std::exception&)
	{
		std::cout << "Server could not bind the given address or port" << std::endl;
	}

	return EXIT_SUCCESS;
}
```

**Comment by ben-crowhurst** [comment]
Thanks will take a look.

**Comment by aliufukyaman** [comment]
Thanks @ben-crowhurst , anything figured out?

**Comment by ben-crowhurst** [comment]
Sorry, @aliufukyaman  nothing yet. I'm someone overloaded currently.  Will attempt to have a look this week.

**Comment by katemamba** [comment]
Just another point of view to think on this:
The function parameters stay in scope until scope of function expires.Lets say you add another 
    
        session->fetch()...session->close()
 block after your first block. The function parameter "const shared_ptr< Session > session" still stays in scope until function is there, and session->close() does respond, but session ptr is still available untill void function returns. If you still want the session to end as soon as close is called, you may do 

return session->close(...);

I would suggest not having the stuff in while loop in handler method after session closes. If you are dependent on response of session in this "time consuming stuff", can add it async after response is returned, before session closes. If it is unrelated or not using session ptr, might not as well have it as part of handler .
