### ISSUE TITLE
BUILD ISSUE: Make failed

### ISSUE THREAD

**Issue by srikara123** [Corvusoft/restbed#307]
> user@lpz-user:/u/ee209064/srikar/github/restbed/build$ make
> Scanning dependencies of target restbed-shared
> [  0%] Building CXX object CMakeFiles/restbed-shared.dir/source/corvusoft/restbed/web_socket_message.cpp.o
> In file included from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/web_socket_message_impl.hpp:12:0,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket_message.cpp:10:
> /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.hpp:37:11: warning: base class ‘class std::enable_shared_from_this<restbed::WebSocket>’ has a non-virtual destructor [-Weffc++]
>      class WebSocket : public std::enable_shared_from_this< WebSocket >
>            ^
> [  1%] Building CXX object CMakeFiles/restbed-shared.dir/source/corvusoft/restbed/web_socket.cpp.o
> In file included from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:10:0:
> /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.hpp:37:11: warning: base class ‘class std::enable_shared_from_this<restbed::WebSocket>’ has a non-virtual destructor [-Weffc++]
>      class WebSocket : public std::enable_shared_from_this< WebSocket >
>            ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/conf.h:13:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:20,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/bio.h:668:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
>  DEPRECATEDIN_1_1_0(int BIO_get_port(const char *str, unsigned short *port_ptr))
>  ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:20:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/conf.h:104:1: error: expected constructor, destructor, or type conversion before ‘struct’
>  struct conf_st {
>  ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/asn1.h:24:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/objects.h:916,
>                  from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/evp.h:27,
>                  from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/x509.h:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:50,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/bn.h:291:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_0_9_8’
>  DEPRECATEDIN_0_9_8(int
>  ^
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/bn.h:362:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_0_9_8’
>  DEPRECATEDIN_0_9_8(int BN_get_params(int which)) /* 0, mul, 1 high, 2 low, 3
>  ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/objects.h:916:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/evp.h:27,
>                  from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/x509.h:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:50,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/asn1.h:554:7: error: expected constructor, destructor, or type conversion before ‘unsigned’
>  const unsigned char *ASN1_STRING_get0_data(const ASN1_STRING *x);
>        ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/x509.h:31:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:50,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/rsa.h:198:1: error: expected constructor, destructor, or type conversion before ‘int’
>  int RSA_generate_key_ex(RSA *rsa, int bits, BIGNUM *e, BN_GENCB *cb);
>  ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/dsa.h:31:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/x509.h:32,
>                  from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:50,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/dh.h:141:1: error: expected constructor, destructor, or type conversion before ‘int’
>  int DH_generate_parameters_ex(DH *dh, int prime_len, int generator,
>  ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/x509.h:32:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:50,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/dsa.h:132:1: error: expected constructor, destructor, or type conversion before ‘int’
>  int DSA_generate_parameters_ex(DSA *dsa, int bits,
>  ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:50:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/x509.h:709:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
>  DEPRECATEDIN_1_1_0(ASN1_TIME *X509_CRL_get_nextUpdate(X509_CRL *crl))
>  ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:56:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/hmac.h:31:12: error: expected constructor, destructor, or type conversion before ‘int’
>  /*__owur*/ int HMAC_Init_ex(HMAC_CTX *ctx, const void *key, int len,
>             ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:870:1: error: expected constructor, destructor, or type conversion before ‘typedef’
>  typedef enum {
>  ^
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:908:3: error: ‘OSSL_HANDSHAKE_STATE’ does not name a type
>  } OSSL_HANDSHAKE_STATE;
>    ^
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:1613:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
>  DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *SSLv3_server_method(void)) /* SSLv3 */
>  ^
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:1628:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
>  DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_server_method(void)) /* TLSv1.0 */
>  ^
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/ssl.h:1730:8: error: ‘OSSL_HANDSHAKE_STATE’ does not name a type
>  __owur OSSL_HANDSHAKE_STATE SSL_get_state(const SSL *ssl);
>         ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/engine.h:28:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/rand.h:48:1: error: expected constructor, destructor, or type conversion before ‘void’
>  void RAND_seed(const void *buf, int num);
>  ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/engine.h:30:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/openssl/include/openssl/err.h:248:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_0_0’
>  DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
>  ^
> In file included from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:755:0,
>                  from /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
>                  from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:
> /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp: In constructor ‘asio::ssl::context::context(asio::ssl::context_base::method)’:
> /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:92:29: error: ‘::TLS_method’ has not been declared
>      handle_ = ::SSL_CTX_new(::TLS_method());
>                              ^
> /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:137:29: error: ‘::TLS_method’ has not been declared
>      handle_ = ::SSL_CTX_new(::TLS_method());
>                              ^
> /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:175:29: error: ‘::TLS_method’ has not been declared
>      handle_ = ::SSL_CTX_new(::TLS_method());
>                              ^
> /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:220:29: error: ‘::TLS_method’ has not been declared
>      handle_ = ::SSL_CTX_new(::TLS_method());
>                              ^
> /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:264:29: error: ‘::TLS_method’ has not been declared
>      handle_ = ::SSL_CTX_new(::SSLv23_method());
>                              ^
> /u/ee209064/srikar/github/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:276:29: error: ‘::TLS_method’ has not been declared
>      handle_ = ::SSL_CTX_new(::TLS_method());
>                              ^
> In file included from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:11:0:
> /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp: At global scope:
> /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:48:15: warning: base class ‘class std::enable_shared_from_this<restbed::detail::SocketImpl>’ has a non-virtual destructor [-Weffc++]
>          class SocketImpl : public std::enable_shared_from_this<SocketImpl>
>                ^
> In file included from /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/web_socket.cpp:13:0:
> /u/ee209064/srikar/github/restbed/source/corvusoft/restbed/detail/web_socket_manager_impl.hpp:36:15: warning: base class ‘class std::enable_shared_from_this<restbed::detail::WebSocketManagerImpl>’ has a non-virtual destructor [-Weffc++]
>          class WebSocketManagerImpl : public std::enable_shared_from_this< WebSocketManagerImpl >
>                ^
> make[2]: *** [CMakeFiles/restbed-shared.dir/source/corvusoft/restbed/web_socket.cpp.o] Error 1
> make[1]: *** [CMakeFiles/restbed-shared.dir/all] Error 2
> make: *** [all] Error 2
> ee209064@lpz-ee209064:/u/ee209064/srikar/github/restbed/build$ 
> ee209064@lpz-ee209064:/u/ee209064/srikar/github/restbed/build$ 
> ee209064@lpz-ee209064:/u/ee209064/srikar/github/restbed/build$ 
> ee209064@lpz-ee209064:/u/ee209064/srikar/github/restbed/build$ 
> ee209064@lpz-ee209064:/u/ee209064/srikar/github/restbed/build$

**Comment by ben-crowhurst** [comment]
What is the environment?

**Comment by srikara123** [comment]
Linux, x86_64

**Comment by ben-crowhurst** [comment]
Complier?

**Comment by srikara123** [comment]
GNU C , C++ compiler, with version 4.8

**Comment by ben-crowhurst** [comment]
Your compiler is not C++11 compliant.  Please upgrade to 4.9.

**Comment by CheyenneForbes** [comment]
I have gcc and g++ version 5.5.0 and I still get this problem
I'm on Ubuntu 16.04.4 LTS
