### ISSUE TITLE
Resource deadlock avoided upon stopping server with Control-C

### ISSUE THREAD

**Issue by rayyar** [Corvusoft/restbed#308]
When Restbed server is stopped upon reception of SIGINT stopService(), in turn calls this->stop() causes
following error and sometime the server does not get stopped (kill -9 works).

terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided

We can kill the process with
kill -9 <pid>

Any suggestions. We are cleaning up our classes and resources.

service is started with
  unsigned int numOfThreads = std::thread::hardware_concurrency();

**Comment by ben-crowhurst** [comment]
If you can provide a minimal example which replicates the problem, we'd be happy to take a look.

**Comment by rayyar** [comment]
Start the service in multi-thread environment by adding following code to::startService(int const& port) method.
        unsigned int numOfThreads = std::thread::hardware_concurrency();
        if (numOfThreads == 0) {
           numOfThreads = 1;
        }
        settings->set_worker_limit(numOfThreads);

Stop service after few seconds by Ctrl-C.

Following is the output of minimum test program:
restbed-server/api$ ./testServer
Started "308 service" on IP Address:Port 0.0.0.0:8080
Starting test for 308 service

^CStopping test for 308 service
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
Aborted (core dumped)


I am also attaching tar.gz files. 
[restbed-server_308.tar.gz](https://github.com/Corvusoft/restbed/files/2035595/restbed-server_308.tar.gz)

**Comment by rayyar** [comment]
Any update on this issue?

**Comment by ben-crowhurst** [comment]
Sorry for the delay. I'll attempt to look into this issue this week.

**Comment by rayyar** [comment]
Thanks. Appreciate

**Comment by ben-crowhurst** [comment]
This issue has been resolved in the 4.7 release branch.
