### ISSUE TITLE
ubuntu 16.04

### ISSUE THREAD

**Issue by ScottDolan** [Corvusoft/restbed#312]
I having a lot of difficulties try to make install to work on ubuntu 16.04. 
I have tried all the following tags but, i alway seem to get the same error which seems to be related to the a dependency 
  git checkout  5.0  
  git checkout 4.6 
  git checkout  4.5 
  git checkout  4.5-RC1
  git checkout revert-281-master
  git master

[  0%] Building CXX object CMakeFiles/restbed-static.dir/source/corvusoft/restbed/session.cpp.o
In file included from /home/scott/restbed/source/corvusoft/restbed/session.cpp:10:0:
/home/scott/restbed/source/corvusoft/restbed/session.hpp:44:11: warning: base class ‘class std::enable_shared_from_this<restbed::Session>’ has accessible non-virtual destructor [-Wnon-virtual-dtor]
     class Session : public std::enable_shared_from_this< Session >
           ^
In file included from /home/scott/restbed/source/corvusoft/restbed/session.cpp:13:0:
/home/scott/restbed/source/corvusoft/restbed/web_socket.hpp:37:11: warning: base class ‘class std::enable_shared_from_this<restbed::WebSocket>’ has accessible non-virtual destructor [-Wnon-virtual-dtor]
     class WebSocket : public std::enable_shared_from_this< WebSocket >
           ^
In file included from /home/scott/restbed/dependency/openssl/include/openssl/conf.h:13:0,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:20,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/bio.h:668:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
 DEPRECATEDIN_1_1_0(int BIO_get_port(const char *str, unsigned short *port_ptr))
 ^
In file included from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:20:0,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/conf.h:104:1: error: expected constructor, destructor, or type conversion before ‘struct’
 struct conf_st {
 ^
In file included from /home/scott/restbed/dependency/openssl/include/openssl/asn1.h:24:0,
                 from /home/scott/restbed/dependency/openssl/include/openssl/objects.h:916,
                 from /home/scott/restbed/dependency/openssl/include/openssl/evp.h:27,
                 from /home/scott/restbed/dependency/openssl/include/openssl/x509.h:23,
                 from /home/scott/restbed/dependency/openssl/include/openssl/ssl.h:50,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/bn.h:291:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_0_9_8’
 DEPRECATEDIN_0_9_8(int
 ^
/home/scott/restbed/dependency/openssl/include/openssl/bn.h:362:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_0_9_8’
 DEPRECATEDIN_0_9_8(int BN_get_params(int which)) /* 0, mul, 1 high, 2 low, 3
 ^
In file included from /home/scott/restbed/dependency/openssl/include/openssl/objects.h:916:0,
                 from /home/scott/restbed/dependency/openssl/include/openssl/evp.h:27,
                 from /home/scott/restbed/dependency/openssl/include/openssl/x509.h:23,
                 from /home/scott/restbed/dependency/openssl/include/openssl/ssl.h:50,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/asn1.h:554:7: error: expected constructor, destructor, or type conversion before ‘unsigned’
 const unsigned char *ASN1_STRING_get0_data(const ASN1_STRING *x);
       ^
In file included from /home/scott/restbed/dependency/openssl/include/openssl/x509.h:31:0,
                 from /home/scott/restbed/dependency/openssl/include/openssl/ssl.h:50,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/rsa.h:198:1: error: expected constructor, destructor, or type conversion before ‘int’
 int RSA_generate_key_ex(RSA *rsa, int bits, BIGNUM *e, BN_GENCB *cb);
 ^
In file included from /home/scott/restbed/dependency/openssl/include/openssl/dsa.h:31:0,
                 from /home/scott/restbed/dependency/openssl/include/openssl/x509.h:32,
                 from /home/scott/restbed/dependency/openssl/include/openssl/ssl.h:50,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/dh.h:141:1: error: expected constructor, destructor, or type conversion before ‘int’
 int DH_generate_parameters_ex(DH *dh, int prime_len, int generator,
 ^
In file included from /home/scott/restbed/dependency/openssl/include/openssl/x509.h:32:0,
                 from /home/scott/restbed/dependency/openssl/include/openssl/ssl.h:50,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/dsa.h:132:1: error: expected constructor, destructor, or type conversion before ‘int’
 int DSA_generate_parameters_ex(DSA *dsa, int bits,
 ^
In file included from /home/scott/restbed/dependency/openssl/include/openssl/ssl.h:50:0,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/x509.h:709:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
 DEPRECATEDIN_1_1_0(ASN1_TIME *X509_CRL_get_nextUpdate(X509_CRL *crl))
 ^
In file included from /home/scott/restbed/dependency/openssl/include/openssl/ssl.h:56:0,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/hmac.h:31:12: error: expected constructor, destructor, or type conversion before ‘int’
 /*__owur*/ int HMAC_Init_ex(HMAC_CTX *ctx, const void *key, int len,
            ^
In file included from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:21:0,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/ssl.h:870:1: error: expected constructor, destructor, or type conversion before ‘typedef’
 typedef enum {
 ^
/home/scott/restbed/dependency/openssl/include/openssl/ssl.h:908:3: error: ‘OSSL_HANDSHAKE_STATE’ does not name a type
 } OSSL_HANDSHAKE_STATE;
   ^
/home/scott/restbed/dependency/openssl/include/openssl/ssl.h:1613:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *SSLv3_server_method(void)) /* SSLv3 */
 ^
/home/scott/restbed/dependency/openssl/include/openssl/ssl.h:1628:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_server_method(void)) /* TLSv1.0 */
 ^
/home/scott/restbed/dependency/openssl/include/openssl/ssl.h:1730:8: error: ‘OSSL_HANDSHAKE_STATE’ does not name a type
 __owur OSSL_HANDSHAKE_STATE SSL_get_state(const SSL *ssl);
        ^
In file included from /home/scott/restbed/dependency/openssl/include/openssl/engine.h:28:0,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/rand.h:48:1: error: expected constructor, destructor, or type conversion before ‘void’
 void RAND_seed(const void *buf, int num);
 ^
In file included from /home/scott/restbed/dependency/openssl/include/openssl/engine.h:30:0,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/detail/openssl_types.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context_base.hpp:19,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:23,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/openssl/include/openssl/err.h:248:1: error: expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_0_0’
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
In file included from /home/scott/restbed/dependency/asio/asio/include/asio/ssl/context.hpp:755:0,
                 from /home/scott/restbed/dependency/asio/asio/include/asio/ssl.hpp:18,
                 from /home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:29,
                 from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:
/home/scott/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp: In constructor ‘asio::ssl::context::context(asio::ssl::context_base::method)’:
/home/scott/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:92:29: error: ‘::TLS_method’ has not been declared
     handle_ = ::SSL_CTX_new(::TLS_method());
                             ^
/home/scott/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:137:29: error: ‘::TLS_method’ has not been declared
     handle_ = ::SSL_CTX_new(::TLS_method());
                             ^
/home/scott/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:175:29: error: ‘::TLS_method’ has not been declared
     handle_ = ::SSL_CTX_new(::TLS_method());
                             ^
/home/scott/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:220:29: error: ‘::TLS_method’ has not been declared
     handle_ = ::SSL_CTX_new(::TLS_method());
                             ^
/home/scott/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:264:29: error: ‘::TLS_method’ has not been declared
     handle_ = ::SSL_CTX_new(::SSLv23_method());
                             ^
/home/scott/restbed/dependency/asio/asio/include/asio/ssl/impl/context.ipp:276:29: error: ‘::TLS_method’ has not been declared
     handle_ = ::SSL_CTX_new(::TLS_method());
                             ^
In file included from /home/scott/restbed/source/corvusoft/restbed/session.cpp:16:0:
/home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp: At global scope:
/home/scott/restbed/source/corvusoft/restbed/detail/socket_impl.hpp:48:15: warning: base class ‘class std::enable_shared_from_this<restbed::detail::SocketImpl>’ has accessible non-virtual destructor [-Wnon-virtual-dtor]
         class SocketImpl : public std::enable_shared_from_this<SocketImpl>
               ^
In file included from /home/scott/restbed/source/corvusoft/restbed/session.cpp:20:0:
/home/scott/restbed/source/corvusoft/restbed/detail/web_socket_manager_impl.hpp:36:15: warning: base class ‘class std::enable_shared_from_this<restbed::detail::WebSocketManagerImpl>’ has accessible non-virtual destructor [-Wnon-virtual-dtor]
         class WebSocketManagerImpl : public std::enable_shared_from_this< WebSocketManagerImpl >
               ^
CMakeFiles/restbed-static.dir/build.make:134: recipe for target 'CMakeFiles/restbed-static.dir/source/corvusoft/restbed/session.cpp.o' failed
make[2]: *** [CMakeFiles/restbed-static.dir/source/corvusoft/restbed/session.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/restbed-static.dir/all' failed
make[1]: *** [CMakeFiles/restbed-static.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ben-crowhurst** [comment]
What version of compiler and dependencies are you using?

**Comment by aakshintala** [comment]
@ScottDolan Did you figure out how to work around this? I've got the same issue. :D

**Comment by nickyfow** [comment]
I was able to work around the issue on Ubuntu 16.04 by using the distribution's own OpenSSL package (`sudo apt-get install libssl-dev`) instead of building one with restbed, i.e. the optional `-DBUILD_SSL=NO` hint from `Readme.md`:
```
cd restbed/build
cmake -DBUILD_SSL=NO ..
sudo make install
```

**Comment by arteniioleg** [comment]
I build static library `restbed` and `openssl` using CMake External Project (superbuild)

### `external-projects.cmake`

```cmake
include(GNUInstallDirs)
include(ExternalProject)

if(NOT DEFINED EXTERNAL_PROJECTS_PREFIX)
    set(EXTERNAL_PROJECTS_PREFIX ${CMAKE_BINARY_DIR}/external-projects)
endif()
if(NOT DEFINED EXTERNAL_PROJECTS_INSTALL_PREFIX)
    set(EXTERNAL_PROJECTS_INSTALL_PREFIX ${EXTERNAL_PROJECTS_PREFIX}/installed)
endif()

include(ProcessorCount)
ProcessorCount(CPU_COUNT)
if(CPU_COUNT EQUAL 0)
    set(CPU_COUNT 1)
endif()
math(EXPR CPU_COUNT "${CPU_COUNT} / 2 + 1")

add_custom_target(external_all)
set_target_properties(external_all PROPERTIES EXCLUDE_FROM_ALL TRUE)

ExternalProject_Add(external_openssl
    PREFIX "${EXTERNAL_PROJECTS_PREFIX}"
    GIT_REPOSITORY "https://github.com/openssl/openssl.git"
    GIT_TAG "OpenSSL_1_1_0h"
    CONFIGURE_COMMAND ../external_openssl/config no-shared no-unit-test no-zlib-dynamic --prefix=${EXTERNAL_PROJECTS_INSTALL_PREFIX}
    BUILD_COMMAND make -j ${CPU_COUNT}
    INSTALL_COMMAND make install_sw install_ssldirs
    )
set_target_properties(external_openssl PROPERTIES EXCLUDE_FROM_ALL TRUE)
add_dependencies(external_all external_openssl)

ExternalProject_Add(external_restbed
    PREFIX "${EXTERNAL_PROJECTS_PREFIX}"
    GIT_REPOSITORY "https://github.com/Corvusoft/restbed.git"
    GIT_TAG "df867a858dddc4cf6ca8642da02720bd65ba239a"
    CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=${EXTERNAL_PROJECTS_INSTALL_PREFIX}
    -DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_LIBDIR}
    -ssl_INCLUDE_DIR=${EXTERNAL_PROJECTS_INSTALL_PREFIX}/${CMAKE_INSTALL_INCLUDEDIR}
    )
set_target_properties(external_restbed PROPERTIES EXCLUDE_FROM_ALL TRUE)
add_dependencies(external_restbed external_openssl)
add_dependencies(external_all external_restbed)
```

### `CMakeLists.txt`

```cmake
cmake_minimum_required(VERSION 3.8)

project(demo_project VERSION 1.0.0 LANGUAGES CXX)

include(external-projects.cmake)

link_directories(${EXTERNAL_PROJECTS_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}) # there is no `target_link_directories()`
set(ADDITIONAL_INCLUDE_DIRS $<BUILD_INTERFACE:${EXTERNAL_PROJECTS_INSTALL_PREFIX}/${CMAKE_INSTALL_INCLUDEDIR}>)

add_executable(${PROJECT_NAME} ${CMAKE_SOURCE_DIR}/src/main.cpp)
set_target_properties(${PROJECT_NAME} PROPERTIES CXX_STANDARD 11 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF)

target_include_directories(${PROJECT_NAME} PRIVATE $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/src> ${ADDITIONAL_INCLUDE_DIRS})

find_package(Threads REQUIRED)
set(PROJECT_LIBRARIES
    Threads::Threads # workaround for https://github.com/Corvusoft/restbed/issues/251
    restbed ssl crypto dl)
target_link_libraries(${PROJECT_NAME} PRIVATE ${PROJECT_LIBRARIES})

find_library(LIB_RESTBED NAMES restbed HINTS ${EXTERNAL_PROJECTS_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR})
if(NOT LIB_RESTBED)
    message(AUTHOR_WARNING "Build the `external_all` target then reload cmake.")
endif()
```

**Comment by ben-crowhurst** [comment]
Do you wish to make this a pull request?

**Comment by arteniioleg** [comment]
@ben-crowhurst to refacto CMakeLists.txt to switch OpenSSL from git submodule to Cmake External Project?

**Comment by zhengdian** [comment]
I got the same issue on my own project, check opensslconf.h exists

**Comment by ben-crowhurst** [comment]
We've refactored the CMakeLists.txt build script in the 4.7 release branch.  You can now easily build using the preinstalled OpenSSL but remove the --recursive during git clone.
