### ISSUE TITLE
Rest Framework monitoring/ API Performance

### ISSUE THREAD

**Issue by katemamba** [Corvusoft/restbed#314]
I have been using restbed for my project, having several endpoints on every method from authentication to inserting details, involving all CRUD Operations, and some endpoints are wrapper to other rest endpoints. 

I am in search of some REST performance measuring tool or monitoring dashboard to use with restbed, against all my endpoints and calculate how much time does each endpoint take to process, how many active threads can run for one endpoint, and so on. What do you guys use for such needs?
PS- I am currently using my own timer functions and boost functions in code to test performance and threads accesibility, but runtime execution may change. Is there any thirdparty tool/simpler approach to this, that given a endpoint and some sample data that runs against my endpoints, I should be able to measure its performance/ Or any class in Restbed which handles this.

Thanks in advance.

**Comment by ben-crowhurst** [comment]
https://httpd.apache.org/docs/2.4/programs/ab.html
