### ISSUE TITLE
Compile error, no matching function call. 

### ISSUE THREAD

**Issue by benwarrick** [Corvusoft/restbed#315]
I have the compilation error: /home/engadmin/restbed/source/corvusoft/restbed/string.cpp: In static member function ‘static std::string restbed::String::replace(const string&, const string&, const string&, restbed::String::Option)’:
/home/engadmin/restbed/source/corvusoft/restbed/string.cpp:142:71: error: no matching function for call to ‘regex_replace(const string&, const regex&, const char [4])’
         const auto expression = regex_replace( target, escape, "\\$1" );

I'm on CentOS 7 x86_64 
g++ 4.8.5, which is C++ 11 complete

I also had to use cmake3, and run git clone --recurse-submodules https://github.com/corvusoft/restbed.git to get this far.

**Comment by ben-crowhurst** [comment]
G++4.8 is not C++11 compliant.
