### ISSUE TITLE
WebSocket client

### ISSUE THREAD

**Issue by derekxgl** [Corvusoft/restbed#323]
I'm new to restbed lib. Below link gives an example writing WebSocket server, and a javascript client.  I'm wondering if I can write a websocket client using restbed.
https://github.com/Corvusoft/restbed/blob/master/documentation/example/WEB_SOCKET.md

**Comment by ben-crowhurst** [comment]
We're in the process of moving all client functionality to the Restless project.

**Comment by Chithesus** [comment]
i also want a websocket client using restbed
