### ISSUE TITLE
Session not always detecting that the client has quit

### ISSUE THREAD

**Issue by AmarOk1412** [Corvusoft/restbed#324]
Hi.

I need to provide a minimal code and I will do it later. For now, I just explain the bug:

I use Restbed on one side has a client, and on the other side has a server. 

The connection is configured with:

```cpp
auto settings = std::make_shared<restbed::Settings>();
        settings->set_default_header("Content-Type", "application/json");
        settings->set_default_header("Connection", "keep-alive");
        settings->set_default_header("Access-Control-Allow-Origin", "*");
        std::chrono::milliseconds timeout(std::numeric_limits<int>::max());
        settings->set_connection_timeout(timeout); // there is a timeout, but really huge
```

A client can quit via two ways:

1. Close the client app (ok, the session server side becomes closed)
2. Loose the connection (`session.is_closed()` stay to false, and it's not detected)

Any clue?

**Comment by ben-crowhurst** [comment]
We don't know the status of the connection until we attempt to read/write to the socket. This is the nature of the underlying implementation within the OS.

We can investigate by polling and see if we can't determine its status.

**Comment by AmarOk1412** [comment]
Note: The write operations seems to succeed, so after several write on the socket I still see `session.is_closed()`

**Comment by AmarOk1412** [comment]
@ben-crowhurst After some investigations, in `socket_impl` I configured a `keep-alive` mechanism on the socket.

Draft:

```cpp
uint32_t val = 1;
setsockopt(m_socket->native_handle(), SOL_SOCKET, SO_KEEPALIVE, &val, sizeof(uint32_t));
uint32_t keepint = 10; // seconds
setsockopt(m_socket->native_handle(), SOL_TCP, TCP_KEEPIDLE, &keepint, sizeof(uint32_t));
keepint = 1; // seconds
setsockopt(m_socket->native_handle(), SOL_TCP, TCP_KEEPINTVL, &keepint, sizeof(uint32_t));
uint32_t cnt = 1;
setsockopt(m_socket->native_handle(), SOL_SOCKET, TCP_KEEPCNT, &cnt, sizeof(uint32_t));
```

This is working, after some seconds, I detect that the client has lost the connection.

I will do a patch because it's needed for me and I think it's important to detect that a client has a connectivity failure.

**Comment by AmarOk1412** [comment]
Yeah. The prototype on win/mac os/linux/android/iOS is the same.

**Comment by AmarOk1412** [comment]
I finally did the patch :)

**Comment by AmarOk1412** [comment]
@ben-crowhurst months later, it finally compile everywhere :), sorry for the delay

**Comment by ben-crowhurst** [comment]
@AmarOk1412 pinged you via the PR.  Could you retarget this at 4.7 branch?  Looking to get this release out as soon as humanly possible.

**Comment by ben-crowhurst** [comment]
Issue resolved with recent PR merge.
