### ISSUE TITLE
restbed build error

### ISSUE THREAD

**Issue by wuedidada** [Corvusoft/restbed#328]
restbed/source/corvusoft/restbed/string.cpp:142:96: note:   deduced conflicting types for parameter _Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
         const auto expression = regex_replace( target, escape, "\\$1" );

**Comment by wuedidada** [comment]
error: no matching function for call to ‘regex_replace(const string&, const regex&, const char [4])’

**Comment by wuedidada** [comment]
gcc 4.8?
should upgrade to 4.9?

**Comment by ben-crowhurst** [comment]
Yes please upgrade. Restbed requires a C++11 complier.
