### ISSUE TITLE
Cannot get the complete request URI

### ISSUE THREAD

**Issue by polchky** [Corvusoft/restbed#330]
In the method handler of a given request, it seems that there is no way of retrieving the complete request URI (including query parameters e.g. "?b=1&a=2"), or at least not via the request object.
I need to get the complete URI as it was received, so building it using the request's get_path() and get_query_parameters() methods is not a possibility, since the order of the query parameters does not correspond to the original request. 
Is there any way to achieve this?

**Comment by ben-crowhurst** [comment]
Correct. The HTTP message only contains the path.  You can obtain the destination via the Service class.

```C++
            const std::shared_ptr< const Uri > get_http_uri( void ) const;
            
            const std::shared_ptr< const Uri > get_https_uri( void ) const;
```

**Comment by lazumbra** [comment]
I'm also with the same problem. I want the complete URL but I can only get everything before "?" or any other special character.
For example:
I want to get -> /value/value2/house?num4
but I only can get value/value2/house

I don't know what is happening.

**Comment by polchky** [comment]
I think that's the intended behavior, the path generally does not include the query parameters (after the "?" sign). Could we propose to create the method get_query() and/or get_uri() in the Request object as possible future features?

**Comment by lazumbra** [comment]
Yeah. I DO need this feature.

**Comment by ben-crowhurst** [comment]
Please open a pull request with the desired design.
