### ISSUE TITLE
PATH_PARAMETERS.md Execution maybe invalid?

### ISSUE THREAD

**Issue by shfxxer** [Corvusoft/restbed#332]
in sample,PATH_PARAMETERS.md.

Execution sample is
 curl -w'\n' -v -XGET 'http://localhost:1984/resource/'

but run this command returns
 HTTP/1.1 404 Not Found

the right way to execute is
 curl -w'\n' -v -XGET 'http://localhost:1984/resource/(who cares someting)'

at the beginning,i thought someting may wrong with my tools......sorry for my poor web dev knowledge...

**Comment by ben-crowhurst** [comment]
Thanks will update the documentation.
