### ISSUE TITLE
The branch "5.0" fails to build from source

### ISSUE THREAD

**Issue by abogani** [Corvusoft/restbed#333]
$ git clone --recursive -b 5.0 https://github.com/Corvusoft/restbed.git
Cloning into 'restbed'...
remote: Counting objects: 14109, done.
remote: Total 14109 (delta 0), reused 0 (delta 0), pack-reused 14109
Receiving objects: 100% (14109/14109), 3.89 MiB | 1.98 MiB/s, done.
Resolving deltas: 100% (9107/9107), done.
Submodule 'dependency/protocol' (http://github.com/corvusoft/protocol) registered for path 'dependency/protocol'
Cloning into '/home/alessio/Sources/git-trees/restbed/dependency/protocol'...
warning: redirecting to https://github.com/corvusoft/protocol/
remote: Counting objects: 613, done.        
remote: Total 613 (delta 0), reused 0 (delta 0), pack-reused 613        
Receiving objects: 100% (613/613), 96.92 KiB | 445.00 KiB/s, done.
Resolving deltas: 100% (293/293), done.
Submodule path 'dependency/protocol': checked out '5a0f4e4e90574a301f0d79b1943913218643f7fc'
Submodule 'dependency/network' (https://github.com/corvusoft/network) registered for path 'dependency/protocol/dependency/network'
Cloning into '/home/alessio/Sources/git-trees/restbed/dependency/protocol/dependency/network'...
remote: Counting objects: 461, done.        
remote: Total 461 (delta 0), reused 0 (delta 0), pack-reused 461        
Receiving objects: 100% (461/461), 81.27 KiB | 368.00 KiB/s, done.
Resolving deltas: 100% (221/221), done.
Submodule path 'dependency/protocol/dependency/network': checked out 'fca34df69ade65ecf83d67826b0caa399682bc35'
Submodule 'dependency/core' (https://github.com/corvusoft/core) registered for path 'dependency/protocol/dependency/network/dependency/core'
Submodule 'dependency/runloop' (https://github.com/corvusoft/runloop) registered for path 'dependency/protocol/dependency/network/dependency/runloop'
Cloning into '/home/alessio/Sources/git-trees/restbed/dependency/protocol/dependency/network/dependency/core'...
remote: Counting objects: 174, done.        
remote: Total 174 (delta 0), reused 0 (delta 0), pack-reused 174        
Receiving objects: 100% (174/174), 36.52 KiB | 316.00 KiB/s, done.
Resolving deltas: 100% (67/67), done.
Cloning into '/home/alessio/Sources/git-trees/restbed/dependency/protocol/dependency/network/dependency/runloop'...
remote: Counting objects: 531, done.        
remote: Total 531 (delta 0), reused 0 (delta 0), pack-reused 531        
Receiving objects: 100% (531/531), 90.85 KiB | 384.00 KiB/s, done.
Resolving deltas: 100% (285/285), done.
Submodule path 'dependency/protocol/dependency/network/dependency/core': checked out 'd02313dfcf317cd62190051935b866c2590d1aa9'
Submodule 'dependency/catch' (https://github.com/corvusoft/catch-dependency) registered for path 'dependency/protocol/dependency/network/dependency/core/dependency/catch'
Cloning into '/home/alessio/Sources/git-trees/restbed/dependency/protocol/dependency/network/dependency/core/dependency/catch'...
remote: Counting objects: 19247, done.        
remote: Total 19247 (delta 0), reused 0 (delta 0), pack-reused 19247        
Receiving objects: 100% (19247/19247), 9.16 MiB | 2.10 MiB/s, done.
Resolving deltas: 100% (12948/12948), done.
Submodule path 'dependency/protocol/dependency/network/dependency/core/dependency/catch': checked out '8ebe94ca2ea1e6ae7765f65d2f3aec08c9a85ae2'
Submodule path 'dependency/protocol/dependency/network/dependency/runloop': checked out '237cea3a8ba9357bea4a2b805086bb891a738d2a'
Submodule 'dependency/catch' (https://github.com/corvusoft/catch-dependency) registered for path 'dependency/protocol/dependency/network/dependency/runloop/dependency/catch'
Cloning into '/home/alessio/Sources/git-trees/restbed/dependency/protocol/dependency/network/dependency/runloop/dependency/catch'...
remote: Counting objects: 19247, done.        
remote: Total 19247 (delta 0), reused 0 (delta 0), pack-reused 19247        
Receiving objects: 100% (19247/19247), 9.16 MiB | 2.22 MiB/s, done.
Resolving deltas: 100% (12948/12948), done.
Submodule path 'dependency/protocol/dependency/network/dependency/runloop/dependency/catch': checked out '8ebe94ca2ea1e6ae7765f65d2f3aec08c9a85ae2'
[CMakeOutput.log](https://github.com/Corvusoft/restbed/files/2294240/CMakeOutput.log)

$ mkdir build
$ cd build
$ cmake ..
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Copyright 2013-2018, Corvusoft Ltd, All Rights Reserved.
CMake Error at cmake/Findcore.cmake:11 (message):
  Failed to locate Core dependency, try again after performing: mkdir build;
  cd build; cmake ..; make install
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/alessio/Sources/git-trees/restbed/build/CMakeFiles/CMakeOutput.log".

[CMakeOutput.log](https://github.com/Corvusoft/restbed/files/2294246/CMakeOutput.log)

**Comment by ben-crowhurst** [comment]
5.0 is an experimental branch. We haven't pushed the lasted changes as the API is in flux.

**Comment by mipac** [comment]
hi,
some news about the v5?
regards

**Comment by ben-crowhurst** [comment]
4.7 will be released this February 2020, shortly followed by 4.8 bring ASIO 1.13.0 into the mix. 5.0 will be a ground-up rewrite to enable H2, QUIC and other assorted protocols; due mid-to-late end of 2020.
