### ISSUE TITLE
Memory consumption problem with sending large data arrays

### ISSUE THREAD

**Issue by mehussein** [Corvusoft/restbed#340]
I am trying to send a large data array from a RESTfull C++ application using `restbed` to a server application. I am using `restbed::Http::sync(request, settings)`, where the `request` parameter contains a byte array of size that can exceed 2GB. The application works correctly. However, the memory consumption was unexpectedly high. Upon investigating the heap activity, we found that about 4 copies of the data are created inside the call above.

**Comment by ben-crowhurst** [comment]
Please provide example code.

**Comment by ben-crowhurst** [comment]
I'm sorry I know this isn't the response you will be looking for but we are deprecating and extracting the client code into a separate project so Restbed can concentrate on its core tasks of being a Service framework.

I'm sorry for the long delay in our response.
