### ISSUE TITLE
Processing the Expect 100 header

### ISSUE THREAD

**Issue by GlowTube** [Corvusoft/restbed#341]
My application receives large binary POSTS, and typically the request headers include

`Expect: 100-continue`

I can see this header in the post handler along with the rest of the client headers.  At the moment I am ignoring it, and my clients generously proceed with sending their data after a short delay.  But I'd like to do the right thing here.  So two questions -

(1) From the restbed viewpoint, where's the proper place to detect and process this header?
(2) To be compliant I have to send "100 Continue" and keep the socket open.  Do I do that with a yield()?

Thanks.

**Comment by ben-crowhurst** [comment]
(2) Yes, please see the documentation for an example.

(1) In the method handler or within a rule.
