### ISSUE TITLE
Weird characters when sending a large file through Websocket

### ISSUE THREAD

**Issue by AlbertoCejas** [Corvusoft/restbed#345]
I am trying to send a large file [1] through WebSocket, to a restbed server. However, I just receive weird characters like:
```
>3}20v#a,
4Rqq#ev31-Vr4?3&2/4P)?
fk<#'?|-9vh
8 "`=-)z.{"'
YFS3X<8a"x
Sx
```
If I send a small file, text is properly received. 
If I split the aforementioned large text file in (i. e. 50 Kb) smaller chunks and I send them, text is properly received. 

Thanks in advance

[ [1] - TestFile.txt ](https://github.com/Corvusoft/restbed/files/2460782/testFile.txt)

**Comment by ben-crowhurst** [comment]
example code, please.

**Comment by ben-crowhurst** [comment]
Closing as no further information has been supplied.  If you determine this to still be an issue with the framework please provide a code example we can't fault find.

Thanks.
