### ISSUE TITLE
Windows: Lib file for dll missing

### ISSUE THREAD

**Issue by schoetbi** [Corvusoft/restbed#346]
When building restbed-shared for windows a lib file does not get created. The reason for this is that the marker "__declspec(dllexport)" is missing before type declarations supposed to be exported.

**Comment by ben-crowhurst** [comment]
Please provide a pull-request and will happily merge.

**Comment by ben-crowhurst** [comment]
@schoetbi any update on this issue?  Will perform a few tests prior to 4.7 release but without further information, we can't progress on this issue.

**Comment by schoetbi** [comment]
I had to continue on another project. So I can not work on this right now.
