### ISSUE TITLE
set a ready being used port ,program coredump 

### ISSUE THREAD

**Issue by zhanb** [Corvusoft/restbed#347]
hi,when i  set a  ready being used  like this :
     settings->set_port(8080);
the progream  would coredump,
the error message :  
terminate called after throwing an instance of 'std::system_error'
  what():  bind: Permission denied
Aborted (core dumped)

the core message:
#0  0x00007fd6e1f08989 in raise () from /lib64/libc.so.6
#1  0x00007fd6e1f0a098 in abort () from /lib64/libc.so.6
#2  0x00007fd6e280cd2d in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007fd6e280ad86 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007fd6e280add1 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007fd6e280b039 in __cxxabiv1::__cxa_rethrow () at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:125
#6  0x00007fd6e3334da1 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<asio::basic_socket_acceptor<asio::ip::tcp>, std::allocator<asio::basic_socket_acceptor<asio::ip::tcp> >, asio::io_context&, asio::ip::basic_endpoint<asio::ip::tcp> >(std::_Sp_make_shared_tag, asio::basic_socket_acceptor<asio::ip::tcp>*, std::allocator<asio::basic_socket_acceptor<asio::ip::tcp> > const&, asio::io_context&, asio::ip::basic_endpoint<asio::ip::tcp>&&) () from /home/zhangbo/software/restbed/build/librestbed.so.4
#7  0x00007fd6e33325ef in std::__shared_ptr<asio::basic_socket_acceptor<asio::ip::tcp>, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<asio::basic_socket_acceptor<asio::ip::tcp> >, asio::io_context&, asio::ip::basic_endpoint<asio::ip::tcp> >(std::_Sp_make_shared_tag, std::allocator<asio::basic_socket_acceptor<asio::ip::tcp> > const&, asio::io_context&, asio::ip::basic_endpoint<asio::ip::tcp>&&) () from /home/zhangbo/software/restbed/build/librestbed.so.4
#8  0x00007fd6e332fd98 in std::shared_ptr<asio::basic_socket_acceptor<asio::ip::tcp> >::shared_ptr<std::allocator<asio::basic_socket_acceptor<asio::ip::tcp> >, asio::io_context&, asio::ip::basic_endpoint<asio::ip::tcp> >(std::_Sp_make_shared_tag, std::allocator<asio::basic_socket_acceptor<asio::ip::tcp> > const&, asio::io_context&, asio::ip::basic_endpoint<asio::ip::tcp>&&) () from /home/zhangbo/software/restbed/build/librestbed.so.4
#9  0x00007fd6e332ba98 in std::shared_ptr<asio::basic_socket_acceptor<asio::ip::tcp> > std::allocate_shared<asio::basic_socket_acceptor<asio::ip::tcp>, std::allocator<asio::basic_socket_acceptor<asio::ip::tcp> >, asio::io_context&, asio::ip::basic_endpoint<asio::ip::tcp> >(std::allocator<asio::basic_socket_acceptor<asio::ip::tcp> > const&, asio::io_context&, asio::ip::basic_endpoint<asio::ip::tcp>&&) () from /home/zhangbo/software/restbed/build/librestbed.so.4
#10 0x00007fd6e3328296 in std::shared_ptr<asio::basic_socket_acceptor<asio::ip::tcp> > std::make_shared<asio::basic_socket_acceptor<asio::ip::tcp>, asio::io_context&, asio::ip::basic_endpoint<asio::ip::tcp> >(asio::io_context&, asio::ip::basic_endpoint<asio::ip::tcp>&&) () from /home/zhangbo/software/restbed/build/librestbed.so.4
#11 0x00007fd6e331a1a2 in restbed::detail::ServiceImpl::http_start() () from /home/zhangbo/software/restbed/build/librestbed.so.4
#12 0x00007fd6e338c4ec in restbed::Service::start(std::shared_ptr<restbed::Settings const> const&) () from /home/zhangbo/software/restbed/build/librestbed.so.4

should i use the try catch before service start? But i can not find it in the exmple

**Comment by ben-crowhurst** [comment]
You don't have permission to bind to that port 8080.  Use a port your user has privileges for.
