### ISSUE TITLE
Memory leak on 500 internal server error

### ISSUE THREAD

**Issue by 01e9** [Corvusoft/restbed#348]
We have a resource that creates a chunked file download. We were creating a wrong response and service showed in logs 500 error. Meanwhile on each resource execution RAM was constantly filling with response size == file size ~100Mb.

We fixed the resource to yeld chunked response in right encoding and memory leak stopped.

(Code example soon, maybe)

**Comment by ben-crowhurst** [comment]
Please provide example client/server code to replicate the issue.

**Comment by ben-crowhurst** [comment]
Hello,  would love to have this fixed in the 4.7 release due this month.  Did you ever get a chance on producing a code example to replicate the issue?

If so please reopen this issue and will tackle the problem, thanks.
