### ISSUE TITLE
Compiling with restbed

### ISSUE THREAD

**Issue by glederrey** [Corvusoft/restbed#35]
Hi,

I'm having some troubles compiling your library on linux mint 17.2.. I'm not an expert in C++, especially with third-party libraries.. 

My problem is that I try to compile with librestbed.so and it doesn't work.. I used your example and just changed `#include <restbed>` by `#include </usr/local/lib/restbed/build/librestbed.so>`.. (The restbed folder being in /usr/local/lib/)

Then, I compile the file example.cpp using the command: `g++ -lx/usr/local/lib/restbed/build/librestbed.so example.cpp`

If I do this, I get this error:
`    ^
In file included from test.cpp:3:0:
/usr/local/lib/restbed/build/librestbed.so:33:72: error: expected unqualified-id before ‘!’ token
�0�Hmn��״�ҿ���}�rm!���b���KOOk6+����S&��o͎��-?z��>%a0C�~��
                                                                        ^
In file included from test.cpp:3:0:
/usr/local/lib/restbed/build/librestbed.so:35:140: error: expected unqualified-id before ‘<’ token
 q�
   z,��Y*4��S�/\(�|/��,�xo����C?�j��Jh��Fgv�.�Y�.�ڜ�-q͑�F6�0/�=ݳ�m}��3J:�'11��U�ܐ5���UCo}��f��W�O������3�&}�N��U6�e\��Y�S�v��}�7��Je���,f�j����$�̫�m��<.�1I�s�Z��u԰�&ә�k<F�
                                                                                                                                            ^`
Does anyone have any idea why?? 

Thanks for your answers

**Comment by ben-crowhurst** [comment]
Hi glederrey,  

``` C++
#include </usr/local/lib/restbed/build/librestbed.so>
```

Is not a vaild means on linking a library with a C/C++ based compiler.  Before proceeding any further would you please provide us with the output of the following command.

```
g++ --version
```

**Comment by glederrey** [comment]
Hi,

Okay.. I knew that I was doing something wrong.. 

Here is the output of the command `g++ --version`:

`g++ (Ubuntu 4.9.2-0ubuntu1~14.04) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by glederrey** [comment]
Hi,

I'm a little bit closer now.. I now use a makefile to link the library. Here it is: 

```
ifndef RESTBED_MODULES_PATH
export RESTBED_MODULES_PATH=/usr/local/lib/restbed
endif

INCLUDE = -I"$(RESTBED_MODULES_PATH)/distribution/include"
LIBRARIES = -L"$(RESTBED_MODULES_PATH)/distribution"

CC=gcc
CXX=g++  -Wno-unused-result -std=c++11
RM=rm -f
CPPFLAGS=-c -Wall
LDFLAGS=-g $(INCLUDE)
LDLIBS=$(LIBRARIES)

SOURCES=example.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=example

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(LDFLAGS) $(OBJECTS) -o $@ $(LDLIBS)
    
.cpp.o:
	$(CXX) $(LDFLAGS) $(CPPFLAGS) $< -o $@ $(LDLIBS)

clean:
	$(RM) $(OBJECTS) $(EXECUTABLE)
```

And if I compile using the command `make`, I now have this error:
```
g++  -Wno-unused-result -std=c++11 -g -I"/usr/local/lib/restbed/distribution/include" -c -Wall example.cpp -o example.o -L"/usr/local/lib/restbed/distribution"
g++  -Wno-unused-result -std=c++11 -g -I"/usr/local/lib/restbed/distribution/include" example.o -o example -L"/usr/local/lib/restbed/distribution"
example.o: In function `operator()':
/home/gael/Desktop/restbed-test/example.cpp:20: undefined reference to `restbed::Session::close(int, std::string const&, std::multimap<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
example.o: In function `get_method_handler(std::shared_ptr<restbed::Session> const&)':
/home/gael/Desktop/restbed-test/example.cpp:10: undefined reference to `restbed::Session::get_request() const'
/home/gael/Desktop/restbed-test/example.cpp:13: undefined reference to `restbed::Request::get_header(std::string const&, unsigned long&, unsigned long) const'
/home/gael/Desktop/restbed-test/example.cpp:21: undefined reference to `restbed::Session::fetch(unsigned long, std::function<void (std::shared_ptr<restbed::Session> const&, std::vector<unsigned char, std::allocator<unsigned char> > const&)> const&)'
example.o: In function `main':
/home/gael/Desktop/restbed-test/example.cpp:27: undefined reference to `restbed::Resource::set_path(std::string const&)'
/home/gael/Desktop/restbed-test/example.cpp:28: undefined reference to `restbed::Resource::set_method_handler(std::string const&, std::function<void (std::shared_ptr<restbed::Session> const&)> const&)'
/home/gael/Desktop/restbed-test/example.cpp:31: undefined reference to `restbed::Settings::set_port(unsigned short)'
/home/gael/Desktop/restbed-test/example.cpp:32: undefined reference to `restbed::Settings::set_default_header(std::string const&, std::string const&)'
/home/gael/Desktop/restbed-test/example.cpp:34: undefined reference to `restbed::Service::Service()'
/home/gael/Desktop/restbed-test/example.cpp:35: undefined reference to `restbed::Service::publish(std::shared_ptr<restbed::Resource const> const&)'
/home/gael/Desktop/restbed-test/example.cpp:36: undefined reference to `restbed::Service::start(std::shared_ptr<restbed::Settings const> const&)'
/home/gael/Desktop/restbed-test/example.cpp:34: undefined reference to `restbed::Service::~Service()'
/home/gael/Desktop/restbed-test/example.cpp:34: undefined reference to `restbed::Service::~Service()'
example.o: In function `_ZN9__gnu_cxx13new_allocatorIN7restbed8ResourceEE9constructIS2_IEEEvPT_DpOT0_':
/usr/include/c++/4.9/ext/new_allocator.h:120: undefined reference to `restbed::Resource::Resource()'
example.o: In function `_ZN9__gnu_cxx13new_allocatorIN7restbed8SettingsEE9constructIS2_IEEEvPT_DpOT0_':
/usr/include/c++/4.9/ext/new_allocator.h:120: undefined reference to `restbed::Settings::Settings()'
collect2: error: ld returned 1 exit status
make: *** [example] Error 1
```

**Comment by ben-crowhurst** [comment]
Please try the following
```
g++  -Wno-unused-result -std=c++11 -g -I"/usr/local/lib/restbed/distribution/include" example.o -o example -L"/usr/local/lib/restbed/distribution/library" -lrestbed
```

G++ linking [options](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html)

**Comment by glederrey** [comment]
Hi,

I just changed a little bit the makefile like this:

```
ifndef RESTBED_MODULES_PATH
export RESTBED_MODULES_PATH=/usr/local/lib/restbed
endif

INCLUDE = -I"$(RESTBED_MODULES_PATH)/distribution/include/"
LIBRARIES = -L"$(RESTBED_MODULES_PATH)/distribution/library" -lrestbed

CC=gcc
CXX=g++  -Wno-unused-result -std=c++11
RM=rm -f
CPPFLAGS=-c -Wall
LDFLAGS=-g $(INCLUDE)
LDLIBS=-g $(LIBRARIES)

SOURCES=example.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=example

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(LDFLAGS) $(OBJECTS) -o $@ $(LDLIBS)
    
.cpp.o:
	$(CXX) $(LDFLAGS) $(CPPFLAGS) $< -o $@ $(LDLIBS)

clean:
	$(RM) $(OBJECTS) $(EXECUTABLE)
```

And it compile now.. But I still have a problem when I try to run the program: 
```
gael@mint-gael ~/Desktop/restbed-test $ ./example
./example: error while loading shared libraries: librestbed.so: cannot open shared object file: No such file or directory
```

If I try your command, it says: 
`g++: error: example.o: No such file or directory`

**Comment by ben-crowhurst** [comment]
Please [set-up](https://help.ubuntu.com/community/EnvironmentVariables#A.2BAC8-etc.2BAC8-environment) your Linux environment with:

LD_LIBRARY_PATH="/usr/local/lib/restbed/distribution/library"

**Comment by glederrey** [comment]
It worked!! Thank you so much!! 

If I can suggest you something, it would be really great if you can add an example of a Makefile or the command to compile your library.. It would prevent having some issues like mine.. =)

Thanks a lot again..

**Comment by ben-crowhurst** [comment]
Will look into creating a template.

We love hearing how people are using Restbed.  What awesome project are you building?

**Comment by glederrey** [comment]
I'm working for a company called nViso.. We work on analysing faces to detect emotions.. If you want more information, you can take a look at our website: http://nviso.ch/.. And we're using restbed because we have a REST API for our product.. 

Thanks again for your help..

I give you my Makefile if you want to start with this:

```
### WARNING: If librestbed.so cannot be found, use the foloowing command: 
###
### export LD_LIBRARY_PATH=/usr/local/lib/restbed/distribution/library
###

ifndef RESTBED_MODULES_PATH
export RESTBED_MODULES_PATH=/usr/local/lib/restbed
endif

INCLUDE = -I"$(RESTBED_MODULES_PATH)/distribution/include/"
LIBRARIES = -L"$(RESTBED_MODULES_PATH)/distribution/library" -lrestbed

CC=gcc
CXX=g++  -Wno-unused-result -std=c++11 -fuse-ld=bfd
RM=rm -f
CPPFLAGS=-c -Wall
LDFLAGS=-g $(INCLUDE)
LDLIBS=$(LIBRARIES)

SOURCES=example.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=example

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(LDFLAGS) $(OBJECTS) -o $@ $(LDLIBS)
    
.cpp.o:
	$(CXX) $(LDFLAGS) $(CPPFLAGS) $< -o $@ $(LDLIBS)

clean:
	$(RM) $(OBJECTS) $(EXECUTABLE)
```

**Comment by ben-crowhurst** [comment]
Exciting stuff, we wish you all the best.  If you require any further help don't hesitate to contact the team.
