### ISSUE TITLE
Memory leak on sending large data using Http::Sync

### ISSUE THREAD

**Issue by abhishek2197** [Corvusoft/restbed#351]
I am currently sending across data of size 800MB using the Http::Sync method. I visualized the memory consumption using the massif-visualizer tool. The results show a peak of 2.9 GB. I have attached a screenshot displaying the functions resulting in memory usage and the code snippet for sending the POST request.

```
#include <memory>
#include <cstdlib>
#include <restbed>
#include <fstream>
#include <string>
#include <iostream>
#include <bits/stdc++.h>
using namespace std;
using namespace restbed;


int main( const int, const char** )
{
    auto request = std::make_shared<restbed::Request>();
    request->set_host("127.0.0.1");
    request->set_method("POST");
    request->set_path( "/resource" );
    std::string content(800000000,'0');
    request->set_headers({
                {"Accept", "application/json"},
                {"Content-Length", std::to_string(content.size())},
                {"Content-Type", "application/octet-stream"}
    }); 

    request->set_body(content);
    auto settings = std::make_shared<restbed::Settings>();
    settings->set_connection_timeout(std::chrono::seconds(60));
    auto response = restbed::Http::sync(request, settings);
    int status_code = response->get_status_code();
    std::cout<<status_code<<std::endl;
    if (status_code != 0){
	std::cout<<"Successful upload"<<std::endl;
    }
    return EXIT_SUCCESS;
} 
```
Massif-visualizer output
![image](https://user-images.githubusercontent.com/21234147/48163018-6b1e0700-e293-11e8-9d53-bd74a21bcfb6.png)

**Comment by ben-crowhurst** [comment]
I'm sorry I know this isn't the response you will be looking for but we are deprecating and extracting the client code into a separate project so Restbed can concentrate on its core tasks of being a Service framework.

I'm sorry for the long delay in our response.
