### ISSUE TITLE
http::fetch is very slow when get data from localhost server

### ISSUE THREAD

**Issue by DianmingHou** [Corvusoft/restbed#353]
I start a web server on my own computer, it provides RESTful services externally, then I provide a client program to get all the data returned by a certain RESTful service of the web server through the Http::fetch method. The entire while loop takes about time. 10 seconds. However, I can get it in one second with the POSTMAN software.

`void RestController::GetResponseBody(std::shared_ptr<restbed::Request> request, std::shared_ptr<restbed::Response> response, std::string &responseBody)  `
`  {`  
	`if (response->get_header("Transfer-Encoding", String::lowercase) == "chunked") {  `
`		while (restbed::Http::is_open(request)) {  `
`			try {  `
`				Bytes fetchStr = Http::fetch("\r\n", response);  `
`			}  `
`			catch (std::runtime_error& e) {  `
`				// Ignore this, operation aborted  `
`			}  `
`		}  `
`		std::string undecodeString;  `
`		response->get_body(undecodeString);  `
`	}  `
`	else if (response->has_header("Content-Length"))  `
`	{  `
`		auto length = response->get_header("Content-Length", 0);  `
`		Http::fetch(length, response);  `
`		response->get_body(responseBody);  `
`	}  `
`	else {  `
`		throw std::runtime_error("response header error :Transfer-Encoding not chunked or Content-Length!");  `
`	}  `
`}`

Is the way I use it incorrect?

**Comment by ben-crowhurst** [comment]
I'm sorry I know this isn't the response you will be looking for but we are deprecating and extracting the client code into a separate project so Restbed can concentrate on its core tasks of being a Service framework.

I'm sorry for the long delay in our response.
