### ISSUE TITLE
Need Minimalistic example on how restbed handles c10k problem

### ISSUE THREAD

**Issue by katemamba** [Corvusoft/restbed#356]
The examples are well documented, and the same isnt the case on how restbed handles c10k problem. An outline example with sample endpoint and handler which solves the 10k problem in async mode will greatly help to understand this better. I tried this earlier using example from example directory,but I feel it isnt happening as expected.

 I use grequests(python) to send out 8k GET concurrent requests. For "https://www.google.com" it takes about a second to proccess all requests. For local restbed server, it takes forever.

Also a way on how you perform tests for c10k problem would be good.

**Comment by ben-crowhurst** [comment]
Do you have a code example of your implementation?

**Comment by ben-crowhurst** [comment]
Closing as author inactive/not responsive.
