### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by jacksu** [Corvusoft/restbed#359]
I clone the new code,but can not compile.The error is fllow:

[  0%] Building CXX object CMakeFiles/restbed-shared.dir/source/corvusoft/restbed/string.cpp.o
/home/ubuntu/sunny/restbed/source/corvusoft/restbed/string.cpp: In static member function ‘static std::string restbed::String::replace(const string&, const string&, const string&, restbed::String::Option)’:
/home/ubuntu/sunny/restbed/source/corvusoft/restbed/string.cpp:142:71: error: no matching function for call to ‘regex_replace(const string&, const regex&, const char [4])’
         const auto expression = regex_replace( target, escape, "\\$1" );
                                                                       ^
/home/ubuntu/sunny/restbed/source/corvusoft/restbed/string.cpp:142:71: note: candidates are:
In file included from /usr/include/c++/4.8/regex:62:0,
                 from /home/ubuntu/sunny/restbed/source/corvusoft/restbed/string.cpp:6:
/usr/include/c++/4.8/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
/home/ubuntu/sunny/restbed/source/corvusoft/restbed/string.cpp:142:71: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [4]’
         const auto expression = regex_replace( target, escape, "\\$1" );
                                                                       ^
In file included from /usr/include/c++/4.8/regex:62:0,
                 from /home/ubuntu/sunny/restbed/source/corvusoft/restbed/string.cpp:6:
/usr/include/c++/4.8/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
/home/ubuntu/sunny/restbed/source/corvusoft/restbed/string.cpp:142:71: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
         const auto expression = regex_replace( target, escape, "\\$1" );
                                                                       ^
make[2]: *** [CMakeFiles/restbed-shared.dir/source/corvusoft/restbed/string.cpp.o] Error 1
make[1]: *** [CMakeFiles/restbed-shared.dir/all] Error 2
make: *** [all] Error 2

**Comment by zhanb** [comment]
need gcc 4.9
