### ISSUE TITLE
Did this compile correctly? 

### ISSUE THREAD

**Issue by benwarrick** [Corvusoft/restbed#361]
Hello, can you tell me if it looks like restbed compiled correctly? The tests run 100%, but this is how the /usr/local directory looks: 

```
ben@VMDebian2:/usr/local$ tree include lib library
include
├── corvusoft
│   └── restbed
│       ├── byte.hpp
│       ├── common.hpp
│       ├── context_placeholder_base.hpp
│       ├── context_placeholder.hpp
│       ├── context_value.hpp
│       ├── http.hpp
│       ├── logger.hpp
│       ├── request.hpp
│       ├── resource.hpp
│       ├── response.hpp
│       ├── rule.hpp
│       ├── service.hpp
│       ├── session.hpp
│       ├── session_manager.hpp
│       ├── settings.hpp
│       ├── ssl_settings.hpp
│       ├── status_code.hpp
│       ├── string.hpp
│       ├── uri.hpp
│       ├── web_socket.hpp
│       └── web_socket_message.hpp
└── restbed
lib
├── python2.7
│   ├── dist-packages
│   └── site-packages
└── python3.5
    └── dist-packages
library
├── librestbed.a
├── librestbed.so -> librestbed.so.4
├── librestbed.so.4 -> librestbed.so.4.7
└── librestbed.so.4.7

```
I compiled it, but it can't find the library. 

ben@VMDebian2:~/Workspaces/restbed_test$ ./test
./test: error while loading shared libraries: librestbed.so.4: cannot open shared object file: No such file or directory

Why is it looking for librestbed.so.4 ???

**Comment by ben-crowhurst** [comment]
What were your build commands?

**Comment by benwarrick** [comment]
Hi Ben,

I did as the readme instructs: 

mkdir restbed/build
cd restbed/build
cmake [-DBUILD_SSL=NO] ..
make install
make test

And I can build the example project HTTP_Service with the following: 

clang++ -L/usr/local/library -std=c++11 -o test test.cpp -l restbed

This way I can run the executable, but only with root and only after setting the LD_LIBRARY_PATH=/usr/local/library

If I try to run the executable without setting the LD_LIBRARY_PATH, I get the error above. And without root, I get a permission error. 

I'm trying to use the restq project as an example of how to setup for cmake:

find_package( restbed REQUIRED )
include_directories( ${restbed_INCLUDE} )
add_library( $<TARGET_OBJECTS:restbed> )

 and also a sophisticated looking Findrestbed.cmake. But it looks like this project is locating the source files, not the executables outside of the project. 

Is there a best practice defined for including restbed in a project? I'm new to writing cmake files but i'm trying to understand it properly. 

Thanks,

Ben W

**Comment by ben-crowhurst** [comment]
Why do you believe this failed to compile correctly?

**Comment by ben-crowhurst** [comment]
Are you sure you have LD paths configured correctly in your environment?  Is the restbed lib in that path?

**Comment by benwarrick** [comment]
Hi ben-crowhurst,

The LD path is correct. Running "make install" puts the librestbed.so library file into /usr/local/library. I have to create the "library" file on Debian, which already has a /usr/local/lib file, for "make install" to work. So, for the readme example to work, I have to specify the non-standard Debian library folder and run as root. I don't think this is probably how restbed is intended to be used in a project. 

I'm trying to use restq as an example. It looks like restq pulls the restbed project into its dependency folder. It's CMakeList.txt file has the following entries: 

find_package( restbed REQUIRED )
include_directories( SYSTEM ${md5_INCLUDE} ${asio_INCLUDE} ${load_INCLUDE} ${restbed_INCLUDE} ${kashmir_INCLUDE} )
add_library( ${PROJECT_NAME} ${MANIFEST} ${load_SOURCE} $<TARGET_OBJECTS:restbed> )

as well as

set( CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/modules" )

Which looks like it picks up cmake/modules/Findrestbed.cmake, which points to all the restbed source files in the dependency folder. 

Doesn't this mean that restbed will have to compile every time your rebuild the project? 

What is the intended way to include restbed in a project?

**Comment by mortenfc** [comment]
bump

**Comment by ben-crowhurst** [comment]
Build dependencies are designed to be placed within `restbed/distribution` folder to provide an OS-agnostic approach.  Once you run `make install` you are free to extract them from this folder and place wherever your OS of choice decides is the most appropriate location.

I hope this has given some insight to our approach?
