### ISSUE TITLE
openssl make all failing

### ISSUE THREAD

**Issue by mithusingh32** [Corvusoft/restbed#363]
cmake can't find openssl, so I do ./config share; make all inside the openssl dependency folder.
./config seems to work fine but when it comes to do a make, I get this output: 

 do \
      if [ -f $f ]; then cat $f; fi; \
    done ) > Makefile.new; \
  if cmp Makefile.new Makefile >/dev/null 2>&1; then \
    rm -f Makefile.new; \
  else \
    mv -f Makefile.new Makefile; \
  fi; \
fi", ...) failed.
make (e=87): The parameter is incorrect.
make[1]: *** [Makefile:214: depend] Error 87
make: *** [Makefile:129: all] Error 2

**Comment by ben-crowhurst** [comment]
Please clearly specify the build steps you've taken to construct Restbed and under which environment compiler, OS, etc...

**Comment by mithusingh32** [comment]
Apologies. 

OS: Windows 10 Pro 64 bit 
Compiler: MinGW Distro (https://nuwen.net/mingw.html)

```
git clone --recursive https://github.com/corvusoft/restbed.git
mkdir restbed/build
cd restbed/build
cmake [-DBUILD_SSL=NO] ..
```
It will fail at this step because it can't find openssl dependencies. I'll do the following:
```
cd ../dependencies/openssl
./config shared
make all
```

**Comment by ben-crowhurst** [comment]
We don't and have never directly supported MinGW on windows.  We do however support Windows using its native build chain under Visual Studio.

Please try building using the native tools and thanks for using Restbed.
