### ISSUE TITLE
Requests containing [ or ] will fail

### ISSUE THREAD

**Issue by ghost** [Corvusoft/restbed#366]
Hello i was trying Restbed example as i really like the API but i ran into an issue:

On windows 10 x64, Visual Studio 2017, Console app

Whenever i use Postman to try and send JSON object containing any array, i will get:
> Your client has issued a malformed or illegal request status line. That’s all we know.

Any idea what can be wrong? :(

Edit: Example of the call from Postman - http://localhost:1984/resource?test={"test":["t1"]}

```
void get_method_handler(const shared_ptr< Session > session)
{
	session->close(OK, "Hello, World!", { { "Content-Length", "22" }, { "Connection", "close" } });
}

void startRest()
{
	auto resource = make_shared< Resource >();
	resource->set_path("/resource");
	resource->set_method_handler("GET", get_method_handler);

	auto settings = make_shared< Settings >();
	settings->set_port(1984);
	settings->set_default_header("Connection", "close");

	Service service;
	service.publish(resource);
	service.start(settings);
}
```

**Comment by Dc41f** [comment]
It was a newbie mistake ofcourse :). Postman didnt encode the URL for me and it took me ages to realize that. I have used https://www.urlencoder.org/ to encode it and now it works fine.

```
Unencoded example: {"values":["1", "2"]}
Encoded example: %7B%22values%22%3A%5B%221%22%2C%20%222%22%5D%7D
```

This article has opened my eyes: https://perishablepress.com/stop-using-unsafe-characters-in-urls/
