### ISSUE TITLE
Is it possible to run the Service asynchronously?

### ISSUE THREAD

**Issue by aprole** [Corvusoft/restbed#368]
Hello,

I am using the Service in a GUI application (MFC on windows) and would like to implement controls to allow the user to start and stop the service. So far it seems like the only way to run the service is by calling Service::start(), but that is ends up blocking. As a temporary solution I placed the service in a concurrency::task. This works but I'm not sure how to shutdown the service without destroying the thread. Is there a way to run it asynchronously?

Thanks,
Alex

**Comment by moneroexamples** [comment]
Not sure if this is what you are after, but I execute `start()` its in own thread. Then in the main tread I use conditional var to wait for cont+c to gracefully stop the service. The relevant code lines for this are here:

https://github.com/moneroexamples/openmonero/blob/ac0463d6d88f7fbce174ed31eb898ae0777334aa/main.cpp#L319-L342

**Comment by ben-crowhurst** [comment]
Guys/Gals take a look at the ready_handler; see example and documentation.
