### ISSUE TITLE
Multiple Service instances listening on same port does not throw exception

### ISSUE THREAD

**Issue by aprole** [Corvusoft/restbed#369]
When I run two instances of my program, each having a Service that is configured to listen on the same port, the second instance will not throw any exception. The Service's ready_handler will get called and Service::is_up() will return true. Yet it won't actually receive anything data because the other Service is already bound to that port number. I tried seeing if the Service's error_handler gets called, but it does not. It would be nice to have some feedback mechanism to know if the Service did not successfully bind to the port.

**Comment by sotex** [comment]
This problem I encountered a long time ago should be only occurring on the Windows platform.

The following information is available for reference:
- [Using SO_REUSEADDR and SO_EXCLUSIVEADDRUSE](https://docs.microsoft.com/en-us/windows/desktop/WinSock/using-so-reuseaddr-and-so-exclusiveaddruse)
- [Socket options](http://man7.org/linux/man-pages/man7/socket.7.html)

**Comment by ben-crowhurst** [comment]
Please provide a code example for us to debug.

**Comment by ben-crowhurst** [comment]
I'm not entirely sure on how to approach this issue.  @aprole / @sotex do either of you have a suggestion on a fix?

**Comment by ben-crowhurst** [comment]
Perhaps a settings feature?
```C++
settings->set_reuse_address(true);
```
This is the only portable solution I can currently see.

**Comment by ben-crowhurst** [comment]
Implemented set_reuse_address in the service settings.
