### ISSUE TITLE
deprecated function get_io_service() is removed in asio 1.13.0

### ISSUE THREAD

**Issue by Rastaban** [Corvusoft/restbed#370]
Just wanted to give you a heads up that the 1.13.0 release of asio removes a few previously deprecated member functions that are used in restbed.  See their release notes http://think-async.com/Asio/asio-1.13.0/doc/asio/history.html#asio.history.asio_1_13_0.

**Comment by ben-crowhurst** [comment]
Thanks for the notice, will roll out an updated build shortly.

**Comment by JackBoosY** [comment]
@ben-crowhurst Any progress?

Related: [#8880](https://github.com/microsoft/vcpkg/pull/8800).

**Comment by ben-crowhurst** [comment]
We've upgraded the 4.7 branch to the latest 1.12.* release.  Tackling ASIO 1.13.0 will require significant surgery and we're on track for 1.13.0 to be a major feature of the 4.8 release.

**Comment by JackBoosY** [comment]
@ben-crowhurst Thanks for reply, if this problem is fixed, please let me know. I will update restbed in vcpkg.

Thanks.

**Comment by ben-crowhurst** [comment]
I'll let you know, thanks.

**Comment by fxfire** [comment]
I upped just yesterday to ASIO 1.16.1 aka latest and had to replace only 4 spots in restbed with what was already said above, 
get_io_service can be replaced with get_executor().context()

all works fine

**Comment by JackBoosY** [comment]
The latest version not working with asio 1.18.0.

**Comment by ben-crowhurst** [comment]
Pushed dependency to 1.18.2 .
