### ISSUE TITLE
reverse proxy

### ISSUE THREAD

**Issue by mipac** [Corvusoft/restbed#373]
hi,
i'd like to expose an api based on multiple microservices
how can I redirect requests to the good service, in function of the route?

**Comment by ben-crowhurst** [comment]
What have you tried so far?

**Comment by mipac** [comment]
well, I plan to do it "manually"
services come register to the front service, stored in internal table, 
and then I redirect from front route request to the good instance with httpClient, with async

but I wonder if there was a "middleware" approach, or an example, before re-invent the wheel

**Comment by mipac** [comment]
I try to better formulate :)

I try to implement a service with :
1)/config
2)/services
3)/services/{id}/

and I want to redirect to another service all the path after /services/{id}
for example GET /services/2/bubbles
call GET /bubbles of the service n°2

an api gateway? not sure of the term...
but anyway, how could I implement that with Restbed?

I try to define a ressource "/services/*" where every call would be redirected "by hand" but it does not work

How would you do that kind of proxy ?

best regards

**Comment by mipac** [comment]
It works!!

I define a resource with multiple paths
with set_paths{
{
            "/services",
            "/services/{id: ^[0-9]{1,8}$}",
            "/services/{id: ^[0-9]{1,8}$}/.*/",
            "/services/{id: ^[0-9]{1,8}$}/.*/.*",
            "/services/{id: ^[0-9]{1,8}$}/.*/.*/.*",
            "/services/{id: ^[0-9]{1,8}$}/.*/.*/.*/.*",
            "/services/{id: ^[0-9]{1,8}$}/.*/.*/.*/.*/.*",
            "/services/{id: ^[0-9]{1,8}$}/.*/.*/.*/.*/.*/.*"
}

and a handler which will be called for all path beginning with /services

it's a bit brute force, but ok for my use case

hope that can help someone.
