### ISSUE TITLE
Restbed Service Start blocking Windows Message Loop

### ISSUE THREAD

**Issue by annyou88** [Corvusoft/restbed#375]
Hi - I am trying to implement Restbed service inside a Windows application (MFC dialog-based) that will run minimized in system tray upon application startup to simulate a "service" on Windows.  User can either double click on the tray icon to restore the window, or right click to show popup menu to exit app.

My problem right now is - I got the Restbed service implemented inside my MFC app, and everything is working fine - the Restbed service can be started and can service requests.  However, once WS started, it appears blocking, as I can no longer access my system tray icon to right click or double click.  If I comment out the code that starts the service, then all Windows action works fine.

I have already implemented set_ready_handler(), and have a function to receive the ready call.  That function is being called, so I know that part works fine.

Before this Windows version, I implemented in a Windows console app using the same Restbed APIs (same methods, manners, implementing set_ready_handler), and evreything was working fine,  After I implement the set_ready_handler() then it won't block the command prompt window.  So not sure why this method is not working for Windows app?

Appreciate any help!  Thanks in advance.

Ann

**Comment by ben-crowhurst** [comment]
Please provide example code.

**Comment by annyou88** [comment]
Hi - I will work on the sample as soon as I am able.  Will let you know once I have something ready.  Thanks.

**Comment by annyou88** [comment]
> Please provide example code.

Hi - I have the sample project and code ready in the attached ZIP file.  This is a VS 2017 MFC project.  For this project, you will need to have an .\include dir and a .\lib dir for the Restbed stuff (too big to be packed into the ZIP file).  So your directory structure should be something like this:

c:\TestDev\Restbed_SysTray_TestApp\
  include\
  lib\
  RestbedServerTest2\
  Restbed_SysTray_TestApp.sln

The 2 lines of code of particular interest is in RestbedServerTest2Dlg.cpp, in OnInitDialog() -> lines 115, 116.  If you comment those 2 lines (don't start the service), then you can right click on the SysTray app icon and the popup menu will display, and can click Exit to exit app.  If you have those 2 lines in, then once the Restbed service is started, right click on the SysTray app icon has no effect.

Thanks in advance.
Ann

[Restbed_SysTray_TestApp.zip](https://github.com/Corvusoft/restbed/files/3216192/Restbed_SysTray_TestApp.zip)

**Comment by annyou88** [comment]
Hi - any updates on this issue?  I have provided sample code/ project as requested, and even detailed the steps and the lines causing the problem.  Thank you.

**Comment by ben-crowhurst** [comment]
Could you please post the code in a code block?  I'm wary of opening a binary file locally.

**Comment by annyou88** [comment]
Hi - I thought by providing a sample app to demonstrate this problem would be easiest?  Since this is a Windows app and there are several classes involved?  I can give you that one particular code block that calls Restbed service, but I don't think it will do any good if not placed inside the entire project/ app?  The ZIP file I provided does not have any binary files, but does include the entire VS solution and resource files and code files.  So if have VS, can just load that solution and build.

Do you still want me to extract out the code in the dialog class?

Thanks.

**Comment by ben-crowhurst** [comment]
Please extract out all the Restbed related code.  If the problem is there I will be able to tell you.

**Comment by annyou88** [comment]
Hi - here you go - all Restbed related code in the app

////////////// RestBedTestApi.h /////////////////////
/**
 * RestBed Test API
 * RestBed Test API description
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.5.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * RestBedTestApi.h
 *
 * 
 */

#ifndef RestBedTestApi_H_
#define RestBedTestApi_H_

#include <memory>

#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/service.hpp>
const int WS_PORT = 7000;

namespace io {
namespace swagger {
namespace server {
namespace api {

//using namespace io::swagger::server::model;

class  RestBedTestApi: public restbed::Service
{
public:
  RestBedTestApi();
	~RestBedTestApi();

	void startService(int const& port);
	void stopService();
};


/// <summary>
/// A series of client actions that takes input XML data formatted by user, processes the data internally for different operations, and returns the processed results in the output XML data
/// </summary>
/// <remarks>
/// 
/// </remarks>
class  RestBedTestApiClient_actionResource: public restbed::Resource
{
public:
  RestBedTestApiClient_actionResource();
  virtual ~RestBedTestApiClient_actionResource();

  void POST_method_handler(const std::shared_ptr<restbed::Session> session);
};

}
}
}
}


////////////// RestBedTestApi.cpp /////////////////////
#include "stdafx.h"

#include <fstream>
#include <streambuf>

#include <restbed>
#include <corvusoft/restbed/byte.hpp>
#include <corvusoft/restbed/string.hpp>
#include <corvusoft/restbed/settings.hpp>
#include <corvusoft/restbed/request.hpp>

#include "RestBedTestApi.h"

using namespace restbed;

namespace io {
namespace swagger {
namespace server {
namespace api {

//using namespace io::swagger::server::model;

/*
void service_ready_handler(Service&)
{
  fprintf(stdout, "RestBed Test Service is up and listening at port %d...\n", WS_PORT);
}
*/

RestBedTestApi::RestBedTestApi()
{
	std::shared_ptr<RestBedTestApiClient_actionResource> spRestBedTestApiClient_actionResource = std::make_shared<RestBedTestApiClient_actionResource>();
	this->publish(spRestBedTestApiClient_actionResource);

}

RestBedTestApi::~RestBedTestApi()
{
}

void RestBedTestApi::startService(int const& port)
{
	std::shared_ptr<restbed::Settings> settings = std::make_shared<restbed::Settings>();
	settings->set_port(port);
	settings->set_root("/Test");

  // ARY NOTE: Cannot have this line here, or else response will return empty string!
  //this->set_ready_handler(service_ready_handler);
	
	this->start(settings);
}

void RestBedTestApi::stopService()
{
	this->stop();
}

RestBedTestApiClient_actionResource::RestBedTestApiClient_actionResource()
{
	this->set_path("test_action");
	this->set_method_handler("POST",
		std::bind(&RestBedTestApiClient_actionResource::POST_method_handler, this,
			std::placeholders::_1));
}

RestBedTestApiClient_actionResource::~RestBedTestApiClient_actionResource()
{
}

void RestBedTestApiClient_actionResource::POST_method_handler(const std::shared_ptr<restbed::Session> session)
{
	const auto request = session->get_request();

	// Body params are present, therefore we have to fetch them
	int content_length = request->get_header("Content-Length", 0);

	session->fetch(content_length,
		[ this ]( const std::shared_ptr<restbed::Session> session, const restbed::Bytes & body )
		{
      const auto request = session->get_request();

      std::string requestBody = restbed::String::format("%.*s\n", (int)body.size(), body.data());
      /**
       * Get body params or form params here from the requestBody string
       */

       // Get some sample file, and then stream to string to be returned to caller.
      std::ifstream t(".\\test\\CMakeLists.txt");
      std::string response_str((std::istreambuf_iterator<char>(t)),
        std::istreambuf_iterator<char>());
      std::size_t response_len = response_str.length();
      std::string response_len_str = std::to_string(response_len);

      // Change the value of this variable to the appropriate response before sending the response
      int status_code = 200;

			/**
			 * Process the received information here
			 */
			if (status_code == 200) 
      {
        session->close(200, response_str, { { "Content-Length", response_len_str}, { "Connection", "close" } });
				return;
			}
			if (status_code == 404) 
      {
				session->close(404, "Invalid request", { {"Connection", "close"} });
				return;
			}
		});
}

}
}
}
}

////// RestbedServerTest2.cpp /////////////////////////////////
//////   This is the Windows application main class.  
//////   Service ready handler method implemented here as global function
//////   so later dialog class can access. 

void service_ready_handler(Service&)
{
  ((CRestbedServerTest2Dlg *)theApp.m_pMainWnd)->MessageBox(L"Test Service is ready...", L"Test Service");
}


////// RestbedServerTest2Dlg.h /////////////////////////////////
//////   This is the Windows application dialog class header file.  

// RestbedServerTest2Dlg.h : header file
//

#pragma once

#include "TrayDialog.h"

#include "RestBedTestApi.h"

using namespace restbed;
using namespace io::swagger::server::api;


// CRestbedServerTest2Dlg dialog
class CRestbedServerTest2Dlg : public CTrayDialog
{
// Construction
public:
	CRestbedServerTest2Dlg(CWnd* pParent = nullptr);	// standard constructor

// Dialog Data
#ifdef AFX_DESIGN_TIME
	enum { IDD = IDD_RESTBEDSERVERTEST2_DIALOG };
#endif

	protected:
	virtual void DoDataExchange(CDataExchange* pDX);	// DDX/DDV support


// Implementation
protected:
	HICON m_hIcon;

	// Generated message map functions
	virtual BOOL OnInitDialog();
	afx_msg void OnSysCommand(UINT nID, LPARAM lParam);
	afx_msg void OnPaint();
	afx_msg HCURSOR OnQueryDragIcon();
	DECLARE_MESSAGE_MAP()
public:
  afx_msg void OnMnuStopService();
  afx_msg void OnMnuStartService();
  afx_msg void OnMnuExit();

private:
  RestBedTestApi m_epidService;		// The Service class object

};


////// RestbedServerTest2Dlg.cpp /////////////////////////////////
//////   This is the Windows application dialog class.  This dialog window
//////   will be running minimized in system tray, and is the window 
//////   displaying the popup menu, and handling all menu events.
//////   This dialog in its OnInitDialog() starts the Restbed service
//////   after the dialog is done its own initialization. 

BOOL CRestbedServerTest2Dlg::OnInitDialog()
{
  CTrayDialog::OnInitDialog();

	// Add "About..." menu item to system menu.

	// IDM_ABOUTBOX must be in the system command range.
	ASSERT((IDM_ABOUTBOX & 0xFFF0) == IDM_ABOUTBOX);
	ASSERT(IDM_ABOUTBOX < 0xF000);

	CMenu* pSysMenu = GetSystemMenu(FALSE);
	if (pSysMenu != nullptr)
	{
		BOOL bNameValid;
		CString strAboutMenu;
		bNameValid = strAboutMenu.LoadString(IDS_ABOUTBOX);
		ASSERT(bNameValid);
		if (!strAboutMenu.IsEmpty())
		{
			pSysMenu->AppendMenu(MF_SEPARATOR);
			pSysMenu->AppendMenu(MF_STRING, IDM_ABOUTBOX, strAboutMenu);
		}
	}

	// Set the icon for this dialog.  The framework does this automatically
	//  when the application's main window is not a dialog
	SetIcon(m_hIcon, TRUE);			// Set big icon
	SetIcon(m_hIcon, FALSE);		// Set small icon

	// TODO: Add extra initialization here
  TraySetIcon(IDR_MAINFRAME);
  TraySetToolTip(L"Hello from RestBed Test Service");
  TraySetMenu(IDR_MENU1);

  TrayShow();
  TraySetMinimizeToTray(TRUE);

  //// Ann Note: Comment these 2 lines below.  Run the program.  Right click on the SysTray icon,
  //// will get a popup menu of "Start Service, Stop Service, Exit".
  //// With these 2 lines, when right click on the SysTray icon, no response and no popup menu.
  m_epidService.set_ready_handler(service_ready_handler);
  m_epidService.startService(WS_PORT);

	return TRUE;  // return TRUE  unless you set the focus to a control
}

Thanks for your help.

**Comment by ben-crowhurst** [comment]
```m_epidService.startService(WS_PORT);``` never returns.  Your application has to resume from within the ```service_read_handler```.

**Comment by annyou88** [comment]
Well - you know what - it never dawned on me the call to startService() never returned.  But thanks for this info/ tip -> your comment got me thinking.  So I resolved this "blocking" issue by putting the startService() in a separate thread.  This way the service is not blocking the application main window UI thread.  After implementing the thread solution, everything works fine now.  

Thank you very much for your help!  Really appreciate it.

**Comment by ben-crowhurst** [comment]
Happy to help 💃

**Comment by kenkit** [comment]
There is still no documentation on how to properly do this. Only some stuff about signals which are linux stuff i'm not familiar with.
I think we should come up with an example of how to start/stop a service in a nonblocking manner to get rid of this confusion.
