### ISSUE TITLE
multipart data on server

### ISSUE THREAD

**Issue by hardwaredesignvhdl** [Corvusoft/restbed#377]
Hi , I am running restbed example to see feasibility to use in project. server is receiving multi-part data(file upload) from client. I can see when it received POST it called post handler. My question is, 
content_length is what total length of uploaded file? does it count multi-part "\upload" header length too?
When I dump Bytes vector memory when it called post handler , I found it contained  Boundry message, contenttype ,file name and so.....like this first few memory location, (its correct as per standard)
------WebKitFormBoundaryNOito4u3SYABv9ay
Content-Disposition: form-data; name="file"; filename="IMG-20190528-WA0000.jpg"
Content-Type: image/jpeg...……………………

Why Bytes doesn't directly return actual file data? is there any function for this? otherwise, I have to mask each and every bytes to get filename, type,...etc and after that to reach pointer to actual file data and perform copy.
DO you have any example for multi-part file transfer?

code: 
void post_method_handler(const shared_ptr< Session > session)
{
    const auto request = session->get_request();

    int content_length = request->get_header("Content-Length", 0);

    session->fetch(content_length, [](const shared_ptr< Session > session, const Bytes & body)
    {
        
         fprintf(stdout, "%.*s\n", (int)body.size(), body.data());
        session->close(OK, "Hello, World!", { { "Content-Length", "13" } });
    });
}
Can you help here?

**Comment by ben-crowhurst** [comment]
This logic would have to be carried out by your application logic.
