### ISSUE TITLE
how can i set  diffrent paths with the same begin? 

### ISSUE THREAD

**Issue by zhanb** [Corvusoft/restbed#378]
hello ,I want set paths like /api/1, /api/1/1,/api/1/1/1, /api/1/1/1/1 ... ,i do not know how deep the url,but it begin with /api, how can i do ?

**Comment by mipac** [comment]
you can register multiple paths with a handler
look at examples in documentation
with regex you can set
"api", "api/.*", "api/.*/.*", ....
with a maximum depth

**Comment by zhanb** [comment]
> you can register multiple paths with a handler
> look at examples in documentation
> with regex you can set
> ‘‘
> "api", "api/._", "api/._/.*", ....
> ‘‘
> with a maximum depth

emmmm,that look like  not very smart

**Comment by ben-crowhurst** [comment]
As @mipac pointed out, you can use the regex matching capabilities to match any path length.  If you don't know the depth of the path sub directories Restbed won't know this information either.
`/api/{one: [0-9]}/{two: [0-9]}`

Alternatively, parse the incoming URL in your own code.
