### ISSUE TITLE
doesn't work in visual studio 2019

### ISSUE THREAD

**Issue by misland** [Corvusoft/restbed#379]
I install the package by Nuget in vs2019 and I just copy the code in the main page.when I build the project in the vs2019,vs2019 returns serveral faults(unresolved external symbol) as follows:
![image](https://user-images.githubusercontent.com/10702423/59736252-6d196100-928b-11e9-8f7d-1c452329b4a4.png)
while everything in vs2017 is perfect!
can anyone explain why?thanks!!

**Comment by MINIONBOTS** [comment]
I cannot read your language, but I literally just compiled restbed in vs2019 and it works fine in my project.

**Comment by GordonEldest** [comment]
@misland 
While being very late comment
Look likes a rather classical missing standard lib. Either inform liker directly searchin web with missing basic_string lib
Or some hints
In project properties, Did you checked the "windows SDK version"
in C/C++ "Code generation" that you do not use de "Multithread XXX DLL" for RunTime library (or that this one is consistent with general panel "Use of MFC"

**Comment by smeualex** [comment]
The title is a bit misleading - it doesn't work with NuGet in vs2019.

I used restbed in VS2019 with no problems but used via git clone and cmake + build with vs2019.

**Comment by ben-crowhurst** [comment]
Now builds with Visual Studio 2019 on a Windows 10 environment.
