### ISSUE TITLE
In restbed post response some extra characters how to remove extra data padding in http request

### ISSUE THREAD

**Issue by thellaindudhar** [Corvusoft/restbed#382]
"INFO_17-21-01: 356 {"channelId":5,"ecoSystemId":1,"start_time_utc":"2019-06-18 09:15:16","end_time_utc":"2019-06-18 09:29:16","primaryinput_url":"rtmp://192.168.22.112/live/commet","secondaryinput_url":"rtmp://192.168.2.10:1935/live/myStream","callback_url":"http://192.168.30.193:1252/api/MagicMoments/ndvrInitiatedCallback?callbackjson=","programId":"iretriseries_2019_g5"}�"
how to remove the � extra character in these response

**Comment by thellaindudhar** [comment]
"INFO_17-21-01: 356 {"channelId":5,"ecoSystemId":1,"start_time_utc":"2019-06-18 09:15:16","end_time_utc":"2019-06-18 09:29:16","primaryinput_url":"rtmp://192.168.22.112/live/commet","secondaryinput_url":"rtmp://192.168.2.10:1935/live/myStream","callback_url":"http://192.168.30.193:1252/api/MagicMoments/ndvrInitiatedCallback?callbackjson=","programId":"iretriseries_2019_g5"}�"
how to remove the � extra character in these response

**Comment by thellaindudhar** [comment]
code:-
-------
void post_method_handler( const shared_ptr< Session > session )
{
        const auto request = session->get_request( );
        int content_length = request->get_header( "Content-Length", 0 );

        session->fetch( content_length, [ ]( const shared_ptr< Session > session, const Bytes & body )
                        {
                        char ch_json[4096] = {'\0'};
                        StringBuffer JSONStrBuffer;
                        Writer<StringBuffer> writer(JSONStrBuffer);
                        writer.StartArray();
                        writer.StartObject();
                        logmsg_info(ndvr_logger,"\n\n");
                        logmsg_info( ndvr_logger, "%d %s\n", ( int ) body.size( ), body.data( ) );
                        memset(ch_json,'\0',sizeof(ch_json));
                        strncpy(ch_json,(char *)body.data( ),( int ) body.size( ));
                        if(parse_request(ch_json))
                        {
                        writer.Key("result"); writer.String("failure");
                        }
                        else
                        {
                        writer.Key("result"); writer.String("success");
                }

                writer.EndObject();
                writer.EndArray(); 
                session->close(OK, JSONStrBuffer.GetString());
        } );
}


int main(  int argc,  char  **argv )
{
        if(argc != 2){
                fprintf(stderr,"Usage: %s <log_path> : \n",argv[0]);
                exit(EXIT_FAILURE);
        }
        create_logger(&ndvr_logger);
        set_logger_name(ndvr_logger,argv[1]);
        set_logger_WrapTime(ndvr_logger,3600);
        set_logger_size(ndvr_logger,10);
        set_logger_level(ndvr_logger,0);

        logmsg_info(ndvr_logger,"Basic ndvr_interface log message\n");

        auto resource = make_shared< Resource >( );
        resource->set_path( "/ndvr" );
        resource->set_method_handler( "POST", post_method_handler );

        auto settings = make_shared< Settings >( );
        settings->set_port( 1984 );
        settings->set_default_header( "Connection", "close" );

        Service service;
        service.publish( resource );
        service.start( settings );

        return EXIT_SUCCESS;
}
-------------------------------------------------------------------------------------------------
->post curl:-
----------------
curl --header "Content-Type: application/json" --request POST --data '{"channel"start_time_utc":"2019-06-18 09:15:16","end_time_utc":"2019-06-18 09:29:16","primaryinput_url":"rtmp://192.168.22.112/live/commet","secondaryinput_url":"rtmp://192.168.2.10:1935/live/myStream","callback_url":"http://192.168.30.193:1252/api/MagicMoments/ndvrInitiatedCallback?callbackjson=","programId":"iretriseries_2019_g5"}' http://localhost:1984/ndvr
-------------------------------------------------------------------------------------------------------------------------------------------->output:-
------------
INFO_11-55-23: 356 {"channelId":5,"ecoSystemId":1,"start_time_utc":"2019-06-18 09:15:16","end_time_utc":"2019-06-18 09:29:16","primaryinput_url":"rtmp://192.168.22.112/live/commet","secondaryinput_url":"rtmp://192.168.2.10:1935/live/myStream","callback_url":"http://192.168.30.193:1252/api/MagicMoments/ndvrInitiatedCallback?callbackjson=","programId":"iretriseries_2019_g5"}�
INFO_11-55-23: ################ channel_id 5 ##################
INFO_11-55-23: ################ start_time_utc 2019-06-18 09:15:16 ##################
INFO_11-55-23: ################ end_time_utc 2019-06-18 09:29:16 ##################
INFO_11-55-23: ################ primaryinput_url rtmp://192.168.22.112/live/commet ##################
INFO_11-55-23: ################ secondaryinput_url rtmp://192.168.2.10:1935/live/myStream ##################
INFO_11-55-23: ################ callback_url http://192.168.30.193:1252/api/MagicMoments/ndvrInitiatedCallback?callbackjson= ##################
INFO_11-55-23: ################ ecoSystemId 1 ##################
--------------------------------------------------------------------------------------------------------------------------------------
->issue:-
-------------
how to remove the � extra character in these response

**Comment by ben-crowhurst** [comment]
This issue should have been resolved in a previous commit.  Are you still seeing this issue?

**Comment by ben-crowhurst** [comment]
Failed to replicate and no response from original author.  Please reopen if you are still seeing this issue.
