### ISSUE TITLE
Uri.get_path("file://...") - relative paths

### ISSUE THREAD

**Issue by oodgaard** [Corvusoft/restbed#39]
This regex seems to not allow relative paths : https://github.com/Corvusoft/restbed/blob/master/source/corvusoft/restbed/uri.cpp#L207
(https://github.com/Corvusoft/restbed/blob/3.0/source/corvusoft/restbed/uri.cpp#L200)

e.g.:

auto uri = Uri("file://certs/server.key");
cout << uri.get_path() << endl;

prints:  /server.key

I guess this is only relevant for file:// though since http://blah.com/blah would be fine.

**Comment by ben-crowhurst** [comment]
Thanks for that @oodgaard, will look to resolve this immediately.

**Comment by ben-crowhurst** [comment]
See https://tools.ietf.org/html/rfc3986#section-4.2 for details of relative path URIs.
