### ISSUE TITLE
http request timeout 

### ISSUE THREAD

**Issue by mipac** [Corvusoft/restbed#391]
Is it possible to set a timeout to a sync call (or async) in the case of failed cause of unknown endpoint?
I saw the timeout examples, where the server is here but "too long"
In the case of unreachable endpoint, I have around 130s of timeout
even when I set 1s with settings for example.
Is there a way to change this behaviour?

best regards,

**Comment by ben-crowhurst** [comment]
The HTTP client has been deprecated, we will provide a complimentary client framework at a later date.
