### ISSUE TITLE
client timeout does not work and sometimes a thread never comes back from sync method

### ISSUE THREAD

**Issue by aliufukyaman** [Corvusoft/restbed#392]
Although the timeout value for client can be set, it does not seem to work. I could not manage to make a timeout on my own too because a thread for client with post method never comes back from Http::sync method so I can not catch if it was a fail or not and handle a manual timeout. 
Below is my code snippet. Any idea? Can not use the library in this way, am I doing something wrong or this is  really a bug? 

```
	auto request = std::make_shared< restbed::Request >(restbed::Uri(connectionUrl));
	request->set_header("Content-Type", "application/json");
	request->set_header("Host", m_params.ip); //does not work without this line.
	request->set_method("POST");

	auto settings = std::make_shared< restbed::Settings >();
	settings->set_connection_timeout(std::chrono::milliseconds(1000));

	request->set_body(requestStr);
	request->set_header("Content-Length", std::to_string(requestStr.size()));

	auto response = restbed::Http::sync(request, settings); // sometimes the thread never returns from this line, stuck here
	responseStatus = response->get_status_message().data();
	if (responseStatus != "OK")
	{

		APP_LOG(LogLevel::ERROR_LOG, "Unexpected server response: " + responseStatus);
	}

	size_t content_length = response->get_header("Content-Length", 0);
	restbed::Http::fetch(content_length, response);

	const auto body = response->get_body();
	std::string strBody(body.begin(), body.end());`
		   
	return strBody;
```

**Comment by ben-crowhurst** [comment]
@aliufukyaman while I'm sure not the response you are looking for, however, we've decide to deprecate the HTTP client in favour of concentrating on the frameworks core problem domain; services.

We will be releasing a complementary client project at a future date.
