### ISSUE TITLE
Has anyone tested restbed performance?

### ISSUE THREAD

**Issue by zhanb** [Corvusoft/restbed#393]
I wrote a hello world demo of GET method with restbed, and a hello world of GET method with nginx. I tested concurrency performance with ab tool, and found that the performance of restbed was several dozen times worse than that of nginx. I don't know if there's a problem with the method I'm using. Has anyone else tested restbed for performance?

**Comment by ben-crowhurst** [comment]
https://github.com/binaryspaceship/cpp-rest-frameworks-benchmark
