### ISSUE TITLE
Does Restbed support UDP?

### ISSUE THREAD

**Issue by oddvardm** [Corvusoft/restbed#396]
I need to write a method that uses UDP datagrams. I can not find this topic in the documentation.

**Comment by zhanb** [comment]
as i know,restbed not support udp

**Comment by oddvardm** [comment]
Thank you. Maybe the socets can do it, by I have not seen it. 


----- Opprinnelig melding -----

Fra: "zhanb" <notifications@github.com> 
Til: "Corvusoft/restbed" <restbed@noreply.github.com> 
Kopi: "oddvardm" <oddvardm@getmail.no>, "Author" <author@noreply.github.com> 
Sendt: 15. oktober 2019 10:28:07 
Emne: Re: [Corvusoft/restbed] Does Restbed support UDP? (#396) 



as i know,restbed not support udp

**Comment by ben-crowhurst** [comment]
Not yet. Quic is UDP based so this feature will becoming down the pipe shortly.
