### ISSUE TITLE
Building warnings "base class has accessible non-virtual destructor [-Wnon-virtual-dtor]"

### ISSUE THREAD

**Issue by AIexG** [Corvusoft/restbed#398]
I've already been able to successfully compile restbed on Ubuntu 16.04 without any warnings or errors before, unfortunately it doesn't work anymore or I'm missing a crucial step I did before.

I've tried it with the following:

 - g++/gcc version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609 
 - g++/gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
 - installed packages: cmake make build-essential
 - asio version: 1.12.0

I'm executing the following commands:

    cd /usr/local/lib/
    git clone --recursive https://github.com/Corvusoft/restbed.git
    mkdir restbed/build && cd restbed/build
    cmake -DBUILD_SSL=NO ..
    make install

The following warnings get thrown for each object:

    In file included from /usr/local/lib/restbed/source/corvusoft/restbed/web_socket.cpp:10:0:
    /usr/local/lib/restbed/source/corvusoft/restbed/web_socket.hpp:37:11: warning: base class ‘class std::enable_shared_from_this<restbed::WebSocket>’ has accessible non-virtual destructor [-Wnon-virtual-dtor]
        class WebSocket : public std::enable_shared_from_this< WebSocket >

**Comment by ben-crowhurst** [comment]
Feel free to fire over a PR, alternatively will address this in the next release.

**Comment by ben-crowhurst** [comment]
This issue has now been addressed in the 4.7 branch.
