### ISSUE TITLE
Request and Connection close

### ISSUE THREAD

**Issue by mipac** [Corvusoft/restbed#400]
I try to send multiple request to a REST API (coded with Restbed)

From that client code I use a Request instance
if I "PUT" to a ressource wich is yielding, according to my request header "keep-alive", every thing is fine

after some PUT, I use the same request instance, I GET with connection close header. 
In this case I just get 0 as response status and nothing happen to server

I've tried to Http::close(request) before sending GET, but same result

Is this normal, or is there a bug?

**Comment by ben-crowhurst** [comment]
Please provide example code.
