### ISSUE TITLE
Unresolved external symbol for - Service class

### ISSUE THREAD

**Issue by lattard** [Corvusoft/restbed#401]
Hi,

I managage to compile restbed on windows using the hints given at [https://github.com/Corvusoft/restbed/issues/17] however for a minimal example of creating a restbed::Service object, I am getting the errors below.  I've added the path of the restbed.lib to the Properties>Linker>General>Additional Library Directories and the restbed.lib to  Properties>Linker>Input>Additional Dependencies.
Anyone encountered this issue and got it resolved ?

`1>CommunicationPoint.obj : error LNK2001: unresolved external symbol "public: void __cdecl restbed::Service::start(class std::shared_ptr<class restbed::Settings const > const &)" (?start@Service@restbed@@QEAAXAEBV?$shared_ptr@$$CBVSettings@restbed@@@std@@@Z)
1>CommunicationPoint.obj : error LNK2001: unresolved external symbol "public: void __cdecl restbed::Service::stop(void)" (?stop@Service@restbed@@QEAAXXZ)
1>CommunicationPoint.obj : error LNK2001: unresolved external symbol "public: virtual __cdecl restbed::Service::~Service(void)" (??1Service@restbed@@UEAA@XZ)
1>CommunicationPoint.obj : error LNK2001: unresolved external symbol "public: __cdecl restbed::Service::Service(void)" (??0Service@restbed@@QEAA@XZ)`

**Comment by MINIONBOTS** [comment]
99% sure your restbed.lib is not proper linked to your project, check spelling and the path once more

**Comment by lattard** [comment]
thanks, it is now solved. 
it was a problem with incorrect compilation config used, thus library compile in wrong architecture.
