### ISSUE TITLE
Restbed 4.7 fails to build with dynamic OpenSSL

### ISSUE THREAD

**Issue by zorun** [Corvusoft/restbed#405]
Commit 2d2ac94ccf8e2c084c3a396b4724b7843fe6d67e broke build with dynamic OpenSSL:

```
-- The CXX compiler identification is GNU 9.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Copyright 2013-2018, Corvusoft Ltd, All Rights Reserved.
-- Found ASIO include at: /usr/include
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "1.1.1d")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindOpenSSL.cmake:447 (find_package_handle_standard_args)
  CMakeLists.txt:50 (find_package)


-- Configuring incomplete, errors occurred!
```

Setting `OPENSSL_USE_STATIC_LIBS` to `FALSE` works, but I have no idea if it will also work with static build.

The previous method with `BUILD_STATIC` / `BUILD_SHARED` was working fine. If you really want to change it, you also need to document it in the release notes: instead of running `cmake -DBUILD_STATIC=OFF  -DBUILD_SHARED=ON`, one needs to run `make restbed-shared` later instead.

**Comment by ben-crowhurst** [comment]
@zorun thanks for raising this issue, I thought I corrected it.  Will take a look-see.

**Comment by ben-crowhurst** [comment]
We've had to move away from FindOpenSSL that comes prepackaged with CMake as it only supports detecting shared or static libraries.

There is no need to mention BUILD_SHARED or BUILD_STATIC as both are produced during a  build.
