### ISSUE TITLE
HTTP 1.1 "Host" Header is missing

### ISSUE THREAD

**Issue by mipac** [Corvusoft/restbed#408]
Hi,

I've spend a lot of time to debug connection problem with a tomcat webapp with "Request" object.
The problem is that "Host" header field is not present if we don't set it explicitly.
So when creating a Request, do add Host header field in your code!

It would be great to add Host field automatically with HTTP/1.1

hope that could help someone :)

**Comment by ben-crowhurst** [comment]
You are required to add the Host header manually by design.  We wish to offer the great level of flexibility for each individual projects needs.

**Comment by mipac** [comment]
Hi,

Sorry for so late response, 
but why can't this header be added automaticaly when request is created from uri?
or when http::(a)sync is called, using the request properties?

best regards
