### ISSUE TITLE
Restbed, Different methodes same paths are not allowed

### ISSUE THREAD

**Issue by phforest** [Corvusoft/restbed#412]
I'm using a restbed c++ and I came across a issue when registering the same uri but with different methods (POST,GET,DELETE) on one resource.

When running the server and requesting a GET request it works fine, but for the POST request I get '405 Method Not Allowed'

PS,Note I had to trick the regex part even to be able to resister the methode.

    GET : language:[a-z_]
    POST: language:[ab-z_]
```This if I register it with the same expression **set_path("/hello/{language:[a-z_]+}");**
#./so-rest 
Service accepting HTTP connections at 'http://[::]:1984'.
Resource published on route '/hello/{language:[a-z_]+}'.
So I kinda use these paths to be able to register them bought.
#./so-rest
Service accepting HTTP connections at 'http://[::]:1984'.
Resource published on route '/hello/{language:[a-z_]+}'.
Resource published on route '/hello/{language:[ab-z_]+}'.
```
Any Idea what is going wrong ? Thanks.

This is a sample code.

```
#include <memory>
#include <cstdlib>
#include <restbed>


using namespace std;
using namespace restbed;


class CustomLogger : public Logger
{
    public:
        void stop( void )
        {
            return;
        }

        void start( const shared_ptr< const Settings >& )
        {
            return;
        }

        void log( const Level, const char* format, ... )
        {
            va_list arguments;
            va_start( arguments, format );
            vfprintf( stderr, format, arguments );
            fprintf( stderr, "\n" );
            va_end( arguments );
        }

        void log_if( bool expression, const Level level, const char* format, ... )
        {
            if ( expression )
            {
                va_list arguments;
                va_start( arguments, format );
                log( level, format, arguments );
                va_end( arguments );
            }
        }
};


int main( const int argc , const char** argv)
{
    Service service;
    auto print_get =  []( const shared_ptr< Session > session ){
            std::string body = "Hello GET";
            session->close( OK, body, { { "Content-Length", ::to_string( body.length( ) ) } } );

        };
    auto print_post =  []( const shared_ptr< Session > session ){
            std::string body = "Hello POST";
            session->close( OK, body, { { "Content-Length", ::to_string( body.length( ) ) } } );

        };

    {
        auto resource = make_shared< Resource >( );
        resource->set_path("/hello/{language:[a-z_]+}");
        resource->set_method_handler( "GET" , print_get);
        service.publish(resource);
    }

    {
        auto resource = make_shared< Resource >( );
        resource->set_path("/hello/{language:[ab-z_]+}");
        resource->set_method_handler( "POST" , print_post);
        service.publish(resource);
    }

    auto settings = make_shared< Settings >( );

    settings->set_port( 1984 );
    service.set_logger( make_shared< CustomLogger >( ) );

    settings->set_default_header( "Connection", "close" );
    service.start( settings );

    return EXIT_SUCCESS;
}

```

# Invoke method:
curl --header "Content-Type: application/json" --data "some text" --request POST localhost:1984/hello/english 
And the log is: Incoming 'POST' request from '[::1]:61094' for route '/hello/english'. '[::1]:61094' 'POST' method not allowed '/hello/english'. 

-------------------

Running on MacOS, High Seirra,
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
# revision:
```
commit 03f1f2391fc8cd00f599ea368e472f1455bd575c (HEAD -> master, origin/master, origin/HEAD)
Merge: 68b302e 3f3da08
Author: Ben Crowhurst <ben.crowhurst@corvusoft.co.uk>
Date:   Sun Mar 1 17:48:38 2020 +1100

    Merge pull request #409 from Corvusoft/4.7

    4.7 Release Candidate One.
```
Thanks

**Comment by lifeibin** [comment]
I have the same problem. But when I run this project, the error is:
terminate called after throwing an instance of 'std::invalid_argument',  what():  Resource would pollute namespace. Please ensure all published resources have unique paths.
my code is:
	auto resource_get = make_shared< Resource >();
    resource_get->set_path(serverPath);
	resource_get->set_method_handler("GET", { { "Content-Type", "application/json"}}, get_method_handler);
	
	auto resource_post = make_shared< Resource>();
	resource_post->set_path(serverPath);
	resource_post->set_method_handler( "POST", { { "Content-Type", "application/json"}}, post_method_handler);
	
	auto resource_put = make_shared< Resource >();	
	resource_put->set_path(serverPath);
	resource_put->set_method_handler("PUT",{ { "Content-Type", "application/json"}},put_method_handler);
	
	auto resource_delete = make_shared< Resource >();
	resource_delete->set_path(serverPath);
	resource_delete->set_method_handler("DELETE", { { "Content-Type", "application/json"}}, delete_method_handler);
	
    auto settings = make_shared< Settings >( );
    settings->set_port(serverPort);
	
    Service service;
    service.publish(resource_get);
    service.publish(resource_post);
	service.publish(resource_put);
    service.publish(resource_delete);

I don't know how to modify the error.

**Comment by ben-crowhurst** [comment]
Thanks, I'll take a look this week.

Which version of Restbed are you using?

**Comment by phforest** [comment]
Hi, the revision is in the initial post under revision:
commit 03f1f2391fc8cd00f599ea368e472f1455bd575c

**Comment by ben-crowhurst** [comment]
Hey sorry for the delay.  This is by design as once Restbed has located a resource it won't search for another with a matching path.  

The solution you want is as follows.

``` C++
        auto resource = make_shared< Resource >( );
        resource->set_path("/hello/{language:[a-z_]+}");
        resource->set_method_handler( "GET" , print_get);
        resource->set_method_handler( "POST" , print_post);
        service.publish(resource);
```
