### ISSUE TITLE
4.7 RC1 Windows 10 Visual Studio 2017 HTTPS sample exception

### ISSUE THREAD

**Issue by danieljpb** [Corvusoft/restbed#414]
First when try to compile the BUILD_SSL=TRUE PreprocessorDefinitions is not added by cmake to vs  project file, after add manually when run this example:

https://github.com/Corvusoft/restbed/blob/master/documentation/example/HTTPS_SERVICE.md

I get a exception when call the from web browser

| Name | Value | Type
- | - | - | -
◢ | this | 0x0000000000000000 <NULL> | asio :: basic_io_object <asio :: detail :: win_iocp_socket_service <asio :: ip :: tcp>> *
| service_ | <Cannot read memory> |
| ◢ implementation_ | {protocol _ = {family _ = ??? } have_remote_endpoint _ = ??? remote_endpoint _ = {impl _ = {data _ = {base = {sa_family = ...} ...}}}} | asio :: detail :: win_iocp_socket_service <asio :: ip :: tcp> :: implementation_type
| ▶ asio :: detail :: win_iocp_socket_service_base :: base_implementation_type | {socket _ = ??? state _ = ??? cancel_token _ = {...} ...} | asio :: detail :: win_iocp_socket_service_base :: base_implementation_type
| ◢ protocol_ | {family _ = ??? } | asio :: ip :: tcp
| family_ | <Cannot read memory> |
| have_remote_endpoint_ | <Cannot read memory> |
| ◢ remote_endpoint_ | {impl _ = {data _ = {base = {sa_family = ??? sa_data = 0x000000000000004a <Error reading the characters in the string.>} ...}}} | asio :: ip :: basic_endpoint <asio :: ip :: tcp>
| ▶ impl_ | {data _ = {base = {sa_family = ??? sa_data = 0x000000000000004a <Error reading the characters in the string.>} ...}} | asio :: ip :: detail :: endpoint

Thanks

Best Regards

**Comment by ben-crowhurst** [comment]
Please try the VCSPKG supported by Microsoft.
