### ISSUE TITLE
http_client cannot afford to work 

### ISSUE THREAD

**Issue by lifeibin** [Corvusoft/restbed#416]
I use the http_client of the examples with the POST method, but it cannot afford to work. Here is the coed.
void print( const shared_ptr< Response >& response )
{
    fprintf( stderr, "*** Response ***\n" );
    fprintf( stderr, "Status Code:    %i\n", response->get_status_code( ) );
    fprintf( stderr, "Status Message: %s\n", response->get_status_message( ).data( ) );
    fprintf( stderr, "HTTP Version:   %.1f\n", response->get_version( ) );
    fprintf( stderr, "HTTP Protocol:  %s\n", response->get_protocol( ).data( ) );

    for ( const auto header : response->get_headers( ) )
    {
        fprintf( stderr, "Header '%s' > '%s'\n", header.first.data( ), header.second.data( ) );
    }

    auto length = response->get_header( "Content-Length", 0 );
    std::string authendicate = response->get_header("WWW-Authenticate");
    printf("authendicate content:%s\n", authendicate.c_str());
    if(!authendicate.empty())
    {
	std::string str;
	int pos1 = authendicate.find("nonce=");
    	int pos2 = authendicate.find_last_of(",");
    	str = authendicate.substr(pos1+6,pos2-pos1-6);
    	printf("%s",str.c_str());
    	printf("\n");
    }
    Http::fetch( length, response );

    fprintf( stderr, "Body:           %.*s...\n\n", 25, response->get_body( ).data( ) );
}

//
int main( const int, const char** )
{
	auto request = make_shared<Request>(Uri("http://10.0.0.108:12121/VIID/Images"));
	
	request->set_method("POST");
	cout<<"request:"<<request->get_path()<<endl;

	Json::Value imageInfo;
	Json::Value imageList;
	Json::Value images;
	Json::FastWriter writer;
	images["ImageID"] = "3100101000050080000000220200326141342000001";
	imageInfo["ImageInfo"] = images;
	imageList.append(imageInfo);

	std::string res = writer.write(imageList);
	
	std::cout<<"res:"<<res<<endl;

	request->set_headers({
                {"Content-Type", "application/json"},
	        {"Accept", "application/json"},
                {"Content-Length", std::to_string(res.size())},
                {"User-Identify", "admin"}
    }); 
	
	request->set_body(res);

    auto response = Http::sync(request);
    print(response);
    int status_code = response->get_status_code();
    cout<<"status_code:"<<status_code<<endl;

    return EXIT_SUCCESS;
}

I run the code and no response.

**Comment by ben-crowhurst** [comment]
@lifeibin sorry for the delay.

We aren't currently working on the client code as it hasn't made its way into version 5; we will however except bug fixes from the community.
