### ISSUE TITLE
CMake Build-Time Dependencies and Restbed static build failure.  Ref: Ver. 4.7-RC1

### ISSUE THREAD

**Issue by EchelonX-Ray** [Corvusoft/restbed#418]
**Restbed build fails if OpenSSL is not built with static-libs**.  It causes the cmake dependecy check to fail in "cmake/Findopenssl.cmake".  This occurs even if restbed is not built with static libs.  In fact, **Restbed will also fail to build if static-libs are enabled**.  So static-libs must be enabled for OpenSSL, but disabled for Restbed in order to build Restbed.  I've been hacking temporary fixes to make building work on my Gentoo system, but it would be nice if these issues were fixed up-stream.  Additionally, **Catch also seems to be required to build Restbed regardless of if tests are enabled**.  

Summary: It looks like a lot of the dependencies need to be cleaned up in CMake and there seems to be a linking issue when building Restbed with static-libs.

**Comment by ben-crowhurst** [comment]
@EchelonX-Ray can you confirm the was resolved in 4.7?

**Comment by ben-crowhurst** [comment]
Closing with no reply from @EchelonX-Ray.  If this issue continues please reopen with an updated status report, thanks.
