### ISSUE TITLE
https core dumped with restbed4.7

### ISSUE THREAD

**Issue by ygm521** [Corvusoft/restbed#419]
**environment:** CentOS Linux release 7.2.1511 (Core) , openssl-dependency-OpenSSL_1_1_1d.tar.gz  , restbed4.7

**# ls /usr/local/lib64/**
cmake  engines-1.1  libcrypto.a  libcrypto.so  libcrypto.so.1.1  libssl.a  libssl.so  libssl.so.1.1  pkgconfig

**vim restbed4.7/CMakeLists.txt**
	if ( BUILD_SSL )	
	#    target_link_libraries( ${SHARED_LIBRARY_NAME} LINK_PRIVATE ${ssl_LIBRARY_SHARED} ${crypto_LIBRARY_SHARED} )
		target_link_libraries( ${STATIC_LIBRARY_NAME} LINK_PRIVATE ${ssl_LIBRARY_STATIC} ${crypto_LIBRARY_STATIC} ${CMAKE_DL_LIBS} )
	else ( )
		target_link_libraries( ${SHARED_LIBRARY_NAME} )
		target_link_libraries( ${STATIC_LIBRARY_NAME} ${CMAKE_DL_LIBS} )
	endif ( )

**# g++ -v**
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 

**examlpe:**
# cat ssl_test.cpp 
	#include <memory>
	#include <cstdlib>
	#include <restbed>

	using namespace std;
	using namespace restbed;

	void get_method_handler( const shared_ptr< Session > session )
	{
		session->close( OK, "Hello, World!", { { "Content-Length", "13" }, { "Connection", "close" } } );
	}

	int main( const int, const char** )
	{
		auto resource = make_shared< Resource >( );
		resource->set_path( "/resource" );
		resource->set_method_handler( "GET", get_method_handler );
		
		auto ssl_settings = make_shared< SSLSettings >( );
		ssl_settings->set_http_disabled( true );
		ssl_settings->set_private_key( Uri( "file:///home/wbq/source/restapi/conf/cert/server.key" ) );
		ssl_settings->set_certificate( Uri( "file:///home/wbq/source/restapi/conf/cert/server.crt" ) );
		ssl_settings->set_temporary_diffie_hellman( Uri( "file:///home/wbq/source/restapi/conf/cert/dh768.pem" ) );
		
		auto settings = make_shared< Settings >( );
		settings->set_ssl_settings( ssl_settings );
		
		Service service;
		service.publish( resource );
		service.start( settings );
		
		return EXIT_SUCCESS;
	}

**Compile:**
	export LD_LIBRARY_PATH=/opt/rh/devtoolset-7/root/lib64:/usr/local/lib64/:$LD_LIBRARY_PATH
	cmake -DBUILD_TESTS=NO -DBUILD_EXAMPLES=NO -DBUILD_SSL=YES -DBUILD_SHARED=NO -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-7/root/bin/g++ ../

  
**run:**
	# ./rest_api 
	terminate called after throwing an instance of 'std::runtime_error'
	  what():  Not Implemented! Rebuild Restbed with SSL functionality enabled.
	**Aborted (core dumped)**

	**# ldd rest_api** 
	linux-vdso.so.1 =>  (0x00007ffd8bff3000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f436c6af000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f436c492000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f436c18a000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f436be88000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f436bc71000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f436b8b0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f436c8ee000)

**Comment by vennai** [comment]
1. Add try-catch
2. Build with cmake -DBUILD_SSL=YES

**Comment by pkarbovn** [comment]
There is a bug in socket_imp.cpp : 
in function SocketImpl::set_keep_alive( ... ) code uses m_socket ->native_handle()
m_socket is null when build with -DBUILD_SSL=YES
need to update : add
#ifdef BUILD_SSL
             auto& socket = ( m_socket not_eq nullptr ) ? *m_socket : m_ssl_socket->lowest_layer( );
#else
             auto& socket = *m_socket;
#endif
and replace m_socket-> to socket. where function uses m_socket->
ex:
setsockopt(socket.native_handle(), SOL_SOCKET, SO_KEEPALIVE, val.c_str(), sizeof(val));

**Comment by generatz** [comment]
@pkarbovn This fix worked for me, thanks. (But I don't see any file changes in your pull request.)

**Comment by ben-crowhurst** [comment]
Closing as this was resolved by commit https://github.com/Corvusoft/restbed/blame/ed83f454cda90a9f1dfa9e4284fa4a8383a687f0/source/corvusoft/restbed/detail/socket_impl.cpp#L280.
