### ISSUE TITLE
Callback function in authentication handler

### ISSUE THREAD

**Issue by GlowTube** [Corvusoft/restbed#424]
The function set_authentication_handler() takes a function address whose prototype is (shared_ptr to a Session, function reference to a callback). The callback address is mandatory, and from the examples, appears to be called if authentication is successful, with control returning to the handler afterwards. Since restbed is setting the callback address, I'm curious where (and what) it is? Also, is it mandatory for my code to call the callback? Thanks.

**Comment by ben-crowhurst** [comment]
Yes, Restbed is an async framework that requires to you call the next phase of success.
