### ISSUE TITLE
#include <restbed> No such file or directory

### ISSUE THREAD

**Issue by emulk** [Corvusoft/restbed#425]
Hello,
i have followed the instruction to compile and install restbed, but when i try to build my project on eclipse, or in a single file, i always get errore #include <restbed> No such file or directory

can someone help me ?  

I can't finde the directory /usr/local/lib/restbed on my pc

Thank you

**Comment by ben-crowhurst** [comment]
You need to have the include directory setup correct in your IDE of choice.
