### ISSUE TITLE
Client-side SSL certificates

### ISSUE THREAD

**Issue by ben-crowhurst** [Corvusoft/restbed#43]

**Comment by ydarma** [comment]
Hi, we would really appreciate this feature.
Thanks.

**Comment by ben-crowhurst** [comment]
@ydarma I must apologise. Somehow I completely missed your comment.  

All client functionality is moving over to the Restless project to help reduce complexity and misunderstanding of core concepts.

You'll see HTTP(s) functionality before the end of the year.

Once again I apologise for missing this.

**Comment by ben-crowhurst** [comment]
This issue has migrated to the [Restless](https://github.com/Corvusoft/restless/issues/5) project.
