### ISSUE TITLE
Does not build with Asio 1.13.0 and newer

### ISSUE THREAD

**Issue by podsvirov** [Corvusoft/restbed#431]
One of ressones is removing of methods like `get_io_service()`. For more info see [revision history](https://think-async.com/Asio/asio-1.16.1/doc/asio/history.html#asio.history.asio_1_13_0).

**Comment by MINIONBOTS** [comment]
Just replace  get_io_service() with get_executor().context() and you are good to go.
(one case you may have to static cast...I know I know, not pretty but does the job until the whole socketimpl was changed to the 'current asio structure'
m_io_service(static_cast<asio::io_context&>(socket->get_executor().context())),

**Comment by podsvirov** [comment]
Any news there? There tag or release that support latest asio?

**Comment by podsvirov** [comment]
Good news. Thank you!
