### ISSUE TITLE
Http Client Help wanted :D

### ISSUE THREAD

**Issue by belarusrulez** [Corvusoft/restbed#436]
Hello :D Hope you all doing good :) Help wanted here :D
I am trying to do post request to java spring boot server.
right now I faced issue.

I can't pass body. For some reason its not going thru. (I 100% know that string body is not empty)
I tried my java service using postman and it also works. I am able to send GET request but I need POST :D. I tried 3 ways to pass data. 3d one I've done I didn't use my body string just used char array and it didn't work also. 

Any clue how to fix this? Thank you for any advice :)

```
		static void sendCallBack(string const& path, string body) {
		string url = "http://localhost:8080/";
		auto request = make_shared< Request >(Uri(url + path));
		request->set_header("Accept", "*/*");
		request->set_method("POST");
		request->set_header("Host", "www.blabla.co.uk");
		request->set_header("Content-Type", "application/json");

// I tried all 3 separately one by one
		request->set_body(body);
		request->set_body(body.c_str());
		request->set_body(Bytes({ '{','}' }));

		auto response = Http::sync(request);
}
```

**Comment by mipac** [comment]
You need to add 'content-length' header
