### ISSUE TITLE
empty value for query parameters

### ISSUE THREAD

**Issue by gastineau** [Corvusoft/restbed#445]
Using the function get_query_parameters or get_query_parameter, there is no way to distinguish the two following uri:

....?param=param
....?param

If the sign = is not given (second case in my example), get_query_parameters  returns a multi map which contains 'param' as the value. If the symbol = is given, there is no problem, the value is and empty string.

**Comment by ben-crowhurst** [comment]
Sounds like a bug do you have a PR we can perhaps review?

**Comment by ben-crowhurst** [comment]
Looks to be caused here:
```C++
    multimap< string, string > Uri::get_query_parameters( void ) const
    {
        multimap< string, string > parameters;
        
        auto query = String::split( get_query( ), '&' );
        
        for ( auto parameter : query )
        {
            auto index = parameter.find_first_of( '=' );
            auto name = decode_parameter( parameter.substr( 0, index ) );
            auto value = decode_parameter( parameter.substr( index + 1, parameter.length( ) ) );
            
            parameters.insert( make_pair( name, value ) );
        }
        
        return parameters;
    }
```
