### ISSUE TITLE
Server_side_events example crashes

### ISSUE THREAD

**Issue by Knutselsmurf1** [Corvusoft/restbed#446]
I am using Ubuntu 20.04.1 LTS

I installed restbed:
$ sudo apt install librestbed-dev

I compiled the Server_Side_events example (https://github.com/Corvusoft/restbed/blob/master/documentation/example/SERVER_SIDE_EVENTS.md):
$ clang++ -o example example.cpp -l restbed
$ ./example

After I enter http://localhost:1984/stream or if I call the given client code in the example, the result is once:
   data: event [number]

However the application then crashes:
  Terminate called after throwing an instance of ‘std::bad_function_call’
     what():   bad_function_call
  Aborted (core dumped)

What is wrong?

**Comment by ben-crowhurst** [comment]
We require more information, can you supply a stack trace?

**Comment by ben-crowhurst** [comment]
Closing as no follow up from OP.
