### ISSUE TITLE
request->get_header("Content-Length", 0) as in README example issues error

### ISSUE THREAD

**Issue by Choongkyu** [Corvusoft/restbed#453]
hi. I tried building the example in the README but I run into this issue
```
more than one instance of overloaded function "restbed::Request::get_header" matches the argument list:

function "restbed::Request::get_header(const std::string &name, const std::string &default_value = "") const" (declared at line 101 of "/usr/include/corvusoft/restbed/request.hpp") -- 

function "restbed::Request::get_header(const std::string &name, const std::function<std::string (const std::string &)> &transform) const" (declared at line 103 of usr/include/corvusoft/restbed/request.hpp")
```
for this line:
```
int content_length = request->get_header(str, 0);
```
Thank you!

**Comment by sinpulse** [comment]
How did you install restbed? If you installed via linux based on the apt installer package I had the exact same error.  sudo apt remove librestbed-dev. 
Then follow these instructions(you can just do this from the home directory on linux)

Download the source code: 

git clone --recursive https://github.com/corvusorft/restbed.git 

Download the files https://github.com/Corvusoft/restbed/archive/master.zip 

`mkdir  restbed/build` 

`cd restbed/build` 

`cmake [-DBUILD_SSL=NO] ..` (if this command does not work try changing directory to restbed then run the step 4 command) 

`make install`  

`make test`  (if you are having troubles with this step try running 'make install' again then run make tests. For some reason this fixed the issue I was having) 

Copy (or move) the header and library files to the appropriate location 

From the `restbed` directory: 

`cp -r distribution/include/* /usr/local/include` will move the header files to your local include directory, which g++ knows to look in for headers 

`cp -a distribution/library/* /usr/local/lib` will move the library file to your local library directory, which, again, g++ knows to look in for libraries

**Comment by sinpulse** [comment]
Hey this may be of a bit of help specifically if you are on Linux. I had the same error. 
Start by removing your current install. sudo apt remove librestbed-dev. 

Then do the following(you can do it in the home directory)

Download the source code: 

git clone --recursive https://github.com/corvusorft/restbed.git 
(OR)
Download the files https://github.com/Corvusoft/restbed/archive/master.zip 

`mkdir  restbed/build` 

`cd restbed/build` 

`cmake [-DBUILD_SSL=NO] ..` (if this command does not work try changing directory to restbed then run the step 4 command) 

`make install`  

`make test`  (if you are having troubles with this step try running 'make install' again then run make tests. For some reason this fixed the issue I was having) 

Copy (or move) the header and library files to the appropriate location 

From the `restbed` directory: 

`cp -r distribution/include/* /usr/local/include` will move the header files to your local include directory, which g++ knows to look in for headers 

`cp -a distribution/library/* /usr/local/lib` will move the library file to your local library directory, which, again, g++ knows to look in for libraries 

Final Step:
sudo /sbin/ldconfig -v

**Comment by MikePooh** [comment]
The working copy of README exapmle should looks like following

**main.cpp**
```
#include <memory>
#include <cstdlib>
#include <restbed>

using namespace std;
using namespace restbed;

void post_method_handler(const shared_ptr<Session> session)
{
    const auto request = session->get_request( );
    int content_length = stoi(request->get_header("Content-Length"));
    session->fetch(content_length, [](const shared_ptr<Session> session, const Bytes& body)
    {
        fprintf(stdout, "%.*s\n", static_cast<int>(body.size()), body.data());
        session->close(OK, "Hello, World!", {{"Content-Length", "13"}});
    } );
}

int main(const int, const char**)
{
    auto resource = make_shared<Resource>();
    resource->set_path("/resource");
    resource->set_method_handler("POST", post_method_handler);

    auto settings = make_shared<Settings>();
    settings->set_bind_address("127.0.0.1");
    settings->set_port(1984);
    settings->set_default_header("Connection", "close");

    Service service;
    service.publish(resource);
    service.start(settings);

    return EXIT_SUCCESS;
}
```
**CMakeLists.txt**
```
cmake_minimum_required(VERSION 3.5)

project(testrestbed LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include_directories(/home/mike/projects/restbed/distribution/include)
link_directories(/home/mike/projects/restbed/distribution/library)

add_executable(testrestbed main.cpp)
target_link_libraries(testrestbed restbed)
```
