### ISSUE TITLE
The example of https service in CentOS8.3/restbed(master) fail

### ISSUE THREAD

**Issue by russwu** [Corvusoft/restbed#456]
-Prorgam from example :
-----------------------------------------------------
#include <memory>
#include <cstdlib>
#include <restbed>

using namespace std;
using namespace restbed;

void get_method_handler( const shared_ptr< Session > session )
{
    session->close( OK, "Hello, World!", { { "Content-Length", "13" }, { "Connection", "close" } } );
}

int main( const int, const char** )
{
    auto resource = make_shared< Resource >( );
    resource->set_path( "/resource" );
    resource->set_method_handler( "GET", get_method_handler );
    
    auto ssl_settings = make_shared< SSLSettings >( );
    ssl_settings->set_http_disabled( true );
    ssl_settings->set_private_key( Uri( "file:///tmp/server.key" ) );
    ssl_settings->set_certificate( Uri( "file:///tmp/server.crt" ) );
    ssl_settings->set_temporary_diffie_hellman( Uri( "file:///tmp/dh2048.pem" ) );
    
    auto settings = make_shared< Settings >( );
    settings->set_ssl_settings( ssl_settings );
    
    Service service;
    service.publish( resource );
    service.start( settings );
    
    return EXIT_SUCCESS;
}

--git checkout restbed master branch--
mkdir build
cd build
cmake -DBUILD_SSL=YES ..
-----The cmake prompt ----------------
-- The CXX compiler identification is GNU 8.3.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

##############################################################
#                                                            #
#  Copyright 2013-2020, Corvusoft Ltd, All Rights Reserved.  #
#                                                            #
#  Restbed is dual-licensed requiring commerical entities    #
#  to acquire a Corvusoft Permissive License, Contact        #
#  sales@corvusoft.co.uk for details.                        #
#                                                            #
##############################################################

-- Found ASIO include at: /root/restbed/dependency/asio/asio/include
-- Found OpenSSL include at: /root/restbed/dependency/openssl/include
-- Found OpenSSL library at: /root/restbed/dependency/openssl/libssl.a
-- Found OpenSSL library at: /root/restbed/dependency/openssl/libssl.so
-- Found Crypto library at: /root/restbed/dependency/openssl/libcrypto.a
-- Found Crypto library at: /root/restbed/dependency/openssl/libcrypto.so
-- Found catch: /root/restbed/dependency/catch/single_include/catch2
-- The C compiler identification is GNU 8.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-----Setup self certifcated key and pem -----------------------------------------------------------
openssl genrsa -out server.key 2048
openssl req -new -key server.key -out server.csr
openssl x509 -req -days 3650 -in server.csr -signkey server.key -out server.crt
openssl dhparam -out dh2048.pem 2048
-------build the https_service.cpp samples program ----------------
g++ -o https_service https_service.cpp -l restbed -l ssl -l crypt -DBUILD_SSL
-----Everything is Fine till now ---------------------------------------------------------------------
 ./https_service
----Prompt as below ：
terminate called after throwing an instance of 'std::runtime_error'
  what():  Not Implemented! Rebuild Restbed with SSL functionality enabled.
[1]    85156 abort (core dumped)  ./https_service

**Comment by russwu** [comment]
I have already set the DBUILD_SSL=YES. and successfully build the restbed . Why the prompt still show" Not Implemented! Rebuild Restbed with SSL functionality enabled." ?

**Comment by russwu** [comment]
I have updated base on below comments in previous issue , but the problem is the same .
---
update : add
#ifdef BUILD_SSL
auto& socket = ( m_socket not_eq nullptr ) ? *m_socket : m_ssl_socket->lowest_layer( );
#else
auto& socket = *m_socket;
#endif
and replace m_socket-> to socket. where function uses m_socket->

**Comment by ben-crowhurst** [comment]
The library must be built with SSL enabled.

`what(): Not Implemented! Rebuild Restbed with SSL functionality enabled.`
