### ISSUE TITLE
Custom transtort

### ISSUE THREAD

**Issue by radozd** [Corvusoft/restbed#460]
Hello,
I'd like to use restbed library with my custom transport, i.e. not HTTP/HTTPS/WebSocket.
Is there any simple way of doing this?
I saw the old mention of "add_application_layer" like methods, but nothing like this exists in the source code.
Thanks in advance

**Comment by Jahrenski** [comment]
The application layer feature is not due before v5 I believe.

**Comment by radozd** [comment]
Too bad. It was promised in 2016. Different lib then.

**Comment by Jahrenski** [comment]
I would stick around if you plan on using a C++ Rest Api server. The alternatives are not that great to be honest.
cpprestsdk by Microsoft was the only real contender besides Restbed but its ssl management is very difficult to say the least. Also it's very basic. Not nearly enough features to help you out.
For the linux crowd, Pistache is an option, but this isn't an option for us.

Restbed has implemented 5.0 using the upcoming Networking TS which is scheduled for c++20.
[https://en.wikipedia.org/wiki/C%2B%2B20#Published_as_Technical_Specifications](https://en.wikipedia.org/wiki/C%2B%2B20#Published_as_Technical_Specifications)

**Comment by radozd** [comment]
I'm done with restbed. Restinio is better in many aspects. Fits perfectly to my tasks. Better license too.
