### ISSUE TITLE
Post handling example and a few notice

### ISSUE THREAD

**Issue by RoyBellingan** [Corvusoft/restbed#462]
Hi, Please can you add a small disclaimer that the fetch operation, well is ASYNC...
So please add just a small notice in https://github.com/Corvusoft/restbed/blob/03f1f2391fc8cd00f599ea368e472f1455bd575c/documentation/example/HTTP_SERVICE.md

That says please do not execute code that depends on fetch.

https://gist.github.com/RoyBellingan/ba9a1ab6af13f8a0a2970fbe74d1e3c9

I added two notes like

    //This is an async operation, so will be scheduled to be performed AFTER the post data is ready
and
    //Function will now return, and depending on the post size the lambda is probably still scheduled to be executed!

**Comment by ben-crowhurst** [comment]
Restbed is designed for async-processing, any method with a callback will be performed after the outer function has performed its duties.

We will attempt to make this architectural decision clearer, thanks.
