### ISSUE TITLE
Http class deprecated problem

### ISSUE THREAD

**Issue by TaeZStkyoht** [Corvusoft/restbed#464]
Making deprecated of "Http" class causes errors below. Please remove useless forward and friend declarations of it from "request.hpp" and "response.hpp", or remove deprecated tag from the definition. My OS is Windows.

blabla\include\corvusoft\restbed\request.hpp(172,20): error C4996: 'restbed::Http': HTTP client is deprecated; we will release a complimentary client framework at a future date.
blabla\include\corvusoft\restbed\response.hpp(119,20): error C4996: 'restbed::Http': HTTP client is deprecated; we will release a complimentary client framework at a future date.

**Comment by ben-crowhurst** [comment]
Will strip the HTTP client functionality in the upcoming release.

**Comment by mirkomaga** [comment]
How can I fix it?
