### ISSUE TITLE
Can't get path parameters in authentication_handler

### ISSUE THREAD

**Issue by TaeZStkyoht** [Corvusoft/restbed#465]
I can get data from both get_path_parameter and get_path_parameters in for example my get method handler. It's ok. However, in authentication_handler, get_path_parameter and get_path_parameters returns no data. Nonetheless, get_path still works in authentication_handler. I can split and use it for making a work around solution. But should it be like that? Is it a bug? I just wanted to bypass some calls like user/login etc. from checking authentication (bearer token checks etc.).

**Comment by ben-crowhurst** [comment]
The logic here is to do the minimal amount of processing prior to authentication for security reasons, don't trust the user input prior to verification; path is delivered in the HTTP Request and requires no processing.

**Comment by TaeZStkyoht** [comment]
Nevertheless, I should bypass some calls (user/login etc.) which are not needed to be checked by a token. Therefore, in the authentication_handler function which is set by set_authentication_handler function, I should get path parameters to check this call needs an authentication or not. As I said, I found a workaround solution, request->get_path() is still working in the authentication_handler function and I can parse path with '/' character to get path parameters; however, get_path_parameters() is not working. After calling "callback(session);" at the end of authentication_handler function, in the method_handler function which is set by set_method_handler function, I can use both of them. So, I thought it was a bug and still thinking like that; but it's OK. People who has the problem like that can use my workaround solution.

**Comment by ben-crowhurst** [comment]
Thanks, @TaeZStkyoht for your understanding.  We like to have a security-first mindset here, perform as little action as possible until the peer has been identified; reducing attack vectors.
