### ISSUE TITLE
Download breaks when large binary body is sent

### ISSUE THREAD

**Issue by m-peko** [Corvusoft/restbed#467]
Hi there,

I want to send back a bit larger binary data ( 20MB and above ) on GET request but the download breaks with the following messages:

- when using CURL:

> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                                    Dload     Upload  Total    Spent    Left   Speed
> 7 20.6M    7 1535k    0     0   215k      0  0:01:37  0:00:07  0:01:30  280k
>  curl: (18) transfer closed with 20042572 bytes remaining to read

- when using wget:

> HTTP request sent, awaiting response... 200 OK                                                                                                                                                        [0/115]
Length: 21614584 (21M) [application/octet-stream]
Saving to: ‘12’
>
> 12                                                    6%[======>                                                                                                          ]   1.37M   315KB/s    in 5.3s
>
> 2021-03-10 22:02:31 (264 KB/s) - Connection closed at byte 1440790. Retrying.

Headers I send are:

```
Content-Type: application/octet-stream
Content-Length: 21614584
```

Here is the code:

```c++
void Api::download( std::shared_ptr< restbed::Session > const & session ) const
{
    auto const request = session->get_request();
    auto const uuid    = request->get_path_parameter("uuid");

    std::vector< std::uint8_t > data;
    // fill the data

    session->close
    (
        StatusCode::Ok,
        data,
        {
             { "Content-Type"  , "application/octet-stream"          },
             { "Content-Length", std::to_string( std::size( data ) ) }
        }
    );
}
```

I have tried sending hex data too but same issue occurs.

OS: Ubuntu
Restbed tag: `1db9d8785fd287a7a59565610346cb08cf541cbd` (last commit that I am using - cannot use newer because I am stuck on C++11)

Thank you on your help!

**Comment by m-peko** [comment]
I have also tried with 

```c++
session->yield
(
    StatusCode::Ok,
    data,
    {
        { "Content-Type"  , "application/octet-stream"          },
        { "Content-Length", std::to_string( std::size( data ) ) }
    }
);
session->close();
```

but the same issue occurs.

**Comment by m-peko** [comment]
Following results with the same issue too:

```c++
session->yield
(
    StatusCode::Ok,
    records,
    {
        { "Connection"    , "keep-alive"                        },
        { "Content-Type"  , "application/octet-stream"          },
        { "Content-Length", std::to_string( std::size( data ) ) }
    },
    []( std::shared_ptr< restbed::Session > const & s )
    {
        s->close();
    }
);
```

**Comment by m-peko** [comment]
@ben-crowhurst any idea regarding this issue?

**Comment by ben-crowhurst** [comment]
What did the client-side code look like?

**Comment by ben-crowhurst** [comment]
Could you provide a complete server-side code example? Configurations settings, the full bhuna?

**Comment by m-peko** [comment]
Here are the client-side commands:
- curl: `curl -i -G -H "Accept: application/octet-stream" --output resp.bin '<ip-address>:5060/api/data/1'`
- wget: `wget <ip-address>:5060/api/data/1` (have also tried with `--continue` but didn't help)

and here are the settings:

```c++
auto settings = std::make_shared< restbed::Settings >();
settings->set_port( port_ );
settings->set_bind_address( "0.0.0.0" );
settings->set_default_header( "Connection", "close" ); // i have also tried without this default header

service_ = std::make_unique< restbed::Service >();

auto data_id = std::make_shared< restbed::Resource >();
records_uuid->set_path( "/api/data/{id: .*}" );
records_uuid->set_method_handler( "GET"   , std::bind( &Api::download , this, std::placeholders::_1 ) );

service_->publish( data_id );
```

**Comment by ben-crowhurst** [comment]
Hmm performed a test on the loopback interface and saw no issue, will try from further afield.

**Comment by m-peko** [comment]
@ben-crowhurst i am trying to send raw PCAP file, i.e. its binary data, so this info might help you. You can try downloading a random PCAP file from internet. Maybe the bytes within the PCAP file are causing the session to close.

**Comment by m-peko** [comment]
@ben-crowhurst and please make sure you perform test on data >= 20MB.

**Comment by m-peko** [comment]
Ok, I realized that when downloading from the machine where the API runs, everything works perfectly fine. But when downloading from any other machine, connections breaks.

**Comment by m-peko** [comment]
I am closing this issue as it seems that the 3rd example i posted here is working and i obviously have problem in networking.

Thanks for your help!
