### ISSUE TITLE
how to achieve file upload and download

### ISSUE THREAD

**Issue by Uangski** [Corvusoft/restbed#468]
could provide some test example，please!

**Comment by Jahrenski** [comment]
Have you checked in the examples?
[https://github.com/Corvusoft/restbed/tree/master/documentation/example](https://github.com/Corvusoft/restbed/tree/master/documentation/example)

Check both TRANSFER_ENCODING_REQUEST.md and TRANSFER_ENCODING_RESPONSE to see if it helps you.
