### ISSUE TITLE
Uri() crashes with a file path including spaces

### ISSUE THREAD

**Issue by Jahrenski** [Corvusoft/restbed#469]
When passing the Uri to the set_private_key() function it crashes because the path is said to be invalid.
Yet, on windows, spaces in a path are valid.

Uri("file://C:/Program Files/RestServer/key.pem") //This crashes.

Edit: 
I should note that without a space it's all fine
Uri("file://C:/RestServer/key.pem")

**Comment by ben-crowhurst** [comment]
Do you have any further details regarding the crash report?

**Comment by Jahrenski** [comment]
It is thrown by the Uri::Uri() constructor judging the string invalid
throw invalid_argument( "Argument is not a valid URI: " + value );

But on windows, spaces in paths should be valid.

**Comment by ben-crowhurst** [comment]
URI class is intended to be an implementation that follows [RFC 1738](https://tools.ietf.org/html/rfc1738).  Not OS specific filesystem details.

**Comment by Jahrenski** [comment]
Sounds good, will convert all spaces to %20. Thanks.

**Comment by Jahrenski** [comment]
Sorry to bother but %20 still makes it crash. In context::use_certificate_file  this time.
Uri("file://C:/Program%20Files/RestServer/key.pem");

Our users will be able to setup this restapi server anywhere on their machine including in a folder with spaces in it.
Is there any way to make this happen without requiring our users to serve their certificate though a webserver?

**Comment by ben-crowhurst** [comment]
OK, thanks @Jahrenski.  We'll take a look for the 4.8 release.

**Comment by ben-crowhurst** [comment]
@Jahrenski OK so here is the suggested fix.
We will URL Decode the string inside the set_private_key, and associated, method.

``` C++
 void SSLSettings::set_private_key( const Uri& value )
 {
    m_pimpl->m_private_key = Uri::decode(String::remove( "file://", value.to_string( ), String::CASE_INSENSITIVE ));
 }
```

**Comment by ben-crowhurst** [comment]
@Jahrenski let us know how it goes.

https://github.com/Corvusoft/restbed/blob/master/test/regression/source/ssl_settings_to_handle_windows_paths.cpp
