### ISSUE TITLE
trouble running the https example

### ISSUE THREAD

**Issue by CosicK** [Corvusoft/restbed#470]
I have been using restbed to code a REST API on a Respberry Pi Desktop in Virtualbox. I deactivated the unit tests and the secure socket layer support for the first implementation but now I want to implement https.
I installed another Raspberry Pi Desktop with more RAM, to have enough space to install everything. I am not very experienced, so I kept looking for solutions but nothing has helped me so far.

/////////////////////OS////////////////////////////

Type: Linux, Debian 32-bit
RAM: 5GB
hard disk: 16GB
Image: 2021-01-11-raspios-buster-i386.iso

/////////////////////START//////////////////////////////////

git clone --recursive https://github.com/corvusoft/restbed.git
mkdir restbed/build
cd restbed/build

/////////////////////FIRST ERROR FROM CMAKE/////////////////////////

pi@raspberry:~/restbed/build $ cmake -DBUILD_SSL=YES -DBUILD_TESTS=YES ..
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
                                             
Copyright 2013-2020, Corvusoft Ltd, All Rights Reserved.  
                                                            
Restbed is dual-licensed requiring commerical entities    
to acquire a Corvusoft Permissive License, Contact        
sales@corvusoft.co.uk for details.                        
                                                              
-- Found ASIO include at: /home/pi/restbed/dependency/asio/asio/include
CMake Error at cmake/Findopenssl.cmake:22 (message):
  Failed to locate OpenSSL dependency.  see restbed/dependency/openssl
Call Stack (most recent call first):
  CMakeLists.txt:58 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pi/restbed/build/CMakeFiles/CMakeOutput.log".

////////////////////////SOLUTION?///////////////////////////

LINK: https://stackoverflow.com/questions/54623729/findopenssl-cmake-fails-to-find-openssl-compiling-restbed-c
sudo apt-get update -y 
sudo apt-get install -y libssl-dev
cd restbed/dependency/openssl
./config; make

///////////////////////FURTHER BUILD///////////////////////////

sudo apt-get -y install cmake

mkdir restbed/build
cd restbed/build/
cmake -DBUILD_SSL=YES -DBUILD_TESTS=YES ..

pi@raspberry:~/restbed/build $ cmake -DBUILD_SSL=YES -DBUILD_TESTS=YES ..
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
                                                                                                                     
Copyright 2013-2020, Corvusoft Ltd, All Rights Reserved.  

Restbed is dual-licensed requiring commerical entities 
to acquire a Corvusoft Permissive License, Contact 
sales@corvusoft.co.uk for details.                        
                                                              
-- Found ASIO include at: /home/pi/restbed/dependency/asio/asio/include
-- Found OpenSSL include at: /home/pi/restbed/dependency/openssl/include
-- Found OpenSSL library at: /home/pi/restbed/dependency/openssl/libssl.a
-- Found OpenSSL library at: /home/pi/restbed/dependency/openssl/libssl.so
-- Found Crypto library at: /home/pi/restbed/dependency/openssl/libcrypto.a
-- Found Crypto library at: /home/pi/restbed/dependency/openssl/libcrypto.so
-- Found catch: /home/pi/restbed/dependency/catch/single_include/catch2  
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/restbed/build

//////////////////////////////////INSTALL//////////////////////////////////

make install

test/integration/CMakeFiles/resource_integration_test_suite.dir/source/resource_suite.cpp.o
[100%] Linking CXX executable resource_integration_test_suite
[100%] Built target resource_integration_test_suite
Install the project...
-- Install configuration: ""
-- Installing: /home/pi/restbed/distribution/include/restbed
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/byte.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/common.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/context_placeholder.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/context_placeholder_base.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/context_value.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/http.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/logger.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/request.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/resource.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/response.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/rule.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/service.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/session.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/session_manager.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/settings.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/ssl_settings.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/status_code.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/string.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/uri.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/web_socket.hpp
-- Installing: /home/pi/restbed/distribution/include/corvusoft/restbed/web_socket_message.hpp
-- Installing: /home/pi/restbed/distribution/library/librestbed.a
-- Installing: /home/pi/restbed/distribution/library/librestbed.so.4.7
-- Installing: /home/pi/restbed/distribution/library/librestbed.so.4
-- Set runtime path of "/home/pi/restbed/distribution/library/librestbed.so.4.7" to ""
-- Installing: /home/pi/restbed/distribution/library/librestbed.so

///////////////////////////////TESTS////////////////////////////////////

make test

100% tests passed, 0 tests failed out of 115
Total Test time (real) =  25.53 sec

//////////////////////////////EXAMPLE////////////////////////////////////

sudo apt-get install clang
used example: https://github.com/Corvusoft/restbed/blob/master/documentation/example/HTTPS_SERVICE.md

clang++ -I"/home/pi/restbed/distribution/include" -I"/home/pi/restbed/dependency/openssl/include" -o example example.cpp -L"/home/pi/restbed/distribution/library" -lrestbed -L"/home/pi/restbed/dependency/openssl"-lssl -lcrypt

//////////////////////////////LIBRARY PATH/////////////////////////////////

LD_LIBRARY_PATH=/usr/lib
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/pi/restbed/distribution/library/
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/pi/restbed/dependency/openssl/include/
export LD_LIBRARY_PATH

/////////////////////////////IMPLEMENTATION ERROR/////////////////////////////

pi@raspberry:~/Documents $ ./example
terminate called after throwing an instance of 'std::runtime_error'
  what():  Not Implemented! Rebuild Restbed with SSL functionality enabled.
Aborted

pi@raspberry:~/Documents $ sudo LD_LIBRARY_PATH=/usr/lib:/home/pi/restbed/distribution/library/:/home/pi/restbed/dependency/openssl/include/ ./example
terminate called after throwing an instance of 'std::runtime_error'
  what():  Not Implemented! Rebuild Restbed with SSL functionality enabled.
Aborted

**Comment by ben-crowhurst** [comment]
You need to have a version of the library build with SSL enabled `BUILD_SSL=YES`.

**Comment by ben-crowhurst** [comment]
No, follow up from OP; closing.
