### ISSUE TITLE
Service::set_method_not_allowed_handler api documentation mistake

### ISSUE THREAD

**Issue by MikePooh** [Corvusoft/restbed#471]
![Снимок экрана в 2021-04-01 13-00-51](https://user-images.githubusercontent.com/31304969/113281125-d9911300-92ed-11eb-9a48-2a493c23c9b4.png)

**Comment by ben-crowhurst** [comment]
Thanks will make the change for 4.8.

**Comment by ben-crowhurst** [comment]
@MikePooh thanks for pointing this out... you might be the only person who has read the documentation :rofl:
