### ISSUE TITLE
Planning on a release ? :)

### ISSUE THREAD

**Issue by MJBGO** [Corvusoft/restbed#474]
Hello @ben-crowhurst,

Are you planning on releasing 4.8 soon to have all the lastest memory freeing fixes ?

Thanks for you work :)

**Comment by ben-crowhurst** [comment]
Yep will look to have a release cut before the end of this month, if not this week :+1:

**Comment by MJBGO** [comment]
Perfect thanks :)

**Comment by bencrowhurst** [comment]
Sorry for the delay, this is coming this week.

**Comment by ben-crowhurst** [comment]
Really, really sorry about the delay; pushing this out now!

**Comment by ben-crowhurst** [comment]
Sorry to keep pulling your chain with this.  We're waiting on sign-off from one customer and will stamp HEAD 4.8.

@MJBGO thanks for your patience.  Do you have a  by-me-a-beer or coffee app I can send you a drink while you wait?

**Comment by Jahrenski** [comment]
We are closing in the 4 months mark since initial ETA, any update on this release?

**Comment by ben-crowhurst** [comment]
Once again, sorry.  The atmosphere has now settled, this will be stamped 4.8 today.

**Comment by ben-crowhurst** [comment]
Pushed tag [4.8-RC1](https://github.com/Corvusoft/restbed/releases/tag/4.8-RC1), end of the week given no issues will stamp 4.8.

**Comment by ben-crowhurst** [comment]
4.8 Release has been bundled. https://github.com/Corvusoft/restbed/releases/tag/4.8
