### ISSUE TITLE
Chaining requests in POST handler

### ISSUE THREAD

**Issue by IsraelLencina** [Corvusoft/restbed#477]
Hi, i'm triying to chain a POST call in a POST call, it works, actually i can see the packets throw the net with wireshark.

The request is complete, and return:
```
*** Response ***
Status Code:    200
Status Message: OK
HTTP Version:   1.1
HTTP Protocol:  HTTP
Header 'content-length' > '36'
Header 'content-type' > 'application/json'
Header 'date' > 'Mon, 17 May 2021 07:28:44 GMT'
Header 'server' > 'gunicorn'
... (time)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Socket receive failed: 'End of file'
```

The problem comes when i try to get the body data, in this case is an "application/json", this is the request:
```
auto request = std::make_shared<restbed::Request>(restbed::Uri(correct_uril));
request->set_header("Accept", "application/json");
request->set_header("Content-type", "application/json");
request->set_header("Content-Length", longitud);
request->set_method("POST");
request->set_body(strbuf.GetString());
auto response_example = restbed::Http::sync(request);
```

When i call to print(response_example) the output is what have you seen at the beggining, i retrieve the header "content-length" it's correct, but when i do:
```
restbed::Http::fetch(length_response, response_mariquery);
auto body_response = response_mariquery->get_body().data();
```

body_response is empty.

Edit: The exception raises in "restbed::Http::fetch".
Edit2: Finally i've solved by fetch looking for "}\0" instead of length_response, i don't know if there is a bug or it's a compilation problem, but if you use the returned Content-length header value in fetch is not valid and due in this behaviour.

**Comment by ben-crowhurst** [comment]
Please don't use the HTTP client as it will be stripped from the repository in an upcoming release.

Try CURL or alternative clients.
