### ISSUE TITLE
project version

### ISSUE THREAD

**Issue by maggu2810** [Corvusoft/restbed#495]
The project version in the CMakeLists.txt is set to 4.7.0 in the current master and also in the 4.8 tag? Is this done by intention?

**Comment by maggu2810** [comment]
I must confess that I am negatively surprised that you do not even get a short answer.

I created a MSYS2 package for Restbed, so it could be installed (with all dependencies) easily for Windows developers.
I am pretty sure, the version is not correct but as upstream does not seem to care about it...
https://packages.msys2.org/base/mingw-w64-restbed

**Comment by ben-crowhurst** [comment]
Issue resolved.
