### ISSUE TITLE
It's possible compile restbed with boost::asio ?

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#51]
I have a large project which is already link with boost and boost::asio as static link, now I would like to integrate restbed into my project, but it's seems restbed is depends on non-boost::asio, it will causes the  conflict unless I wrapper the restbed as dynamic link.

So my question is  possible compile restbed with boost::asio ?

**Comment by ben-crowhurst** [comment]
Currently I'm afraid not.

We intend to remove ASIO altogether with the eventual release of the [C++ network library proposal](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4370.html).  This will therefore remove a project dependency, simplify building, and reduce maintenance.

If you'd like to create a pull request implementing this feature and the necessary build switches, we would not reject merging the requested feature.
