### ISSUE TITLE
Builds with Restbed lib fail, with missing OpenSSL symbols galore

### ISSUE THREAD

**Issue by Stokestack** [Corvusoft/restbed#521]
I built Restbed according to the (first, non-external libraries) instructions and the process appeared to complete without issue.

But upon attempting to build a test project, it fails with errors like:
```
[build] /usr/bin/ld: ../lib/librestbed.a(request.cpp.o): in function `asio::detail::posix_tss_ptr_create(unsigned int&)':
[build] request.cpp:(.text._ZN4asio6detail20posix_tss_ptr_createERj[_ZN4asio6detail20posix_tss_ptr_createERj]+0x14): undefined reference to `pthread_key_create'
[build] /usr/bin/ld: ../lib/librestbed.a(request.cpp.o): in function `asio::ssl::detail::openssl_init_base::do_init::~do_init()':
[build] request.cpp:(.text._ZN4asio3ssl6detail17openssl_init_base7do_initD2Ev[_ZN4asio3ssl6detail17openssl_init_base7do_initD5Ev]+0x10): undefined reference to `CONF_modules_unload'
```

This looks like ASIO and maybe OpenSSL, and there are no other libs in Restbed's distribution directory other than librestbed.*. So... I don't know what the problem is. The ASIO and OpenSSL subdirectories are present and populated under Restbed's dependency directory in the source tree.

**Comment by LukasWoodtli** [comment]
I think you need to link your test binary with OpenSSL and pthread (and maybe also to ASIO).
 Something like this:

```
target_compile_options(${YOUR_TARGET_NAME} PRIVATE -pthread)
target_link_libraries(${YOUR_TARGET_NAME} PRIVATE -pthread)

target_link_libraries(${YOUR_TARGET_NAME} PRIVATE ${ssl_LIBRARY_SHARED})

target_link_libraries(${YOUR_TARGET_NAME} PRIVATE ${crypto_LIBRARY_SHARED})
```

And maybe analogous for ASIO.

**Comment by Stokestack** [comment]
Thanks for the reply. Those dependencies are included in the Restbed source tree (and are in fact populated). I followed the build directions [here](https://github.com/Corvusoft/restbed) (for non-external libraries), so I wonder how this works for anyone.

**Comment by LukasWoodtli** [comment]
In a project of mine, I had to link to `pthread`. There I disable the use of SSL (for now) so I don't need to link these libraries.

```
target_link_libraries(${TARGET_NAME}
    PUBLIC
        restbed-shared
        -lpthread)
```

I'm not sure why it's not working without linking these dependencies. Basically It's there in the CMake project of restbed...

**Comment by Stokestack** [comment]
Thanks for that reply. I did eventually get it to work, expanding a bit on what you posted above. Somewhere I found a project that was linking against it with all of the following. I'll paste it here in case someone else has the problem.

I don't understand why this is necessary either since I would expect all this to be built into the Restbed lib. I'm not sure how much of it is even being executed, but oh well!

target_compile_options(Series2Server PRIVATE -pthread)
target_link_libraries(Series2Server PRIVATE -pthread)

```
# Set up ASIO
find_path( asio_INCLUDE asio.hpp HINTS "${CMAKE_CURRENT_SOURCE_DIR}/restbed/dependency/asio/asio/include")

if ( asio_INCLUDE )
    set( ASIO_FOUND TRUE )
    set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DASIO_STANDALONE=YES" )

    message( STATUS "${Green}Found ASIO include at: ${asio_INCLUDE}${Reset}" )
else ( )
    message( FATAL_ERROR "${Red}Failed to locate ASIO dependency.${Reset}" )
endif ( )

# Set up OpenSSL
find_library(ssl_LIBRARY ssl)
find_library(crypto_LIBRARY crypto)
find_path( ssl_INCLUDE openssl/ssl.h)

if ( ssl_INCLUDE AND ssl_LIBRARY AND crypto_LIBRARY )
    set( OPENSSL_FOUND TRUE )
    add_definitions( -DBUILD_SSL=TRUE )

    if ( APPLE AND BUILD_SSL )
        set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated-declarations" )
    endif( )

    message( STATUS "${Green}Found OpenSSL library at: ${ssl_LIBRARY}${Reset}" )
    message( STATUS "${Green}Found OpenSSL include at: ${ssl_INCLUDE}${Reset}" )
    message( STATUS "${Green}Found Crypto library at: ${crypto_LIBRARY}${Reset}" )
else( )
    message( FATAL_ERROR "${Red}Failed to locate OpenSSL dependency. see restbed/dependency/openssl; ./config shared; make all${Reset}" )
endif( )
```

**Comment by Stokestack** [comment]
I'm back to this issue now on Mac. My test project (which is basically just one of the provided examples) builds on Linux but not Mac. I get loads of errors like this:
```
/usr/bin/clang++ -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/Series2Server.dir/main.cpp.o -o Series2Server -L/Users/me/data/series2server/restbed/library -Wl,-rpath,/Users/me/data/series2server/restbed/library  -lrestbed  -pthread && :
[build] Undefined symbols for architecture x86_64:
[build]   "_BIO_ctrl", referenced from:
[build]       asio::ssl::detail::engine::map_error_code(std::__1::error_code&) const in librestbed.a(service_impl.cpp.o)
[build]       asio::ssl::detail::engine::map_error_code(std::__1::error_code&) const in librestbed.a(socket_impl.cpp.o)
```

I even used libtool to combine the OpenSSL and crypto libs into the openssl lib, and built Restbed with that. No difference. Kind of dead in the water on Mac at the moment.

**Comment by Stokestack** [comment]
Oddly enough this will build on Apple Silicon but not Intel. My test project is basically just one of the provided examples. I get loads of errors after the build command on Intel:

`/usr/bin/clang++ -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/Series2Server.dir/main.cpp.o -o Series2Server -L/Users/me/data/series2server/restbed/library -Wl,-rpath,/Users/me/data/series2server/restbed/library -lrestbed -pthread`

> [build] Undefined symbols for architecture x86_64: [build]
> "_BIO_ctrl", referenced from: [build]
> asio::ssl::detail::engine::map_error_code(std::__1::error_code&) const in librestbed.a(service_impl.cpp.o) [build]
> asio::ssl::detail::engine::map_error_code(std::__1::error_code&) const in librestbed.a(socket_impl.cpp.o)

I even used libtool to combine the OpenSSL and crypto libs into the openssl lib, and built Restbed with that. No difference. I'm perplexed as to why these are missing, when they should be statically linked into Restbed. And indeed the same code builds on Apple Silicon.

Here's the build command on Apple Silicon:

`/usr/bin/clang++ -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/Series2Server.dir/main.cpp.o -o Series2Server -L/Users/gavin/data/series2server/restbed/library -Wl,-rpath,/Users/gavin/data/series2server/restbed/library -lrestbed -pthread`

The only difference, aside from a point difference in Mac SDK and the ARM architecture directive, is that the Intel one has:

`-mmacosx-version-min=11.6`

**Comment by Stokestack** [comment]
Apparently I had a misconception that the OpenSSL libs would be folded into the Restbed lib. Moving them into my source tree and and adding link directives for them took care of the errors here.
