### ISSUE TITLE
Is there a way to start the server with a non-blocking call and continue working on the same thread?

### ISSUE THREAD

**Issue by lrodriguez14** [Corvusoft/restbed#523]
Hello,

Is there a way to start the http server with a non-blocking call? When the `.start()` function is called the code stops there, but I need to call more functions on the same thread after the server is up for my implementation.

Any help? @ben-crowhurst 

Regards,
-Leonardo R.

**Comment by ben-crowhurst** [comment]
Please review the documentation and examples with regard to the Service::ready_handler.
