### ISSUE TITLE
Why is the CMake config putting "std=gnu++14" in Clang invocations?

### ISSUE THREAD

**Issue by Stokestack** [Corvusoft/restbed#524]
Right now I can't build a project that uses Restbed on Mac. The failure appears to be due to a mismatch between GCC's std:: and Clang's. But I can't figure out why GCC is involved.

Can anyone tell me how "std=gnu++14" is ending up in the compiler command?

Thanks!

**Comment by Stokestack** [comment]
Thanks for that reference, but why does that specify **GNU**? And how do I get this thing to build on the Mac with Clang?

**Comment by ben-crowhurst** [comment]
Can you provide the exact build file you are using?  What set of commands are you invoking to get Restbed compiled on macOS?  The framework has been crossed compiled with GCC and Clang for years on macOS.

Perhaps a new issue has been raised, please provide more context?

**Comment by Stokestack** [comment]
Thanks for the response. I'm digging into it now, but it looks like that wasn't the problem. I did get Restbed itself to compile OK, and forgot to come back and update this issue.

Now I can't get my project to compile if it includes code generated by the OpenAPI generator for Restbed (perplexing std:: problems on both Mac and Linux), but that's not your responsibility.
