### ISSUE TITLE
How to compile restbed for x64 ?

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#53]
The VS project which generated from CMAKE just include the 32bit project, I'm created the X64 project which copy from the x86, but got the compile error :

Error	2	error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'	E:\Stacks\restbed\x64\Debug\uri.obj	1	1	restbed

**Comment by ben-crowhurst** [comment]
As stated on the landing page

```
For Microsoft Visual Studio instructions please see feature #17.
```

[Feature #17](https://github.com/Corvusoft/restbed/issues/17)
