### ISSUE TITLE
Is it possible to upload a file with Restbed?

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#55]
It's possible to use restbed to upload and download file ?

One more thing, I have been post a wiki for compile restbed with vs2013 for x64, please add it to install.md if you think it's useful.

Thanks

**Comment by ben-crowhurst** [comment]
File uploading is best achieved with [Transfer-Encoding](https://en.m.wikipedia.org/wiki/Chunked_transfer_encoding) see [example](https://github.com/Corvusoft/restbed/tree/master/example/transfer_encoding_request) in source tree.

Alternatively you could perform a post request.

**Comment by ben-crowhurst** [comment]
Do you have a link to the wiki describing Visual Studio 2013 build instructions?

**Comment by ben-crowhurst** [comment]
File uploading is best achieved with Transfer-Encoding see example in source tree.

Alternatively you could perform a post request.
