### ISSUE TITLE
Are there any HTTP(s) client examples?

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#56]
I'm sorry but I would like to know where has the example for implement a http/https client ?

Thanks.

**Comment by ben-crowhurst** [comment]
Just about to check in HTTP example, give me 10 minutes.  HTTPS example tomorrow morning, logic is already present.

**Comment by pengweichu** [comment]
Thanks, I have been read the http client source code, but I have a suggestion: please add the option allows set the request timeout.

**Comment by ben-crowhurst** [comment]
We'll investigate this proposal shortly.

``` C++
auto settings = make_shared< Settings >( );
settings->set_connection_limit( milliseconds( 30 ) );

Http::sync( const Request& request, const Settings& settings );
```

**Comment by ben-crowhurst** [comment]
@pengweichu Out of curiosity, we'd love to hear what you're building?

**Comment by pengweichu** [comment]
I use this for the servers communicate, for example, I have some servers, one central provides the REST API service, another servers use the HTTPS client connect to that server and call the REST API to get/post messages with central server.

For a scenario, if a server call a REST API but the central server doesn't respond, so the HTTPS client request will failed once the timeout, otherwise the request will blocking...

In the previous version I use the ZMQ to do that, now I want to replaced it by REST API.

**Comment by pengweichu** [comment]
@ben-crowhurst it's great code, thanks!

auto settings = make_shared< Settings >( );
settings->set_connection_limit( milliseconds( 30 ) );

Http::sync( const Request& request, const Settings& settings );

**Comment by ben-crowhurst** [comment]
HTTP(s) client examples are now available at [HTTP](https://github.com/Corvusoft/restbed/tree/master/example/http_client/source) and [HTTPS](https://github.com/Corvusoft/restbed/tree/master/example/https_client/source).

Move examples will follow.

**Comment by pengweichu** [comment]
Thanks very much, happy new year.

**Comment by ben-crowhurst** [comment]
You're welcome, Happy new year  :D
