### ISSUE TITLE
How to pass the class member function to resource->set_method_handler ?

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#57]
Sorry again, would you please show me an example of how to pass a class member function to `Resource::set_method_handler`.

**Comment by ben-crowhurst** [comment]
This can be achieved with [std::bind](http://en.cppreference.com/w/cpp/utility/functional/bind)

> The function template bind generates a forwarding call wrapper for f. Calling this wrapper is equivalent > to invoking f with some of its arguments bound to args.

```
Resource resource
resource.set_method_handler( "GET", bind( &MyRestfulServicel::read_resource_handler, this, _1 ) );
```

**Comment by zhanb** [comment]
> bind

: error: invalid use of ‘this’ in non-member function
