### ISSUE TITLE
Socket timeout for HTTP Client.

### ISSUE THREAD

**Issue by ben-crowhurst** [Corvusoft/restbed#58]
User @pengweichu has requested the ability to set socket timeout on HTTP client requests.

**Comment by ben-crowhurst** [comment]
@pengweichu A beta implementation of this will be pushed on 11th February 2016; we'll let you know when its available.

**Comment by ben-crowhurst** [comment]
@pengweichu This feature has now been implemented with commit https://github.com/Corvusoft/restbed/commit/3401dfec927cf90192f35fa96f5229a32393a86e, enjoy.

**Comment by pengweichu** [comment]
@ben-crowhurst Thank you very much! I will test it then feedback. Best regards,
