### ISSUE TITLE
Is there a response body limit for HTTPS?

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#59]
The following example returns 20,000 byte response, however 2k appears to be garbled.

``` C++
std::string body;
for ( int i = 0; i < 20000; i++ )
{
    body.push_back( 'a' );
}

const multimap< string, string > headers {
    { "Connection", "close" },
    { "Content-Length", std::to_string( body.length( ) ) }
};

session->close( restbed::OK, body, headers );
```

My web browser renders that result as follows:

![s1](https://cloud.githubusercontent.com/assets/12697283/12163201/66d607c4-b546-11e5-85c0-e78dbadcc75f.png)

**Comment by ben-crowhurst** [comment]
Happy to take ownership of this ticket.  I'll endeavour to investigate the cause this week and present a fix by the end of the month (January 2016).

**Comment by ben-crowhurst** [comment]
@pengweichu Can you present the client code you used to cause this issue?

**Comment by pengweichu** [comment]
I've just use the Google Chrome open https://localhost/resource then got the Chrome display wrong data.

The server code is below:



#include <memory>
#include <cstdlib>
#include <restbed>

		 using namespace std;
using namespace restbed;

void get_method_handler(const shared_ptr< Session > session)
{
	std::string body;
	for (int i = 0; i < 20000; i++)
	{
		body.push_back('a');
	}

	const multimap< string, string > headers{
		{ "Connection", "close" },
		{ "Content-Length", std::to_string(body.length()) }
	};

	session->close(restbed::OK, body, headers);
}

int main(const int, const char**)
{
	auto resource = make_shared< Resource >();
	resource->set_path("/resource");
	resource->set_method_handler("GET", get_method_handler);

	auto ssl_settings = make_shared< SSLSettings >();
	ssl_settings->set_http_disabled(true);
	ssl_settings->set_private_key(Uri("d://server.key"));
	ssl_settings->set_certificate(Uri("d://server.crt"));
	//	ssl_settings->set_temporary_diffie_hellman(Uri("file:///tmp/dh768.pem"));

	auto settings = make_shared< Settings >();
	settings->set_ssl_settings(ssl_settings);

	Service service;
	service.publish(resource);
	service.start(settings);

	return EXIT_SUCCESS;
}


[example.txt](https://github.com/Corvusoft/restbed/files/117143/example.txt)

**Comment by ben-crowhurst** [comment]
I've attempted to replicate this issue with the following test case; under curl, restbed::Http, wget, firefox, chrome, and safari clients with no luck.

``` C++
#include <map>
#include <thread>
#include <memory>
#include <chrono>
#include <functional>
#include <restbed>
#include <catch.hpp>

using namespace std;
using namespace restbed;

void get_handler( const shared_ptr< Session > session )
{
    std::string body;
    for ( int i = 0; i < 20000; i++ )
    {
        body.push_back( 'a' );
    }

    const std::multimap< string, string > headers {
        { "Connection", "close" },
        { "Content-Length", std::to_string( body.length( ) ) }
    };

    session->close( restbed::OK, body, headers );
}

TEST_CASE( "large response bodies being garbled", "[response]" )
{
    auto resource = make_shared< Resource >( );
    resource->set_path( "test" );
    resource->set_method_handler( "GET", get_handler );
    
    auto settings = make_shared< Settings >( );
    settings->set_port( 1984 );
    
    shared_ptr< thread > worker = nullptr;
    
    Service service;
    service.publish( resource );
    service.set_ready_handler( [ &worker ]( Service & service )
    {
        worker = make_shared< thread >( [ &service ] ( )
        {
            auto request = make_shared< Request >( );
            request->set_method( "GET" );
            request->set_port( 1984 );
            request->set_host( "localhost" );
            request->set_path( "/test" );
            
            auto response = Http::sync( request );
            
            REQUIRE( 200 == response->get_status_code( ) );
            Http::fetch( 20000, response );
            
            string actual;
            response->get_body( actual );
            
            string expectation( 20000, 'a' );
            
            REQUIRE( actual.length( ) == expectation.length( ) );
            REQUIRE( actual == expectation );

            service.stop( );
        } );
    } );
    service.start( settings );
    worker->join( );
}
```

Please present a complete test case and instructions for replicating this issue.

**Comment by ben-crowhurst** [comment]
Its been a long evening, but I believe I've found the cause of this issue; however I still have no means of testing it.  Please can you pull HEAD and attempt to run the above test case again.

**Comment by pengweichu** [comment]
@ben-crowhurst I have been recorded the crash as mp4 video, please download attached the files and remove .txt extension name then play it by video player you will see the issue.

I'm using the Visual Studio 2013 Ultimate with Update 5, Windows 10 Pro 64 bit, the example project is compile as X64, DEBUG, Multi-threaded Debug (/MTd).

Best regards,

[chrome.mp4.txt](https://github.com/Corvusoft/restbed/files/120148/chrome.mp4.txt)
[firefox.mp4.txt](https://github.com/Corvusoft/restbed/files/120149/firefox.mp4.txt)

**Comment by ben-crowhurst** [comment]
@pengweichu Have you pulled the latest source code?

**Comment by pengweichu** [comment]
@ben-crowhurst The llastest code is works fine, thanks!

**Comment by ben-crowhurst** [comment]
That's fantastic news! Thanks for all the help.
