### ISSUE TITLE
The https client crashed when the host can't be reached

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#60]
With examples/https_client, if change the URI and host to a unreachable host, the application is crashed.

For example:

    auto request = make_shared< Request >( Uri( "https://www.google.comnnn/" ) );
    request->set_header( "Accept", "*/*" );
    request->set_header( "Host", "www.google.comnnn" );

**Comment by ben-crowhurst** [comment]
Thanks do you have a suggested fix?

**Comment by pengweichu** [comment]
I'm sorry I don't debug it yet, but I will try.

Best regards,

**Comment by ben-crowhurst** [comment]
@pengweichu Is this a crash or is an exception thrown?

**Comment by pengweichu** [comment]
Please see attached screenshot.

![2](https://cloud.githubusercontent.com/assets/12697283/12382293/63a25fa4-bdd3-11e5-8475-68c34a2376f5.png)

**Comment by ben-crowhurst** [comment]
Please can you present a complete code example causing the fault?

**Comment by ben-crowhurst** [comment]
The exception you are seeing was one of runtime_error indicating that the host was not found.  If you attempt to try-catch you'll see the exception.

HEAD now has a refactored HTTP client implementation that will return a response status code of '0' and a body containing the error message; Content-Length and Content-Type headers are included also.

Documentation coming shortly.

**Comment by pengweichu** [comment]
@ben-crowhurst Thank you!
