### ISSUE TITLE
Session::get crashes if the "key" doesn't exists.

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#61]
``` C++
string value = session->get("mykey");
```

The application crashed when "mykey" does not exist, I would suggest just returning an empty string for this scenario or modifying the set function as
``` C++
bool get(const string & key, string & value);
```

**Comment by ben-crowhurst** [comment]
This is a known issue.  You can circumvent this situation with:

``` C++
if ( session->has( "my_key" ) )
{
   ... 
}
```

**Comment by ben-crowhurst** [comment]
@pengweichu Do you have any suggestions regarding this issue?

**Comment by pengweichu** [comment]
@ben-crowhurst thanks for your follow up, I just use it as your suggestion now.

Bet regards,

**Comment by ben-crowhurst** [comment]
After reviewing this ticket I can see the "crash" you speak of is in fact an exception of type std::out_of_range.  This is thrown as the key you attempt to retrieve doesn't exist.  This is the correct behaviour.

Please ensure you manage this situation with the example above or by employing a try-catch block.
