### ISSUE TITLE
Multiple log entries written for each request

### ISSUE THREAD

**Issue by terrymah** [Corvusoft/restbed#63]
If you create a server with mulitple resources, when a request comes in there is a log entry for each resource until it is handled.

For example, if you create 5 resources, and request the 1st, you see one log entry. Request the 2nd, and you see two log entries. And so on.

**Comment by ben-crowhurst** [comment]
I've confirmed this to be true.  Thank you for bringing this to my attention, I appreciate all the bug discoveries @terrymah.

**Comment by ben-crowhurst** [comment]
This situation has been resolved.
