### ISSUE TITLE
Performing a clean shutdown

### ISSUE THREAD

**Issue by dayn9t** [Corvusoft/restbed#65]
Is there a clean way to stop the restbed::Service?

**Comment by ben-crowhurst** [comment]
Service::stop.

If this is not working for you please present your code for review.

**Comment by pengweichu** [comment]
@ben-crowhurst I suggest the Service::start() doesn't blocked, in Service::start() function, just create a thread then return immediately. Likes below:



void Service::threadProc()
{
    while (!mThreadExit)
    {
      // do works
    }
}

void Service::start()
{
	mThread = std::shared_ptr<std::thread>(new std::thread(std::mem_fn(&Service::threadProc), this));
}

void Service::shutdown()
{
	mThreadExit = true;
}

void Service::join()
{
	if (mThread)
	{
		mThread->join();
	}
}

**Comment by ben-crowhurst** [comment]
Have you looked in to the Service::set_ready_handler? And Settings::set_worker_limit? No thread creation required.

**Comment by dayn9t** [comment]
@ben-crowhurst  I use a POST request to restart the service.

```
void post_method_handler( const shared_ptr< Session > session )
{
    service->stop();
}

```

It doesn't work. I try to use signal.

`raise(SIGTERM);`

I found that io_service did not handle this signal. It‘s a unclean shutdown.

**Comment by ben-crowhurst** [comment]
The following example worked without issue. Are you using version 3.5 or HEAD?

``` C++
#include <memory>
#include <cstdlib>
#include <restbed>

using namespace std;
using namespace restbed;

shared_ptr< Service > service = nullptr;

void post_method_handler( const shared_ptr< Session > session )
{
    service->stop( );
}

int main( const int, const char** )
{
    auto resource = make_shared< Resource >( );
    resource->set_path( "/resource" );
    resource->set_method_handler( "POST", post_method_handler );

    auto settings = make_shared< Settings >( );
    settings->set_port( 1984 );

    service = make_shared< Service >( );
    service->publish( resource );
    service->start( settings );

    return EXIT_SUCCESS;
}
```

**Comment by pengweichu** [comment]
@ben-crowhurst Currently the Service::Start function is blocked until the application exit. I suggest this function don't block just return immediately.

**Comment by dayn9t** [comment]
@ben-crowhurst Thank you. It works well,after a bugfix.

**Comment by ben-crowhurst** [comment]
@pengweichu There is no need for the Service::start not to block.  The Service::set_ready_handler and increasing the worker count keeps all threads within the service event loop.

**Comment by ben-crowhurst** [comment]
@dayn9t Thats good to hear.  What was the fix?

**Comment by dayn9t** [comment]
A deadlock in my code.

**Comment by ben-crowhurst** [comment]
@dayn9t  Good to hear.  Don't hesitate to get in touch if you have any further questions/issues.
