### ISSUE TITLE
How to set timeout to https client ? (refer to #58)

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#66]
Update: I'm sorry I just saw the #58 now.

=============================================

@ben-crowhurst  Hello, is there any way can set the timeout to https client ? In the source code, the Http::sync only accept the "SSLSettings" parameter, but the "set_connection_limit" is member of Settings, it's seems we can't set the timeout to https client by "set_connection_limit" ?

Thanks & Regards,

**Comment by ben-crowhurst** [comment]
This feature is pending and will be in the upcoming 4.0 release.  We're currently focusing on bugs over features, so this is at the back of the list for now.
