### ISSUE TITLE
Proposal: don't use not, not_eq instead the !, !=

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#70]
I have a proposal for last code, don't use the "not", "not_eq", "or", "and" to instead of the "!", "!=", "||" and "&&"", since some users still using the VS2013, the VS2013+UPDATE 5 doesn't support these word operator.

Thanks

**Comment by ben-crowhurst** [comment]
Our primary focus is readability not supporting 4 year old technology stacks.  We have plans to move to C++14 shortly.  I'd recommend you upgrade your tool chain.
