### ISSUE TITLE
Can't compile the std::promise with VS2013

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#71]
Sorry for my questions, but the last code can't compiled by VS2013 + UPDAE 5, the error is from below code:

            std::promise< const shared_ptr< Response > > result;
            result.set_value( request->m_pimpl->m_response );

It's seems can't use restbed with VS2013 anyway ?
The error message is:

1>  http.cpp
1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\future(413): error C2678: binary '=' : no operator found which takes a left-hand operand of type 'const std::shared_ptr<restbed::Response>' (or there is no acceptable conversion)
1>          D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\memory(613): could be 'std::shared_ptr<restbed::Response> &std::shared_ptr<restbed::Response>::operator =(const std::shared_ptr<restbed::Response> &) throw()'
1>          D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\memory(595): or       'std::shared_ptr<restbed::Response> &std::shared_ptr<restbed::Response>::operator =(std::shared_ptr<restbed::Response> &&) throw()'
1>          D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\memory(620): or       'std::shared_ptr<restbed::Response> &std::shared_ptr<restbed::Response>::operator =<restbed::Response>(const std::shared_ptr<restbed::Response> &) throw()'
1>          D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\memory(602): or       'std::shared_ptr<restbed::Response> &std::shared_ptr<restbed::Response>::operator =<restbed::Response>(std::shared_ptr<restbed::Response> &&) throw()'
1>          while trying to match the argument list '(const std::shared_ptr<restbed::Response>, const std::shared_ptr<restbed::Response>)'
1>          D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\future(409) : while compiling class template member function 'void std::_Associated_state<_Ty>::_Set_value_raw(_Ty &,std::unique_lock<std::mutex> *,bool)'
1>          with
1>          [
1>              _Ty=const std::shared_ptr<restbed::Response>
1>          ]
1>          D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\future(404) : see reference to function template instantiation 'void std::_Associated_state<_Ty>::_Set_value_raw(_Ty &,std::unique_lock<std::mutex> *,bool)' being compiled
1>          with
1>          [
1>              _Ty=const std::shared_ptr<restbed::Response>
1>          ]
1>          D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\future(1479) : see reference to class template instantiation 'std::_Associated_state<_Ty>' being compiled
1>          with
1>          [
1>              _Ty=const std::shared_ptr<restbed::Response>
1>          ]

**Comment by ben-crowhurst** [comment]
No need to apologise.  Restbed requires at least a C++11 complier.

https://msdn.microsoft.com/en-us/library/hh567368.aspx
