### ISSUE TITLE
Can't compile the restbed with VS2015 + UPDATE1

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#72]
Hello, I still got the errors with even with VS2015 + UPDATE 1:

E:\Stacks\restbed>cmake -DBUILD_SSL=ON -DBUILD_EXAMPLES=NO -G "Visual Studio 14 2015 Win64" -DBUILD_TESTS=NO -DBUILD_SHARED=NO
-- The C compiler identification is MSVC 19.0.23506.0
-- The CXX compiler identification is MSVC 19.0.23506.0
-- Check for working C compiler using: Visual Studio 14 2015 Win64
-- Check for working C compiler using: Visual Studio 14 2015 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 14 2015 Win64
-- Check for working CXX compiler using: Visual Studio 14 2015 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
   Copyright 2013-2016, Corvusoft Ltd, All Rights Reserved.
-- Found ASIO include at: E:/Stacks/restbed/dependency/asio/asio/include
-- Found OpenSSL library at: E:/Stacks/restbed/dependency/openssl/out32dll/ssleay32.lib
-- Found OpenSSL include at: E:/Stacks/restbed/dependency/openssl/inc32
-- Found Crypto library at: E:/Stacks/restbed/dependency/openssl/out32dll/libeay32.lib
-- Configuring done
-- Generating done
-- Build files have been written to: E:/Stacks/restbed

==========================================

1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>  Checking Build System
1>  CMake does not need to re-run because E:/Stacks/restbed/CMakeFiles/generate.stamp is up-to-date.
2>------ Rebuild All started: Project: restbed, Configuration: Debug x64 ------
2>  Building Custom Rule E:/Stacks/restbed/CMakeLists.txt
2>  CMake does not need to re-run because E:\Stacks\restbed\CMakeFiles\generate.stamp is up-to-date.
2>  uri.cpp
2>E:\Stacks\restbed\source\corvusoft\restbed\uri.cpp(221): warning C4244: 'return': conversion from 'int' to 'uint16_t', possible loss of data
2>  rule.cpp
2>  http.cpp
2>D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\future(380): error C2678: binary '=': no operator found which takes a left-hand operand of type 'const std::shared_ptr<restbed::Response>' (or there is no acceptable conversion)
2>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(570): note: could be 'std::shared_ptr<restbed::Response> &std::shared_ptr<restbed::Response>::operator =(const std::shared_ptr<restbed::Response> &) noexcept'
2>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(552): note: or       'std::shared_ptr<restbed::Response> &std::shared_ptr<restbed::Response>::operator =(std::shared_ptr<restbed::Response> &&) noexcept'
2>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(577): note: or       'std::shared_ptr<restbed::Response> &std::shared_ptr<restbed::Response>::operator =<restbed::Response>(const std::shared_ptr<restbed::Response> &) noexcept'
2>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(559): note: or       'std::shared_ptr<restbed::Response> &std::shared_ptr<restbed::Response>::operator =<restbed::Response>(std::shared_ptr<restbed::Response> &&) noexcept'
2>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\future(380): note: while trying to match the argument list '(const std::shared_ptr<restbed::Response>, const std::shared_ptr<restbed::Response>)'
2>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\future(376): note: while compiling class template member function 'void std::_Associated_state<_Ty>::_Set_value_raw(_Ty &,std::unique_lock<std::mutex> *,bool)'
2>          with
2>          [
2>              _Ty=const std::shared_ptr<restbed::Response>
2>          ]
2>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\future(371): note: see reference to function template instantiation 'void std::_Associated_state<_Ty>::_Set_value_raw(_Ty &,std::unique_lock<std::mutex> *,bool)' being compiled
2>          with
2>          [
2>              _Ty=const std::shared_ptr<restbed::Response>
2>          ]
2>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\future(1492): note: see reference to class template instantiation 'std::_Associated_state<_Ty>' being compiled
2>          with
2>          [
2>              _Ty=const std::shared_ptr<restbed::Response>
2>          ]
2>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\future(1492): note: while compiling class template member function 'std::promise<const std::shared_ptr<restbed::Response>>::promise(void)'
2>  E:\Stacks\restbed\source\corvusoft\restbed\http.cpp(186): note: see reference to function template instantiation 'std::promise<const std::shared_ptr<restbed::Response>>::promise(void)' being compiled
2>  E:\Stacks\restbed\source\corvusoft\restbed\http.cpp(186): note: see reference to class template instantiation 'std::promise<const std::shared_ptr<restbed::Response>>' being compiled
2>  string.cpp
2>  request.cpp
2>  service.cpp
2>  session.cpp
2>  resource.cpp
2>  response.cpp
2>  settings.cpp
2>  ssl_settings.cpp
2>  session_manager.cpp
2>  http_impl.cpp
2>  Generating Code...
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

**Comment by ben-crowhurst** [comment]
We'll investigate this shortly.  If you find a solution to this issue please do let us know.

**Comment by pengweichu** [comment]
Finally I got it resolved, just remove the "const", please download the attached diff file - remove the .png extension name then open it.

Note: for VS2012 and VS2015, we must include the iso646.h to compatibles the "not", "not_eq", "or", "and" operators.

![restbed diff](https://cloud.githubusercontent.com/assets/12697283/13050363/d8366188-d42d-11e5-901d-5c66210012ce.png)

**Comment by ben-crowhurst** [comment]
Fantastic news @pengweichu. Could you please submit a pull request with your changes?  That way others can track your contributions to the project :D

Welcome to the team.

**Comment by pengweichu** [comment]
@ben-crowhurst I'm sorry I really don't know how to submit the PR with TortoiseSVN.
