### ISSUE TITLE
How to set the server side expires ?

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#76]
For example, when the server received the request, and query the database, but it's blocked long time will cause the request timeout, any way to specify this expires value ?

**Comment by ben-crowhurst** [comment]
`Settings::set_connection_timeout` should do the job.

``` C++
  ...
  void set_connection_timeout( const std::chrono::seconds& value );
            
  void set_connection_timeout( const std::chrono::milliseconds& value );
   ...
```

If these methods are not working for you please present your code, you may be blocking the event-loop from performing its work correctly.
