### ISSUE TITLE
Crash error when expired

### ISSUE THREAD

**Issue by pengweichu** [Corvusoft/restbed#78]
I got a crash error when debug the application step by step in the POST handler. It's seems the m_timer is released but not set to NULL, and we still try to access it.

In the call stack I can see the m_timer value is 0xfeeefeeefeeefeee.

Please see attached the screenshot, 

![error](https://cloud.githubusercontent.com/assets/12697283/13370562/98081d32-dd46-11e5-8eef-274f3764f117.png)

**Comment by callum-kirby** [comment]
Please could you present a code example.  Strictly speaking the SocketImpl::m_timer instance will not be reclaimed until SocketImpl class destruction.   How this timer becomes an deallocated without the entire SocketImpl instance being destructed is baffling.

**Comment by pengweichu** [comment]
@callum-kirby It's very hard to reproduce it every times, I just encountered it in my project sometimes, I will try find an easy to replicate it .

**Comment by pengweichu** [comment]
Please close this issue, I believe that is my wrong code cause it.

**Comment by ben-crowhurst** [comment]
Thanks for letting us know @pengweichu.

**Comment by ben-crowhurst** [comment]
@pengweichu We're about to tag Restbed 4.0.  I'm just looking to check you're not having any further issues with the latest product on Windows?

**Comment by pengweichu** [comment]
@ben-crowhurst  thanks for update, I will test it and feedback.

Best regards,
