### ISSUE TITLE
Continuous Integration.

### ISSUE THREAD

**Issue by ben-crowhurst** [Corvusoft/restbed#81]
- Update Travis-CI settings to include at least G++, Clang on Linux, Windows, FreeBSD, and Mac OSX platforms.
- Test project build with and without SSL enabled.

**Comment by ben-crowhurst** [comment]
Windows CI is delayed due to AppVeyor bugs.  See [ticket](http://help.appveyor.com/discussions/questions/2794-vs2015-x64-native-tools-command-prompt) we've open for further details.

**Comment by nunojpg** [comment]
Hi :smile: 

What do you mean by Windows on Travis-CI? Is there a plan to add cross compilation?

Is it possible to find Windows binaries or to provide them? I'm currently cross compiling to Windows and not sure how easy is to cross compile restbed so I am planning to just plug binaries.

Thanks!

**Comment by ben-crowhurst** [comment]
Restbed currently builds under Windows Visual Studio 2015 without any problems. We are seeking an automatic build on Windows for testing purposes.

**Comment by nunojpg** [comment]
Thanks for the clarification and thanks for the great product.

**Comment by ben-crowhurst** [comment]
AppVeyor configuration is now in place.
