### ISSUE TITLE
Server-Sent Events

### ISSUE THREAD

**Issue by gitaaronc** [Corvusoft/restbed#84]
Is it possible to implement Server-Sent Events with restbed? 
Can I send data using restbed without closing the connection? Would I use yield?
I've just starting using your library, so far it's working beautifully. Nice work!

**Comment by ben-crowhurst** [comment]
Correct Session::yield will return data without closing the active client session. See [Transfer-Encoding](https://github.com/Corvusoft/restbed/blob/master/example/transfer_encoding_response/source/example.cpp) example for details.

**Comment by gitaaronc** [comment]
Thank you.

**Comment by callum-kirby** [comment]
Documentation is coming immediately after the 4.0 release, which is on hold pending [OpenSSL 1.0.2g](https://github.com/chriskohlhoff/asio/pull/115).
