### ISSUE TITLE
Session objects leak permanently

### ISSUE THREAD

**Issue by willmmiles** [Corvusoft/restbed#85]
Hi,

I was tracking a memory leak issue in my application, and I found what appears to be a self-reference problem with Session objects.   When a Session is created by the Service, the bind calls at source/corvusoft/restbed/detail/service_impl.cpp:295 or :522 store a shared_ptr to the Session inside one of the Session's own members.  This means that the Session's shared_ptr's use_count will always be >=1 -- essentially the Session is pointing to itself -- and thus the Session will be leaked and never destructed.   It looks like this bug was introduced by commit dedc9a4.

Given that it looks like there's a refactor in progress, it wasn't immediately apparent what the best way to solve this was.   Any guidance on how best to fix this would be appreciated.

Thanks,

Will

**Comment by callum-kirby** [comment]
Thanks for highlighting this issue, I'll get back to you shortly with a fix.

**Comment by callum-kirby** [comment]
@willmmiles, We've pushed a possible fix for the memory leak.  Would appreciate you confirming it on your end.

**Comment by willmmiles** [comment]
Yes, I can confirm that this patch does fix the issue.   Thank you very much!
