### ISSUE TITLE
Set_Path for unknown number of params?

### ISSUE THREAD

**Issue by webbrandon** [Corvusoft/restbed#88]
Can you allow for a path with known `params` to have an additional number of unknown `params`?  Thought I should check with your team but it looks like you must declare each `param`. 

---

I would assume the library does or will be able to account for paths that are dynamic.  What I mean is you shouldn't need to declare path `params` and a url should parse paths so `get_path_parameters` returns a `map` with generated `id`'s on undeclared `params`.

---

**Pseudo Concept**

*Example call for an unknown number of `params` and their values in a path:*
```c++
resource->set_path( "/foo/bar/{id:.*}/{^.*/(.+)/.*.+}" );
```

*Paths:* (`params` length, value and numbers are defined by user)
`/foo/bar/unknown/unknown2/unknown3/unknown.js`,
`/foo/bar/unknown/unknown2/`,
`/foo/bar/unknown/unknown2/unknown3/unknown4`

*Returns:*
What I might expect after `get_path_parameters`:
```console
id : "unknown"    |  id : "unknown"  |  id : "unknown" 
1 : "unknown2"    |  1 : "unknown2"  |  1 : "unknown2" 
2 : "unknown3"    |  ...             |  2 : "unknown3"
3 : "unknown.js"  |                  |  3 : "unknown4"
...               |                  | ...            
```

**Comment by callum-kirby** [comment]
This feature is not currently supported.  We would need to hear a strong argument for add this additional complexity over performing the following:

``` C++
void get_method_handler( const shared_ptr< Session > session )
{
    const auto& request = session->get_request( );
    const auto directories = String::split( request->get_path( ), '/' );
    ...
}
```

**Comment by webbrandon** [comment]
Not sure I am following.  How do you get to a method handler that handles all routes so you can perform this operation?

I don't think it needs to strong a argument but here are just some random use cases without having to discuss how I need it for image generation.

**Use cases:**
1. *Wild file system linking.*  As a developer building a remote file system I need to deliver any path to a file that is created without having to recompile every time.
2. *User defined url request.*  As a user I want to make request define how my data gets named.
3. *Fallback pages.*  As a developer I want to have custom HTML pages delivered for any unsuccessful routes so the user may receive the message as I choose to display it.  Example `("/") && ("/foo/bar")` fallback to `("/.*")` when they don't exist.

**Comment by ben-crowhurst** [comment]
Please see examples and server interface supplied with the codebase?

1. [serving html](https://github.com/Corvusoft/restbed/blob/master/example/serving_html/source/example.cpp)
2. [path parameters](https://github.com/Corvusoft/restbed/tree/master/example/path_parameters/source)
3. [error handlers](https://github.com/Corvusoft/restbed/blob/master/source/corvusoft/restbed/service.hpp#L85)

**Comment by webbrandon** [comment]
I'm sorry I must not be explaining myself or you haven't fully reviewed my example.

**Comment by palikar** [comment]
Is  this feature still being considered?
