### ISSUE TITLE
How to Run restbed

### ISSUE THREAD

**Issue by MadhusudhanaHV** [Corvusoft/restbed#91]
Hi,
Kindly let me know in restbed/README.md/Build, what is meant by test in the command "make test".

```
git clone --recursive https://github.com/corvusoft/restbed.git
mkdir restbed/build
cd restbed/build
cmake [-DBUILD_TESTS=YES] [-DBUILD_EXAMPLES=YES] [-DBUILD_SSL=NO] [-DBUILD_SHARED=YES] [-DCMAKE_INSTALL_PREFIX=/output-directory] ..
make [-j CPU_CORES+1] install
make test
```
Also please let me know the steps for how to start restbed and run Example .

Thanks and Regards,
Madhusudhana H V

**Comment by ben-crowhurst** [comment]
Invoking ```make test``` runs the unit, integration, and acceptance test suites.  This ensures everything is working correctly after you have built the framework.  

Each example illustrates usage at the top of the primary source file.

**Comment by MadhusudhanaHV** [comment]
On executing "make test" I am getting the following output.
make: *** No rule to make target 'test'.  Stop.

Kindly help me.

**Comment by ben-crowhurst** [comment]
You need to use the  ```cmake -DBUILD_TESTS``` switch to construct the test suites.

**Comment by MadhusudhanaHV** [comment]
On typing the command:
cmake -DBUILD_TESTS=YES 
it is giving me error as follows:
CMake Error: The source directory "/home/madhusudhana/Documents/cApi/restbed/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Thanks and Regards,
Madhusudhana H V

**Comment by MadhusudhanaHV** [comment]
On typing the command:
cmake -DBUILD_TESTS=YES
it is giving me error as follows:
CMake Error: The source directory "/home/madhusudhana/Documents/cApi/restbed/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Thanks and Regards,
Madhusudhana H V

**Comment by MadhusudhanaHV** [comment]
In the path restbed/README.md/Build, it is given as follows:

git clone --recursive https://github.com/corvusoft/restbed.git
mkdir restbed/build
cd restbed/build
cmake [-DBUILD_TESTS=YES] [-DBUILD_EXAMPLES=YES] [-DBUILD_SSL=NO] [-DBUILD_SHARED=YES] [-DCMAKE_INSTALL_PREFIX=/output-directory] ..
make [-j CPU_CORES+1] install
make test

In step 3, instead of:
 "cd restbed/build"

 I did:
" cd restbed"

rest of the commands worked.

Please let me know what I should do after "make test" command.

Thanks and Regards,
Madhusudhana H V

**Comment by ben-crowhurst** [comment]
Please read [beginners guide to bash](http://www.tldp.org/LDP/Bash-Beginners-Guide/html/
).

```
git clone --recursive https://github.com/corvusoft/restbed.git
mkdir restbed/build
cd restbed/build
cmake -DBUILD_TESTS=YES -DBUILD_EXAMPLES=YES -DBUILD_SSL=NO ..
make [-j CPU_CORES+1] install
make test
```

**Comment by MadhusudhanaHV** [comment]
Thanks Ben. It is working. :)
