### ISSUE TITLE
Embedding 'Client usage part of Examples' in C Program.

### ISSUE THREAD

**Issue by MadhusudhanaHV** [Corvusoft/restbed#93]
Hi,

Kindly let me know how to embed in C program, the following command line GET and POST,  

curl -w'\n' -v -X POST --data 'Hello, Restbed' 'http://localhost/resource'
curl -w'\n' -v --digest -XGET 'http://Corvusoft:Glasgow@localhost:1984/resource'

Thanks and Regards,
Madhusudhana H V

**Comment by ben-crowhurst** [comment]
Please review [examples](https://github.com/Corvusoft/restbed/tree/master/example/https_client) before raising issues.

**Comment by ben-crowhurst** [comment]
@MadhusudhanaHV What are you building? Sounds fun.
