### ISSUE TITLE
How to Compile Our API? and how to Invoke API from a C program?.

### ISSUE THREAD

**Issue by MadhusudhanaHV** [Corvusoft/restbed#94]
Hi,

We learned how to create API.

Kindly let me know 
(1)how to Compile our API and
(2)How to Invoke the API from a C program.

Thanks and Regards,
Madhusudhana H V

**Comment by siddharudh** [comment]
Hi Madhusudhana,

This place is not a user forum so please don't post your help requests as issues here unless you're sure that you're reporting a bug or enhancement request about restbed library.

Please check **example** folder to learn more about how to use the restbed library.

**Comment by MadhusudhanaHV** [comment]
OK

**Comment by ben-crowhurst** [comment]
@MadhusudhanaHV If you'd like to purchase a license, required for commercial projects, and associated support package, then you'll receive the level of care you desire.

Please email sales@corvusoft.co.uk for affordable licensing and support options.
