### ISSUE TITLE
example/http_client/source/example.cpp  crashed.

### ISSUE THREAD

**Issue by dayn9t** [Corvusoft/restbed#96]
file: example/http_client/source/example.cpp
compiler: vs2015

The release build crashed, but the debug build works well.

**Comment by dayn9t** [comment]
compiler: vs2015 with update2

**Comment by callum-kirby** [comment]
Please provide more information.

**Comment by Puneetsharma030** [comment]
Hi,

I am also experiencing the same issue while using the release mode. The programs works fine with debug mode but crashes while exiting in release. There might be some issue with the destructors or memory de-allocation in release. Attached is the call stack.
![call_stack](https://cloud.githubusercontent.com/assets/5556978/15389784/e4b702b2-1db8-11e6-8dac-437ef150e1e6.png)

**Comment by callum-kirby** [comment]
I'm attempting to replicate this issue and wondered if you could confirm what version of Restbed you have?

**Comment by dayn9t** [comment]
$ git log
commit e9357eb56678688d9db2f2e962a533eb4b274e98
Merge: 7f7d803 cf5746b
Author: Ben Crowhurst <ben.crowhurst@corvusoft.co.uk>
Date:   Thu May 12 17:44:13 2016 +1200

    Merge pull request #95 from charno/patch-1

    Add colon to ipv4 endpoint between address & port

**Comment by Puneetsharma030** [comment]
I have restbed version 4.0

**Comment by Puneetsharma030** [comment]
As additional information, I tried to check the call stack and flow for both debug and release builds. 
Before executing the requests, it makes several calls to ::EnterCriticalSection(&crit_section_); and ::DeleteCriticalSection(&crit_section_);

The last call to ::EnterCriticalSection(&crit_section_) fails when the program crashes. The normal calls enter critical section looks like call1 in the attachments. The failing call looks like call2. In release build its always like call2 for the last call which crashes. In debug version the scenario looks like call3 which also looks weird like some garbage data, but that prevents the crash.

![call1](https://cloud.githubusercontent.com/assets/5556978/15671568/b7a7a8c2-272b-11e6-9804-f7b88b65ea76.png)
![call2](https://cloud.githubusercontent.com/assets/5556978/15671569/b7a7dec8-272b-11e6-962f-d7a6e8e5209b.png)
![call3](https://cloud.githubusercontent.com/assets/5556978/15671570/b7a8aab0-272b-11e6-8032-f92cd1b4710f.png)

**Comment by callum-kirby** [comment]
Thanks @Puneetsharma030.  This is a priority for me this week with a solution being made available shortly.

**Comment by callum-kirby** [comment]
This issue includes the test suites in Release mode, can anyone independently confirm this?

```
An unhandled win32 exception occurred in publishing_single_path_resources_http_connect_acceptance_test_suite.exe [4980].
```

**Comment by callum-kirby** [comment]
Guys I've pushed a fix for this issue.

It relates to the bidirectional relationships of a HTTP Request and its associated Response.  This will be removed in [future](https://github.com/Corvusoft/restbed/issues/103) versions.

Sorry for the delay, please confirm resolution.

**Comment by Puneetsharma030** [comment]
I confirm that this fix has resolved the issue. Thanks a lot for all the support.
