### ISSUE TITLE
Could use std::unique_ptr to clean up

### ISSUE THREAD

**Issue by vinniefalco** [Corvusoft/restbed#98]
I see
```
unsigned char* data = new unsigned char[ length ];
...
delete data[]
```

in some places, this could be done with
```
std::unique_ptr<unsigned char[]> data = new unsigned char[length];
```

For example, here:
https://github.com/Corvusoft/restbed/blob/6d6eb19ab8223fc385508cbd220a7a2d28f998ed/example/compression/source/example.cpp#L46

**Comment by ben-crowhurst** [comment]
Please feel free to submit a Pull Request with the desired change.

**Comment by MasihAkbari** [comment]
I submitted a Pull Request about this subject please take a look

**Comment by ben-crowhurst** [comment]
This issue has been resolved, thanks for your hard work 👍
